In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/My Drive/IISC_data/

/content/drive/My Drive/IISC_data

In [ ]:
import os
print(os.listdir('.'))

['metadata.csv', 'sample_submission.csv', 'test.csv', 'train.csv', 'submission_blend.csv', 'submission_blend_tuned_bias.csv', 'submission_convex5_tuned_bias.csv', 'alpha_table.parquet', 'bias_table.parquet', 'submission_blend_tuned_bias_smooth_clip.csv', 'submission_blend_cf.csv', 'beta_table_cf.parquet', 'submission_blend_cf_lag24.csv', 'submission_calibrated.csv', 'submission_calibrated_lagmix_v2.csv', 'submission_calibrated_lagmix_safe.csv', 'alpha_table_cf.parquet', 'bias_table_cf.parquet', 'beta24_table.parquet', 'beta168_table.parquet', 'gamma_table.parquet', 'lambda_table.parquet', 'submission_final.csv', 'submission_final_nonull.csv', 'wknd_table.parquet', 'quant_bhoff.parquet', 'quant_b.parquet', 'quant_global.txt', 'submission_postproc_weekend_smooth_clip.csv', 'submission_ens_f60_c30_l10.csv', 'submission_ens_f70_c20_l10.csv', 'submission_ens_median_top.csv', 'submission_ens_trimmed.csv.csv', 'submission_ens_winsor.csv.csv', 'submission_ens_power05.csv.csv', 'submission_ens_medfin_60_40.csv.csv', 'submission_ens_medfin_70_30.csv.csv', 'submission_ens_medfin_80_20.csv', 'submission_ens_medfin_75_25.csv', 'submission_stack_med85_lgbm15.csv', 'submission_stack_med80_lgbm20.csv', 'submission_stack_m70_f20_l10.csv', 'submission_stack_m60_f25_l15.csv', 'submission_stack_m50_f30_l20.csv', 'pred_tr_lgbm.parquet', 'submission_lgbm.csv', 'stack_weights_bh.parquet', 'stack_weights_b.parquet', 'submission_superstack.csv', 'submission_superstack_safe.csv', 'stack_w_bh.parquet', 'stack_w_b.parquet', 'submission_meta_wlgbm.csv', 'submission_meta_wlgbm_safe.csv', 'submission_iso_stack.csv', 'submission_iso_stack_loose.csv', 'submission_med_lgbm_hsched_tau8.csv', 'submission_med_lgbm_w22.csv', 'submission_med_lgbm_w24.csv', 'submission_med_lgbm_w18.csv', 'submission_med_lgbm_power05.csv', 'submission_med_lgbm_w23.csv', 'submission_knn_building.csv', 'submission_knn_blend_70_20_10.csv', 'submission_knn_blend_75_20_05.csv', 'submission_med_lgbm_w23_resave.csv', 'submission_med_lgbm_w240.csv', 'submission_med_lgbm_w245.csv', 'pred_ttm_tr.parquet', 'submission_med_lgbm_ttmBoost_65_20_15.csv', 'submission_hod.csv', 'submission_ttm.csv', 'submission_ttm_boost.csv', 'submission_lgbm_direct.csv', 'submission_stack_cvmed.csv', 'submission_med_lgbm_w232_c18.csv', 'submission_med_lgbm_w238_c18.csv', 'submission_med_lgbm_w245_c18.csv', 'submission_med_lgbm_w238_c15.csv', 'submission_med_lgbm_w250_c18.csv', 'submission_med_lgbm_sched_smooth_clip.csv', 'submission_med_lgbm_w235_c18_winsor2_15.csv', 'submission_med_lgbm_w233_c18_winsor1_15.csv', 'submission_med_lgbm_w237_c18.csv', 'submission_med_lgbm_w235_c17.csv', 'submission_adaptive_gate_fix.csv.csv', 'submission_adaptive_gate_safe_fix.csv.csv', 'submission_med_lgbm_w236.csv', 'submission_med_lgbm_w234.csv', 'submission_med_lgbm_w235.csv', 'submission_med_lgbm_w2352.csv', 'submission_med_lgbm_w2348.csv', 'submission_med_lgbm_piecewise.csv', 'submission_med_lgbm_w23503.csv', 'submission_med_lgbm_w23497.csv', 'submission_med_lgbm_piece_micro.csv', 'submission_med_lgbm_w23502.csv', 'submission_med_lgbm_presmooth_w23505.csv', 'submission_med_lgbm_dualsmooth_w23503.csv', 'w_bh.parquet', 'w_b.parquet', 'submission_med_lgbm_wBH.csv', 'pred_ttm_r2_tr.parquet', 'pred_ttm_r2_te.parquet', 'pred_ttm_r1_tr.parquet', 'pred_ttm_r1_te.parquet', 'ttm_affine_bh.parquet', 'submission_ttmCal_med_lgbm.csv', 'submission_blend_ttm_ridge_lgbm.csv', 'submission_blend_ttm_ridge_lgbm_shrink0p1.csv']

In [ ]:
import pandas as pd

metadata_df = pd.read_csv('metadata.csv')
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
sample_submission_df = pd.read_csv('sample_submission.csv')


print("Metadata DataFrame:")
display(metadata_df.head())

print("\nTrain DataFrame:")
display(train_df.head())

print("\nTest DataFrame:")
display(test_df.head())

print("\nSample Submission DataFrame:")
display(sample_submission_df.head())

Metadata DataFrame:

,building_id,region,rooms,no_of_people,area_in_sqft,inverter,lights,ceiling_fans,air_coolers,air_conditioners,fridge,tv,water_heaters,washing_machine,mixer,iron,micro_wave
0,H001,Pune city,3.0,3,625.0,0.0,19,3,0,0.0,1,1,0,1,1,1,1
1,H002,Pune city,5.0,4,1100.0,0.0,14,5,0,3.0,1,1,1,1,1,1,1
2,H003,Pune city,5.0,2,1000.0,0.0,16,6,0,0.0,1,1,3,1,1,1,1
3,H005,Pune city,4.0,5,NaN,0.0,4,3,0,1.0,1,0,0,0,0,1,1
4,H006,Pune city,3.0,4,530.0,0.0,0,0,0,0.0,0,0,0,0,0,0,0

Train DataFrame:

  building_id  window_id            timestamp  meter_reading   role
0        H001          1  2018-07-01 00:00:00         1.4081  input
1        H001          1  2018-07-01 01:00:00         0.8785  input
2        H001          1  2018-07-01 02:00:00         0.4504  input
3        H001          1  2018-07-01 03:00:00         0.6049  input
4        H001          1  2018-07-01 04:00:00         0.2719  input

Test DataFrame:

   row_id building_id  window_id            timestamp  meter_reading   role
0       1        H001          1  2019-07-09 00:00:00         0.6062  input
1       2        H001          1  2019-07-09 01:00:00         0.8477  input
2       3        H001          1  2019-07-09 02:00:00         0.3375  input
3       4        H001          1  2019-07-09 03:00:00         0.5490  input
4       5        H001          1  2019-07-09 04:00:00         0.3079  input

Sample Submission DataFrame:

   row_id  meter_reading
0     169              0
1     170              0
2     171              0
3     172              0
4     173              0

In [ ]:
DATA_DIR = "/content/drive/My Drive/IISC_data"
OUTPUT_DIR = DATA_DIR  # save submissions next to data

In [ ]:
import os, pathlib
os.chdir(DATA_DIR)
print("CWD:", os.getcwd())
print("Files:", os.listdir("."))

CWD: /content/drive/My Drive/IISC_data
Files: ['metadata.csv', 'sample_submission.csv', 'test.csv', 'train.csv', 'submission_blend.csv', 'submission_blend_tuned_bias.csv', 'submission_convex5_tuned_bias.csv', 'alpha_table.parquet', 'bias_table.parquet', 'submission_blend_tuned_bias_smooth_clip.csv', 'submission_blend_cf.csv', 'beta_table_cf.parquet', 'submission_blend_cf_lag24.csv', 'submission_calibrated.csv', 'submission_calibrated_lagmix_v2.csv', 'submission_calibrated_lagmix_safe.csv', 'submission_hod.csv', 'submission_ttm.csv', 'alpha_table_cf.parquet', 'bias_table_cf.parquet', 'beta24_table.parquet', 'beta168_table.parquet', 'gamma_table.parquet', 'lambda_table.parquet', 'submission_final.csv', 'submission_final_nonull.csv', 'wknd_table.parquet', 'quant_bhoff.parquet', 'quant_b.parquet', 'quant_global.txt', 'submission_postproc_weekend_smooth_clip.csv', 'submission_ens_f60_c30_l10.csv', 'submission_ens_f70_c20_l10.csv', 'submission_ens_median_top.csv']

In [ ]:
!pip -q install "granite-tsfm[notebooks]==0.3.1"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.3/66.3 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 94.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 5.7 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np
import torch
from tsfm_public import (
    TimeSeriesForecastingPipeline,
    TinyTimeMixerForPrediction,
    TimeSeriesPreprocessor,
)
pd.set_option("display.max_columns", 200)

# Determinism
seed = 42
np.random.seed(seed); torch.manual_seed(seed)
torch.set_float32_matmul_precision("high")
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
metadata_df = pd.read_csv(f"{DATA_DIR}/metadata.csv")
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])
sample_submission_df = pd.read_csv(f"{DATA_DIR}/sample_submission.csv")

display(metadata_df.head())
display(train_df.head())
display(test_df.head())
display(sample_submission_df.head())

print("Train shape:", train_df.shape, "| Test shape:", test_df.shape)

,building_id,region,rooms,no_of_people,area_in_sqft,inverter,lights,ceiling_fans,air_coolers,air_conditioners,fridge,tv,water_heaters,washing_machine,mixer,iron,micro_wave
0,H001,Pune city,3.0,3,625.0,0.0,19,3,0,0.0,1,1,0,1,1,1,1
1,H002,Pune city,5.0,4,1100.0,0.0,14,5,0,3.0,1,1,1,1,1,1,1
2,H003,Pune city,5.0,2,1000.0,0.0,16,6,0,0.0,1,1,3,1,1,1,1
3,H005,Pune city,4.0,5,NaN,0.0,4,3,0,1.0,1,0,0,0,0,1,1
4,H006,Pune city,3.0,4,530.0,0.0,0,0,0,0.0,0,0,0,0,0,0,0

  building_id  window_id           timestamp  meter_reading   role
0        H001          1 2018-07-01 00:00:00         1.4081  input
1        H001          1 2018-07-01 01:00:00         0.8785  input
2        H001          1 2018-07-01 02:00:00         0.4504  input
3        H001          1 2018-07-01 03:00:00         0.6049  input
4        H001          1 2018-07-01 04:00:00         0.2719  input

   row_id building_id  window_id           timestamp  meter_reading   role
0       1        H001          1 2019-07-09 00:00:00         0.6062  input
1       2        H001          1 2019-07-09 01:00:00         0.8477  input
2       3        H001          1 2019-07-09 02:00:00         0.3375  input
3       4        H001          1 2019-07-09 03:00:00         0.5490  input
4       5        H001          1 2019-07-09 04:00:00         0.3079  input

   row_id  meter_reading
0     169              0
1     170              0
2     171              0
3     172              0
4     173              0

Train shape: (2582976, 5) | Test shape: (676800, 6)

In [ ]:
# Hour-of-Day baseline (fixed)
# Ensure timestamp is datetime
test_df = test_df.copy()
test_df["timestamp"] = pd.to_datetime(test_df["timestamp"])

# Build hour-of-day mean from the 168h inputs per window_id
inputs = (
    test_df.query("role == 'input'")
           .assign(hod=lambda x: x["timestamp"].dt.hour)
)

hod_means = (
    inputs.groupby(["window_id", "hod"])["meter_reading"]
          .mean()
          .rename("hod_mean")
)

targets = (
    test_df.query("role == 'target'")
           .assign(hod=lambda x: x["timestamp"].dt.hour)
           [["row_id", "window_id", "hod"]]
)

sub_hod = targets.merge(hod_means, on=["window_id", "hod"], how="left")

# If any hod bucket is missing, fall back to window mean
wmean = inputs.groupby("window_id")["meter_reading"].mean().rename("wmean")
sub_hod = sub_hod.merge(wmean, on="window_id", how="left")

sub_hod["meter_reading"] = (
    sub_hod["hod_mean"].fillna(sub_hod["wmean"]).clip(lower=0)
)

sub_hod = (
    sub_hod[["row_id", "meter_reading"]]
    .sort_values("row_id")
    .reset_index(drop=True)
)

hod_path = f"{OUTPUT_DIR}/submission_hod.csv"
sub_hod.to_csv(hod_path, index=False)
print("Wrote:", hod_path, "| shape:", sub_hod.shape)

Wrote: /content/drive/My Drive/IISC_data/submission_hod.csv | shape: (84600, 2)

In [ ]:
# Preprocessor config
timestamp_column = "timestamp"
target_columns = ["meter_reading"]
context_length = 180       # TTM r2 checkpoint expects 180h context
forecast_length = 60       # ...and predicts 60 steps
id_columns = ["building_id", "window_id"]  # per-series scaling

# Fit scaler on all INPUT rows (safe)
tsp = TimeSeriesPreprocessor(
    timestamp_column=timestamp_column,
    id_columns=id_columns,
    target_columns=target_columns,
    control_columns=[],
    context_length=context_length,
    forecast_length=forecast_length,
    scaling=True,
    scaler_type="standard",
    freq="h",
)
tsp.train(test_df.query("role == 'input'"))

# Load model
ttm = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=len(target_columns),
).eval()

pipeline = TimeSeriesForecastingPipeline(
    ttm, explode_forecasts=True, feature_extractor=tsp, device=device
)

# Helper: pad each window from 168h to 180h by repeating the first 12 hours
def pad_to_180(win_df: pd.DataFrame) -> pd.DataFrame:
    win = win_df.sort_values(timestamp_column).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[timestamp_column] = pad[timestamp_column] - pd.to_timedelta(
            np.arange(12, 0, -1), unit="h"
        )
        win = pd.concat([pad, win], ignore_index=True).sort_values(timestamp_column)
    return win

# Forecast per window
ttm_rows = []
for wi, wdf in test_df.groupby("window_id", sort=False):
    current_inp = wdf[wdf["role"]=="input"].copy()
    current_out = wdf[wdf["role"]=="target"][["row_id", "timestamp"]].copy()

    inp_padded = pad_to_180(current_inp)
    pred = pipeline(inp_padded)           # returns 60-step forecast
    pred24 = pred.iloc[:24][["meter_reading"]].reset_index(drop=True)  # take first 24

    tmp = current_out.reset_index(drop=True)
    tmp["meter_reading_ttm"] = pred24["meter_reading"].astype(float).clip(lower=0)
    ttm_rows.append(tmp)

sub_ttm = pd.concat(ttm_rows, ignore_index=True)
ttm_path = f"{OUTPUT_DIR}/submission_ttm.csv"
sub_ttm.rename(columns={"meter_reading_ttm":"meter_reading"})[["row_id","meter_reading"]].to_csv(ttm_path, index=False)
print("Wrote:", ttm_path, "| shape:", sub_ttm.shape)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.04M [00:00<?, ?B/s]

Device set to use cpu

Wrote: /content/drive/My Drive/IISC_data/submission_ttm.csv | shape: (84600, 3)

In [ ]:
# Robust blend: rename columns, merge, compute final meter_reading

# 1) Ensure expected column names
if "meter_reading" in sub_hod.columns and "meter_reading_hod" not in sub_hod.columns:
    sub_hod = sub_hod.rename(columns={"meter_reading": "meter_reading_hod"})

# sub_ttm from the TTM step typically has ['row_id','timestamp','meter_reading_ttm'].
# If it was saved as 'meter_reading', rename it too:
if "meter_reading" in sub_ttm.columns and "meter_reading_ttm" not in sub_ttm.columns:
    sub_ttm = sub_ttm.rename(columns={"meter_reading": "meter_reading_ttm"})

# 2) Merge on row_id
sub_blend = sub_hod.merge(sub_ttm[["row_id", "meter_reading_ttm"]], on="row_id", how="left")

# 3) Blend
ALPHA = 0.7  # weight on TTM (tune later if needed)
sub_blend["meter_reading_hod"] = sub_blend["meter_reading_hod"].astype(float)
sub_blend["meter_reading"] = (
    ALPHA * sub_blend["meter_reading_ttm"].fillna(sub_blend["meter_reading_hod"]) +
    (1 - ALPHA) * sub_blend["meter_reading_hod"]
).clip(lower=0)

# 4) Save submission
blend_path = f"{OUTPUT_DIR}/submission_blend.csv"
sub_blend[["row_id", "meter_reading"]].sort_values("row_id").to_csv(blend_path, index=False)
print("Wrote:", blend_path, "| shape:", sub_blend.shape)

Wrote: /content/drive/My Drive/IISC_data/submission_blend.csv | shape: (84600, 4)

In [ ]:
import pandas as pd, numpy as np
from tqdm import tqdm

# Reuse the same pad function; define if not present
def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

# Tag each window's targets with horizon offset 0..23
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out = out.sort_values(["window_id", "timestamp"])
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Quick TTM forecaster for a list of window_ids on a given dataframe (train or test)
def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows"):
        wdf = df[df["window_id"]==wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

In [ ]:
# Reuse your chosen N_WINDOWS and sample
N_WINDOWS = 1000
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=42).tolist()

# Context/forecast to match TTM r2 (180→60)
timestamp_column = "timestamp"
target_columns = ["meter_reading"]
id_columns = ["building_id", "window_id"]
context_length = 180
forecast_length = 60

# Fit the preprocessor ONLY on the sampled TRAIN inputs (so it has scalers for those ids)
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
import numpy as np, torch

train_inputs_sel = train_df.query("role=='input' and window_id in @sample_wids").copy()

tsp_train = TimeSeriesPreprocessor(
    timestamp_column=timestamp_column,
    id_columns=id_columns,
    target_columns=target_columns,
    control_columns=[],
    context_length=context_length,
    forecast_length=forecast_length,
    scaling=True,
    scaler_type="standard",
    freq="h",
)
tsp_train.train(train_inputs_sel)

ttm_train = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline_tr = TimeSeriesForecastingPipeline(
    ttm_train, explode_forecasts=True, feature_extractor=tsp_train, device=device
)

print("Train pipeline ready on", len(sample_wids), "windows. Device:", device)

Device set to use cpu

Train pipeline ready on 1000 windows. Device: cpu

In [ ]:
from sklearn.metrics import mean_squared_error
alphas = np.linspace(0, 1, 21)

best = []
# Ensure numeric types once
feat["y_hod"] = pd.to_numeric(feat["y_hod"], errors="coerce")
feat["y_weekly"] = pd.to_numeric(feat["y_weekly"], errors="coerce")
feat["y_ttm"] = pd.to_numeric(feat["meter_reading_ttm"], errors="coerce")
feat["ytrue"] = pd.to_numeric(feat["ytrue"], errors="coerce")

for (bid, hoff), g in feat.dropna(subset=["ytrue", "y_hod"]).groupby(["building_id","h_offset"], sort=False):
    yh = g["y_hod"].to_numpy()
    # FIX: use Series fallback (aligned by index), not ndarray
    yt = g["y_ttm"].fillna(g["y_hod"]).to_numpy()
    y  = g["ytrue"].to_numpy()

    # optional safety
    yh = np.clip(yh, 0, None)
    yt = np.clip(yt, 0, None)

    best_a, best_m = None, None
    for a in alphas:
        yhat = np.clip(a*yt + (1-a)*yh, 0, None)
        m = mean_squared_error(y, yhat)
        if best_m is None or m < best_m:
            best_a, best_m = float(a), m

    best.append((bid, hoff, best_a, best_m))

alpha_table = pd.DataFrame(best, columns=["building_id","h_offset","alpha","cv_mse"])
print("Learned alphas:", alpha_table.shape)

Learned alphas: (2184, 4)

In [ ]:
import pandas as pd
import numpy as np

# Recreate feat_valid from 'feat'
# Make sure required columns are numeric
for col in ["ytrue", "y_hod", "y_ttm", "y_weekly"]:
    if col in feat.columns:
        feat[col] = pd.to_numeric(feat[col], errors="coerce")

# Keep rows with ground truth + HoD available
feat_valid = feat.dropna(subset=["ytrue", "y_hod"]).copy()

# Merge learned alphas per (building_id, h_offset)
feat_bias = feat_valid.merge(alpha_table, on=["building_id","h_offset"], how="left")
feat_bias["alpha"] = feat_bias["alpha"].fillna(0.0)  # default to pure HoD if alpha missing

# Compute blended train predictions and residuals
yhat_train = (
    feat_bias["alpha"] * feat_bias["y_ttm"].fillna(feat_bias["y_hod"]) +
    (1.0 - feat_bias["alpha"]) * feat_bias["y_hod"]
).clip(lower=0)

resid = feat_bias["ytrue"] - yhat_train

# Mean residual per (building_id, h_offset) -> bias correction
bias_table = (
    pd.DataFrame({"building_id": feat_bias["building_id"],
                  "h_offset": feat_bias["h_offset"],
                  "bias": resid})
    .groupby(["building_id","h_offset"])["bias"]
    .mean()
    .reset_index()
)

print("feat_valid:", feat_valid.shape, "| bias_table:", bias_table.shape)

feat_valid: (322872, 12) | bias_table: (2184, 3)

In [ ]:
# Helper to tag horizons 0..23 per window
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Build TEST targets with horizon offsets
test_targets = (
    test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]]
)
test_targets = add_hoffset(test_targets)

# Ensure column names from previous steps are consistent
# sub_hod should have ['row_id','meter_reading_hod']
if "meter_reading" in sub_hod.columns and "meter_reading_hod" not in sub_hod.columns:
    sub_hod = sub_hod.rename(columns={"meter_reading": "meter_reading_hod"})

# sub_ttm should have ['row_id','meter_reading_ttm']
if "meter_reading" in sub_ttm.columns and "meter_reading_ttm" not in sub_ttm.columns:
    sub_ttm = sub_ttm.rename(columns={"meter_reading": "meter_reading_ttm"})

# Join HoD, TTM, alpha, bias
blend = (
    test_targets
    .merge(sub_hod[["row_id","meter_reading_hod"]], on="row_id", how="left")
    .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left")
    .merge(alpha_table, on=["building_id","h_offset"], how="left")
    .merge(bias_table, on=["building_id","h_offset"], how="left")
)

# Defaults for unseen combos
blend["alpha"] = blend["alpha"].fillna(0.0)  # pure HoD when no alpha learned
blend["bias"]  = blend["bias"].fillna(0.0)

# Final prediction = convex blend + bias, clamp ≥0
blend["meter_reading_hod"] = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
blend["meter_reading_ttm"] = pd.to_numeric(blend["meter_reading_ttm"], errors="coerce").fillna(blend["meter_reading_hod"])

blend["meter_reading"] = (
    blend["alpha"] * blend["meter_reading_ttm"] +
    (1.0 - blend["alpha"]) * blend["meter_reading_hod"] +
    blend["bias"]
).clip(lower=0)

# Save
FINAL_PATH = f"{OUTPUT_DIR}/submission_blend_tuned_bias.csv"
blend[["row_id","meter_reading"]].sort_values("row_id").to_csv(FINAL_PATH, index=False)
print("Wrote:", FINAL_PATH, "| rows:", len(blend))

Wrote: /content/drive/My Drive/IISC_data/submission_blend_tuned_bias.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# 0) Start from your existing 'feat' frame that already has:
#    columns: ['building_id','window_id','timestamp','h_offset','ytrue','y_hod','y_ttm'] (y_ttm may be NaN for some rows)
# If you lost it, rebuild as in earlier cells; otherwise continue.

# 1) Extra baselines on TRAIN
trin = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
trin["hod"] = trin["timestamp"].dt.hour

# Weekly naive
idx_in = trin.set_index(["window_id","timestamp"])["meter_reading"].rename("y_lag168")
wk = feat[["window_id","timestamp"]].copy()
wk["timestamp_lag"] = wk["timestamp"] - pd.Timedelta(hours=168)
wk = wk.join(idx_in, on=["window_id","timestamp_lag"])

# Lag-24
idx24 = idx_in.rename("mr").rename(None)
lag24 = feat[["window_id","timestamp"]].copy()
lag24["timestamp_lag"] = lag24["timestamp"] - pd.Timedelta(hours=24)
lag24 = lag24.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"y_lag168":"y_lag24"})

# Last value in window (persistence)
last_val = (trin.sort_values("timestamp")
                 .groupby("window_id").tail(1)
                 .set_index("window_id")["meter_reading"].rename("y_last"))
feat = feat.merge(wk[["window_id","timestamp","y_lag168"]], on=["window_id","timestamp"], how="left")
feat = feat.merge(lag24[["window_id","timestamp","y_lag24"]], on=["window_id","timestamp"], how="left")
feat = feat.join(last_val, on="window_id")

# 2) Clean types & fallbacks
for c in ["ytrue","y_hod","y_ttm","y_lag168","y_lag24","y_last"]:
    feat[c] = pd.to_numeric(feat[c], errors="coerce")

# Fill NA bases with y_hod (safe shrinkage), then clip ≥0
for c in ["y_ttm","y_lag168","y_lag24","y_last"]:
    feat[c] = feat[c].fillna(feat["y_hod"]).clip(lower=0)

# 3) Learn non-negative ridge weights per (building_id, h_offset)
models = []
colsX = ["y_ttm","y_hod","y_lag168","y_lag24","y_last"]

for (bid, hoff), g in feat.dropna(subset=["ytrue","y_hod"]).groupby(["building_id","h_offset"], sort=False):
    X = g[colsX].values
    y = g["ytrue"].values
    # Ridge with positive coefficients; fit_intercept=False (we’ll add bias separately)
    reg = Ridge(alpha=1e-3, fit_intercept=False, positive=True)
    reg.fit(X, y)
    w = reg.coef_.astype(float)
    # Renormalize to sum-to-one (convex weights)
    s = w.sum()
    if s > 0:
        w = w / s
    models.append([bid, hoff] + list(w))

weight_table = pd.DataFrame(models, columns=["building_id","h_offset"] + [f"w_{c}" for c in colsX])
print("Weight table:", weight_table.shape)

# 4) Bias (mean residual) with the learned weights
tmp = feat.merge(weight_table, on=["building_id","h_offset"], how="left")
for c in colsX:
    tmp[f"w_{c}"] = tmp[f"w_{c}"].fillna(0.0)
# If weights missing, default to HoD
tmp["w_y_hod"] = np.where(tmp[[f"w_{c}" for c in colsX]].sum(axis=1)==0, 1.0, tmp["w_y_hod"])

yhat = (tmp["w_y_ttm"]*tmp["y_ttm"] +
        tmp["w_y_hod"]*tmp["y_hod"] +
        tmp["w_y_lag168"]*tmp["y_lag168"] +
        tmp["w_y_lag24"]*tmp["y_lag24"] +
        tmp["w_y_last"]*tmp["y_last"]).clip(lower=0)

resid = tmp["ytrue"] - yhat
bias_table = (pd.DataFrame({"building_id": tmp["building_id"],
                            "h_offset": tmp["h_offset"],
                            "bias": resid})
              .groupby(["building_id","h_offset"])["bias"]
              .mean().reset_index())
print("Bias table:", bias_table.shape)

Weight table: (2184, 7)
Bias table: (2184, 3)

In [ ]:
# 1) Build all bases on TEST
test_inp = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
test_inp["hod"] = test_inp["timestamp"].dt.hour

# HoD (already have sub_hod)
if "meter_reading" in sub_hod.columns and "meter_reading_hod" not in sub_hod.columns:
    sub_hod = sub_hod.rename(columns={"meter_reading":"meter_reading_hod"})

# TTM (already have sub_ttm)
if "meter_reading" in sub_ttm.columns and "meter_reading_ttm" not in sub_ttm.columns:
    sub_ttm = sub_ttm.rename(columns={"meter_reading":"meter_reading_ttm"})

# Weekly naive
idx_in_test = test_inp.set_index(["window_id","timestamp"])["meter_reading"].rename("y_lag168")
wk_te = test_df.query("role=='target'")[["row_id","window_id","timestamp"]].copy()
wk_te["timestamp_lag"] = wk_te["timestamp"] - pd.Timedelta(hours=168)
wk_te = wk_te.join(idx_in_test, on=["window_id","timestamp_lag"])

# Lag-24
lag24_te = test_df.query("role=='target'")[["row_id","window_id","timestamp"]].copy()
lag24_te["timestamp_lag"] = lag24_te["timestamp"] - pd.Timedelta(hours=24)
lag24_te = lag24_te.join(idx_in_test, on=["window_id","timestamp_lag"]).rename(columns={"y_lag168":"y_lag24"})

# Last value per window
last_val_te = (test_inp.sort_values("timestamp")
                    .groupby("window_id").tail(1)
                    .set_index("window_id")["meter_reading"].rename("y_last"))

# 2) Join everything + add h_offset and building_id
def add_hoffset(df):
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

test_targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]]
test_targets = add_hoffset(test_targets)

blend = (test_targets
         .merge(sub_hod, on="row_id", how="left")
         .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left")
         .merge(wk_te[["row_id","y_lag168"]], on="row_id", how="left")
         .merge(lag24_te[["row_id","y_lag24"]], on="row_id", how="left")
         .join(last_val_te, on="window_id"))

# Fill NA bases with HoD
blend["y_hod"] = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
for c_old, c_new in [("meter_reading_ttm","y_ttm"), ("y_lag168","y_lag168"), ("y_lag24","y_lag24"), ("y_last","y_last")]:
    blend[c_new] = pd.to_numeric(blend[c_old], errors="coerce")

for c in ["y_ttm","y_lag168","y_lag24","y_last"]:
    blend[c] = blend[c].fillna(blend["y_hod"]).clip(lower=0)

# 3) Attach weights + bias
blend = blend.merge(weight_table, on=["building_id","h_offset"], how="left") \
             .merge(bias_table, on=["building_id","h_offset"], how="left")

# Defaults where weights missing: pure HoD, zero bias
for c in [f"w_{k}" for k in ["y_ttm","y_hod","y_lag168","y_lag24","y_last"]]:
    blend[c] = blend[c].fillna(0.0)
row_sum = blend[[f"w_{k}" for k in ["y_ttm","y_hod","y_lag168","y_lag24","y_last"]]].sum(axis=1)
# If no weights found, set w_hod=1
blend.loc[row_sum.eq(0), "w_y_hod"] = 1.0
blend["bias"] = blend["bias"].fillna(0.0)

# 4) Final prediction (convex weights + bias), clamp ≥0
pred = (blend["w_y_ttm"]*blend["y_ttm"] +
        blend["w_y_hod"]*blend["y_hod"] +
        blend["w_y_lag168"]*blend["y_lag168"] +
        blend["w_y_lag24"]*blend["y_lag24"] +
        blend["w_y_last"]*blend["y_last"] + blend["bias"]).clip(lower=0)

sub_final = pd.DataFrame({"row_id": blend["row_id"], "meter_reading": pred}).sort_values("row_id")
out_path = f"{OUTPUT_DIR}/submission_convex5_tuned_bias.csv"
sub_final.to_csv(out_path, index=False)
print("Wrote:", out_path, "| rows:", len(sub_final))

Wrote: /content/drive/My Drive/IISC_data/submission_convex5_tuned_bias.csv | rows: 84600

In [ ]:
# Robust per-building × hour-of-day bounds (IQR-based) from TRAIN
train_all = train_df.copy()
train_all["timestamp"] = pd.to_datetime(train_all["timestamp"])
train_all["hod"] = train_all["timestamp"].dt.hour

g = train_all.groupby(["building_id","hod"])["meter_reading"]
q25 = g.quantile(0.25).rename("q25")
q75 = g.quantile(0.75).rename("q75")
iqr = (q75 - q25).rename("iqr")
bounds = pd.concat([q25, q75, iqr], axis=1).reset_index()
# Tukey-style limits; feel free to tighten/loosen 3.0 → 2.5/2.0 if needed
bounds["lo"] = (bounds["q25"] - 3.0 * bounds["iqr"]).clip(lower=0)
bounds["hi"] = (bounds["q75"] + 3.0 * bounds["iqr"])
bounds = bounds[["building_id","hod","lo","hi"]]
print("Bounds rows:", bounds.shape)

Bounds rows: (2184, 4)

In [ ]:
# Paths
DATA_DIR = "/content/drive/My Drive/IISC_data"

import os, pandas as pd, numpy as np

# Ensure dataframes exist
if "test_df" not in globals():
    test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])
if "train_df" not in globals():
    train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])

# Load HoD predictions saved earlier
if "sub_hod" not in globals():
    hod_path = f"{DATA_DIR}/submission_hod.csv"
    assert os.path.exists(hod_path), "submission_hod.csv not found. Re-run the HoD cell."
    sub_hod = pd.read_csv(hod_path).rename(columns={"meter_reading":"meter_reading_hod"})

# Load TTM predictions saved earlier
if "sub_ttm" not in globals():
    ttm_path = f"{DATA_DIR}/submission_ttm.csv"
    assert os.path.exists(ttm_path), "submission_ttm.csv not found. Re-run the TTM cell."
    sub_ttm = pd.read_csv(ttm_path).rename(columns={"meter_reading":"meter_reading_ttm"})

# Alpha/bias tables come from tuning cells; save + load these to avoid recompute:
# If you previously saved them, load now; otherwise they should still be in memory.
alpha_pq = f"{DATA_DIR}/alpha_table.parquet"
bias_pq  = f"{DATA_DIR}/bias_table.parquet"
if "alpha_table" not in globals() and os.path.exists(alpha_pq):
    alpha_table = pd.read_parquet(alpha_pq)
if "bias_table" not in globals() and os.path.exists(bias_pq):
    bias_table = pd.read_parquet(bias_pq)

# If they still don't exist, please re-run the tuning cells that create alpha_table & bias_table,
# and (optionally) save them:
# alpha_table.to_parquet(alpha_pq, index=False); bias_table.to_parquet(bias_pq, index=False)

print("Recovered:",
      f"sub_hod({sub_hod.shape})",
      f"sub_ttm({sub_ttm.shape})",
      f"alpha_table({'ok' if 'alpha_table' in globals() else 'missing'})",
      f"bias_table({'ok' if 'bias_table' in globals() else 'missing'})")

Recovered: sub_hod((84600, 2)) sub_ttm((84600, 2)) alpha_table(missing) bias_table(missing)

In [ ]:
# Rebuild alphas & bias without redoing everything else
import pandas as pd, numpy as np, torch
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
from sklearn.metrics import mean_squared_error
from tqdm import tqdm

# Helpers (define if missing)
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows"):
        wdf = df[df["window_id"]==wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

# Ensure datetimes
train_df["timestamp"] = pd.to_datetime(train_df["timestamp"])

# 1) Build HoD target frame on TRAIN
train_tgt = (train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
             .rename(columns={"meter_reading":"ytrue"}))
train_tgt = add_hoffset(train_tgt)
train_tgt["hod"] = train_tgt["timestamp"].dt.hour

trin = (train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy())
trin["hod"] = pd.to_datetime(trin["timestamp"]).dt.hour
hod_means = (trin.groupby(["window_id","hod"])["meter_reading"].mean()
             .rename("y_hod").reset_index())
wmean_tr = (trin.groupby("window_id")["meter_reading"].mean()
            .rename("wmean").reset_index())

feat = (train_tgt.merge(hod_means, on=["window_id","hod"], how="left")
                 .merge(wmean_tr, on="window_id", how="left"))
feat["y_hod"] = feat["y_hod"].fillna(feat["wmean"])

# 2) Build TRAIN TTM predictions on a sample of windows (fast and sufficient)
N_WINDOWS = 1200  # raise to ~2000 if you have time/GPU
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=42).tolist()

tsp_train = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180,
    forecast_length=60,
    scaling=True,
    scaler_type="standard",
    freq="h",
)
tsp_train.train(train_df.query("role=='input' and window_id in @sample_wids"))

ttm_train = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline_tr = TimeSeriesForecastingPipeline(ttm_train, explode_forecasts=True, feature_extractor=tsp_train, device=device)

pred_ttm = ttm_forecast_windows(train_df, sample_wids, pipeline_tr, steps=24)
feat = feat.merge(pred_ttm, on=["window_id","timestamp"], how="left")
feat["y_ttm"] = pd.to_numeric(feat["meter_reading_ttm"], errors="coerce")
feat["ytrue"] = pd.to_numeric(feat["ytrue"], errors="coerce")
feat["y_hod"] = pd.to_numeric(feat["y_hod"], errors="coerce")

# 3) Learn per (building_id, h_offset) alpha
alphas = np.linspace(0, 1, 21)
best = []
for (bid, hoff), g in feat.dropna(subset=["ytrue","y_hod"]).groupby(["building_id","h_offset"], sort=False):
    yh = g["y_hod"].to_numpy()
    yt = g["y_ttm"].fillna(g["y_hod"]).to_numpy()  # fallback to HoD when TTM missing
    y  = g["ytrue"].to_numpy()
    yh = np.clip(yh, 0, None); yt = np.clip(yt, 0, None)
    best_a, best_m = None, None
    for a in alphas:
        yhat = np.clip(a*yt + (1-a)*yh, 0, None)
        m = mean_squared_error(y, yhat)
        if best_m is None or m < best_m:
            best_a, best_m = float(a), m
    best.append((bid, hoff, best_a, best_m))

alpha_table = pd.DataFrame(best, columns=["building_id","h_offset","alpha","cv_mse"])
print("alpha_table:", alpha_table.shape)

# 4) Bias per (building_id, h_offset)
feat_bias = feat.dropna(subset=["ytrue","y_hod"]).merge(alpha_table, on=["building_id","h_offset"], how="left")
feat_bias["alpha"] = feat_bias["alpha"].fillna(0.0)
yhat_train = (feat_bias["alpha"] * feat_bias["y_ttm"].fillna(feat_bias["y_hod"])
              + (1 - feat_bias["alpha"]) * feat_bias["y_hod"]).clip(lower=0)
resid = feat_bias["ytrue"] - yhat_train
bias_table = (pd.DataFrame({"building_id": feat_bias["building_id"], "h_offset": feat_bias["h_offset"], "bias": resid})
              .groupby(["building_id","h_offset"])["bias"].mean().reset_index())
print("bias_table:", bias_table.shape)

# Save for future recovery
alpha_table.to_parquet(f"{DATA_DIR}/alpha_table.parquet", index=False)
bias_table.to_parquet(f"{DATA_DIR}/bias_table.parquet", index=False)
print("Saved alpha_table.parquet and bias_table.parquet to", DATA_DIR)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.04M [00:00<?, ?B/s]

Device set to use cpu
TTM windows: 100%|██████████| 1200/1200 [00:58<00:00, 20.48it/s]

alpha_table: (2184, 4)
bias_table: (2184, 3)
Saved alpha_table.parquet and bias_table.parquet to /content/drive/My Drive/IISC_data

In [ ]:
import pandas as pd, numpy as np

# Compute robust bounds if not already present
if "bounds" not in globals():
    tr = train_df.copy()
    tr["timestamp"] = pd.to_datetime(tr["timestamp"])
    tr["hod"] = tr["timestamp"].dt.hour
    g = tr.groupby(["building_id","hod"])["meter_reading"]
    q25 = g.quantile(0.25).rename("q25")
    q75 = g.quantile(0.75).rename("q75")
    iqr = (q75 - q25).rename("iqr")
    bounds = pd.concat([q25, q75, iqr], axis=1).reset_index()
    bounds["lo"] = (bounds["q25"] - 3.0*bounds["iqr"]).clip(lower=0)
    bounds["hi"] = (bounds["q75"] + 3.0*bounds["iqr"])
    bounds = bounds[["building_id","hod","lo","hi"]]

def add_hoffset(df):
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Test targets + features
test_targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]]
test_targets = add_hoffset(test_targets)
test_targets["hod"] = test_targets["timestamp"].dt.hour

# Blend (α + bias)
blend = (
    test_targets
      .merge(sub_hod[["row_id","meter_reading_hod"]], on="row_id", how="left")
      .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left")
      .merge(alpha_table, on=["building_id","h_offset"], how="left")
      .merge(bias_table,  on=["building_id","h_offset"], how="left")
)

blend["alpha"] = blend["alpha"].fillna(0.0)
blend["bias"]  = blend["bias"].fillna(0.0)

y_hod = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
y_ttm = pd.to_numeric(blend["meter_reading_ttm"], errors="coerce").fillna(y_hod)
y_pred = (blend["alpha"] * y_ttm + (1.0 - blend["alpha"]) * y_hod + blend["bias"]).clip(lower=0)
blend["meter_reading_raw"] = y_pred

# Smooth each 24-h vector per window (3-point kernel)
k = np.array([0.2, 0.6, 0.2])
def smooth24(v):
    return np.convolve(v, k, mode="same") if len(v)==24 else v

blend = blend.sort_values(["window_id","h_offset"]).copy()
sm_series = (
    blend.groupby("window_id", group_keys=False)["meter_reading_raw"]
         .apply(lambda s: pd.Series(smooth24(s.to_numpy()), index=s.index))
)
blend["meter_reading_sm"] = sm_series.values

# Clip to robust bounds per (building_id, hod)
blend = blend.merge(bounds, on=["building_id","hod"], how="left")
blend["meter_reading"] = (
    blend["meter_reading_sm"].clip(lower=blend["lo"].fillna(0), upper=blend["hi"].fillna(np.inf))
)

# Save
FINAL_PATH = f"{DATA_DIR}/submission_blend_tuned_bias_smooth_clip.csv"
blend[["row_id","meter_reading"]].sort_values("row_id").to_csv(FINAL_PATH, index=False)
print("Wrote:", FINAL_PATH, "| rows:", blend['row_id'].nunique())

Wrote: /content/drive/My Drive/IISC_data/submission_blend_tuned_bias_smooth_clip.csv | rows: 84600

In [ ]:
# Closed-form alpha on TRAIN: use TTM vs HoD where TTM preds exist; clip to [0,1], shrink by support,
# smooth across horizons per building, then compute a shrunk bias.

import pandas as pd, numpy as np, torch
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
from tqdm import tqdm
from sklearn.metrics import mean_squared_error

# --- helpers ---
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows"):
        wdf = df[df["window_id"]==wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

# Ensure datetime
train_df["timestamp"] = pd.to_datetime(train_df["timestamp"])

# 1) TRAIN targets + HoD baseline
train_tgt = (train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
             .rename(columns={"meter_reading":"ytrue"}))
train_tgt = add_hoffset(train_tgt)
train_tgt["hod"] = train_tgt["timestamp"].dt.hour

trin = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
trin["hod"] = pd.to_datetime(trin["timestamp"]).dt.hour
y_hod_tab = (trin.groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod").reset_index())
wmean_tr  = (trin.groupby("window_id")["meter_reading"].mean().rename("wmean").reset_index())

feat = (train_tgt.merge(y_hod_tab, on=["window_id","hod"], how="left")
                 .merge(wmean_tr,  on="window_id",      how="left"))
feat["y_hod"] = feat["y_hod"].fillna(feat["wmean"]).astype(float)
feat["ytrue"] = feat["ytrue"].astype(float)

# 2) TTM preds on a moderate sample of windows (enough for stable α)
N_WINDOWS = 1500   # ~1–3 minutes on CPU; adjust if needed
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=42).tolist()

tsp_train = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180,
    forecast_length=60,
    scaling=True,
    scaler_type="standard",
    freq="h",
)
tsp_train.train(train_df.query("role=='input' and window_id in @sample_wids"))

ttm_train = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline_tr = TimeSeriesForecastingPipeline(ttm_train, explode_forecasts=True, feature_extractor=tsp_train, device=device)

pred_ttm = ttm_forecast_windows(train_df, sample_wids, pipeline_tr, steps=24)
feat = feat.merge(pred_ttm, on=["window_id","timestamp"], how="left")
feat["y_ttm"] = pd.to_numeric(feat["meter_reading_ttm"], errors="coerce")

# 3) Closed-form α per (building_id, h_offset):
#    Let d = y_ttm - y_hod ; yhat = y_hod + a*d ; minimize MSE => a* = sum((y - y_hod)*d)/sum(d^2)
#    Guardrails: use only rows with y_ttm; clip a to [0,1]; shrink by support n: a = a_clipped * n/(n+L)
L_ALPHA = 48      # shrinkage strength for alpha (tune 24–96)
MIN_N   = 20      # minimum rows to trust alpha
eps     = 1e-9

rows = []
for (bid, hoff), g in feat.dropna(subset=["ytrue","y_hod","y_ttm"]).groupby(["building_id","h_offset"], sort=False):
    y  = g["ytrue"].to_numpy()
    yh = g["y_hod"].to_numpy()
    yt = g["y_ttm"].to_numpy()
    d  = yt - yh
    num = np.sum((y - yh) * d)
    den = np.sum(d * d) + eps
    a_raw = num / den
    a_clip = float(np.clip(a_raw, 0.0, 1.0))
    n = len(g)
    a_shr = a_clip * (n / (n + L_ALPHA)) if n >= MIN_N else 0.0  # fall back to HoD if too few samples
    rows.append((bid, hoff, n, a_raw, a_clip, a_shr))

alpha_table = pd.DataFrame(rows, columns=["building_id","h_offset","n","alpha_raw","alpha_clip","alpha"]).drop(columns=["alpha_raw","alpha_clip"])
print("alpha_table:", alpha_table.shape)

# 4) Smooth α across horizons per building (3-point moving average)
alpha_table = alpha_table.sort_values(["building_id","h_offset"]).copy()
alpha_table["alpha_sm"] = (
    alpha_table.groupby("building_id")["alpha"]
               .apply(lambda s: pd.Series(np.convolve(s.to_numpy(), np.array([0.2,0.6,0.2]), mode="same"), index=s.index))
               .values
)
alpha_table["alpha"] = alpha_table["alpha_sm"].clip(0,1)
alpha_table = alpha_table.drop(columns=["alpha_sm","n"])  # keep compact

# 5) Bias with shrinkage per (building_id, h_offset)
tmp = feat.merge(alpha_table, on=["building_id","h_offset"], how="left")
tmp["alpha"] = tmp["alpha"].fillna(0.0)
yhat = (tmp["alpha"] * tmp["y_ttm"].fillna(tmp["y_hod"]) + (1-tmp["alpha"]) * tmp["y_hod"]).clip(lower=0)
resid = tmp["ytrue"] - yhat
bias = pd.DataFrame({"building_id": tmp["building_id"], "h_offset": tmp["h_offset"], "resid": resid})
bias_table = bias.groupby(["building_id","h_offset"])["resid"].agg(["mean","count"]).reset_index()
L_BIAS = 50  # shrinkage for bias
bias_table["bias"] = bias_table["mean"] * (bias_table["count"] / (bias_table["count"] + L_BIAS))
bias_table = bias_table[["building_id","h_offset","bias"]]

# Save for reuse
alpha_table.to_parquet(f"{DATA_DIR}/alpha_table_cf.parquet", index=False)
bias_table.to_parquet(f"{DATA_DIR}/bias_table_cf.parquet", index=False)
print("Saved alpha_table_cf.parquet & bias_table_cf.parquet")

Device set to use cpu
TTM windows: 100%|██████████| 1500/1500 [01:11<00:00, 21.08it/s]

alpha_table: (2016, 4)
Saved alpha_table_cf.parquet & bias_table_cf.parquet

In [ ]:
import pandas as pd, numpy as np

# Load artifacts if needed
try:
    alpha_table
    bias_table
except NameError:
    alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
    bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

# Ensure HoD/TTM files are present
if "sub_hod" not in globals():
    sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"meter_reading_hod"})
if "sub_ttm" not in globals():
    sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"meter_reading_ttm"})

# Targets with horizon offsets
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

test_targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]]
test_targets = add_hoffset(test_targets)

# Blend
blend = (test_targets
         .merge(sub_hod[["row_id","meter_reading_hod"]], on="row_id", how="left")
         .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left")
         .merge(alpha_table, on=["building_id","h_offset"], how="left")
         .merge(bias_table,  on=["building_id","h_offset"], how="left"))

blend["alpha"] = blend["alpha"].fillna(0.0)
blend["bias"]  = blend["bias"].fillna(0.0)
y_hod = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
y_ttm = pd.to_numeric(blend["meter_reading_ttm"], errors="coerce").fillna(y_hod)

blend["meter_reading"] = (
    blend["alpha"] * y_ttm + (1.0 - blend["alpha"]) * y_hod + blend["bias"]
).clip(lower=0)

# Write submission (no additional smoothing/clipping)
OUT = f"{DATA_DIR}/submission_blend_cf.csv"
blend[["row_id","meter_reading"]].sort_values("row_id").to_csv(OUT, index=False)
print("Wrote:", OUT, "| rows:", blend["row_id"].nunique())

Wrote: /content/drive/My Drive/IISC_data/submission_blend_cf.csv | rows: 84600

In [ ]:
# Learn a small residual corrector: y_final = y_blend + beta * (lag24 - y_hod)
# Uses your existing alpha_table_cf + bias_table_cf (closed-form α + shrunk bias).

import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Helpers
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Make sure frames are in memory
if "train_df" not in globals():
    train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
if "alpha_table" not in globals():
    alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
if "bias_table" not in globals():
    bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

# --- Build TRAIN target rows with HoD, lag24, TTM, blend ---
trin = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
trin["hod"] = trin["timestamp"].dt.hour

# HoD mean within each window for each hour
y_hod_tab = (trin.groupby(["window_id","hod"])["meter_reading"]
             .mean().rename("y_hod").reset_index())

# TRAIN targets + horizon index
tgt = (train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
       .rename(columns={"meter_reading":"ytrue"}))
tgt = add_hoffset(tgt)
tgt["hod"] = tgt["timestamp"].dt.hour

feat = tgt.merge(y_hod_tab, on=["window_id","hod"], how="left")
# fallback to window mean if some hod missing (rare)
wmean_tr = trin.groupby("window_id")["meter_reading"].mean().rename("wmean").reset_index()
feat = feat.merge(wmean_tr, on="window_id", how="left")
feat["y_hod"] = feat["y_hod"].fillna(feat["wmean"])

# lag-24 from inputs
idx_in = trin.set_index(["window_id","timestamp"])["meter_reading"].rename("lag24_val")
lag24 = feat[["window_id","timestamp"]].copy()
lag24["timestamp_lag"] = lag24["timestamp"] - pd.Timedelta(hours=24)
lag24 = lag24.join(idx_in, on=["window_id","timestamp_lag"])
feat = feat.merge(lag24[["window_id","timestamp","lag24_val"]], on=["window_id","timestamp"], how="left")

# bring in TTM (use the same trick: closed-form α blend uses TTM only to set α;
# we don't need to recompute TTM here—just rebuild y_blend from α+bias and HoD/TTM from TRAIN)
# For stability, build a minimal TTM on a sample exactly as in your α step:
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
import torch
from tqdm import tqdm

def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows (β tune)"):
        wdf = df[df["window_id"]==wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

# Sample some windows for TTM to keep it fast (same spirit as α)
N_WINDOWS = 1500
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=42).tolist()

tsp_tr = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180,
    forecast_length=60,
    scaling=True,
    scaler_type="standard",
    freq="h",
)
tsp_tr.train(train_df.query("role=='input' and window_id in @sample_wids"))

ttm_tr = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipe_tr = TimeSeriesForecastingPipeline(ttm_tr, explode_forecasts=True, feature_extractor=tsp_tr, device=device)

pred_ttm = ttm_forecast_windows(train_df, sample_wids, pipe_tr, steps=24)
feat = feat.merge(pred_ttm, on=["window_id","timestamp"], how="left").rename(columns={"meter_reading_ttm":"y_ttm"})

# Compute blend on TRAIN: y_blend = α*y_ttm + (1-α)*y_hod + bias
tmp = feat.merge(alpha_table, on=["building_id","h_offset"], how="left").merge(bias_table, on=["building_id","h_offset"], how="left")
tmp["alpha"] = tmp["alpha"].fillna(0.0); tmp["bias"] = tmp["bias"].fillna(0.0)
tmp["y_ttm"] = pd.to_numeric(tmp["y_ttm"], errors="coerce").fillna(tmp["y_hod"])
tmp["y_blend"] = (tmp["alpha"]*tmp["y_ttm"] + (1-tmp["alpha"])*tmp["y_hod"] + tmp["bias"]).clip(lower=0)

# Residual r, feature z = (lag24 - y_hod)
tmp["z"] = pd.to_numeric(tmp["lag24_val"], errors="coerce").fillna(tmp["y_hod"]) - tmp["y_hod"]
tmp["r"] = pd.to_numeric(tmp["ytrue"], errors="coerce") - tmp["y_blend"]

# Closed-form β per (building_id, h_offset), with shrinkage + smoothing
L_BETA = 64   # shrinkage strength (try 48–96)
MIN_N  = 20
eps    = 1e-9

rows = []
for (bid, hoff), g in tmp.dropna(subset=["r","z"]).groupby(["building_id","h_offset"], sort=False):
    z = g["z"].to_numpy()
    r = g["r"].to_numpy()
    num = np.sum(r*z); den = np.sum(z*z) + eps
    b_raw = num/den
    n = len(g)
    # clip β to avoid wild corrections; shrink toward 0
    b_clip = float(np.clip(b_raw, -0.5, 0.5))
    b_shr  = b_clip * (n / (n + L_BETA)) if n >= MIN_N else 0.0
    rows.append((bid, hoff, n, b_shr))

beta_table = pd.DataFrame(rows, columns=["building_id","h_offset","n","beta"])
beta_table = beta_table.sort_values(["building_id","h_offset"]).copy()

# Smooth β across horizons per building (gentle 3-point)
kernel = np.array([0.2, 0.6, 0.2])
beta_table["beta_sm"] = (
    beta_table.groupby("building_id")["beta"]
              .apply(lambda s: pd.Series(np.convolve(s.to_numpy(), kernel, mode="same"), index=s.index))
              .values
)
beta_table["beta"] = beta_table["beta_sm"]
beta_table = beta_table.drop(columns=["beta_sm","n"])

beta_table.to_parquet(f"{DATA_DIR}/beta_table_cf.parquet", index=False)
print("beta_table:", beta_table.shape, "saved to beta_table_cf.parquet")

Device set to use cpu
TTM windows (β tune): 100%|██████████| 1500/1500 [01:12<00:00, 20.78it/s]

beta_table: (2184, 3) saved to beta_table_cf.parquet

In [ ]:
# y_final = (α*y_ttm + (1-α)*y_hod + bias) + beta * (lag24 - y_hod)
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load artifacts if needed
if "alpha_table" not in globals():
    alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
if "bias_table" not in globals():
    bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")
if "beta_table" not in globals():
    beta_table  = pd.read_parquet(f"{DATA_DIR}/beta_table_cf.parquet")

# Ensure HoD/TTM preds are available
if "sub_hod" not in globals():
    sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"meter_reading_hod"})
if "sub_ttm" not in globals():
    sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"meter_reading_ttm"})
if "test_df" not in globals():
    test_df = pd.read_csv(f"{DATA_DIR}/test.csv", parse_dates=["timestamp"])

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Build TEST features
test_inputs = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
test_inputs["hod"] = test_inputs["timestamp"].dt.hour

# y_hod for TEST targets
hod_tab = (test_inputs.groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod").reset_index())

targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy()
targets = add_hoffset(targets); targets["hod"] = targets["timestamp"].dt.hour
feat_te = targets.merge(hod_tab, on=["window_id","hod"], how="left")

# lag-24
idx_in_test = test_inputs.set_index(["window_id","timestamp"])["meter_reading"].rename("lag24_val")
lag24_te = feat_te[["window_id","timestamp"]].copy()
lag24_te["timestamp_lag"] = lag24_te["timestamp"] - pd.Timedelta(hours=24)
lag24_te = lag24_te.join(idx_in_test, on=["window_id","timestamp_lag"])
feat_te = feat_te.merge(lag24_te[["window_id","timestamp","lag24_val"]], on=["window_id","timestamp"], how="left")
feat_te["y_hod"] = feat_te["y_hod"].fillna(feat_te.groupby("window_id")["y_hod"].transform("mean"))

# Merge HoD & TTM predictions (row_id-aligned)
feat_te = (feat_te
           .merge(sub_hod[["row_id","meter_reading_hod"]], on="row_id", how="left")
           .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left"))

y_hod_pred = pd.to_numeric(feat_te["meter_reading_hod"], errors="coerce")
y_ttm_pred = pd.to_numeric(feat_te["meter_reading_ttm"], errors="coerce").fillna(y_hod_pred)

# α + bias
feat_te = (feat_te
           .merge(alpha_table, on=["building_id","h_offset"], how="left")
           .merge(bias_table,  on=["building_id","h_offset"], how="left")
           .merge(beta_table,  on=["building_id","h_offset"], how="left"))

feat_te["alpha"] = feat_te["alpha"].fillna(0.0)
feat_te["bias"]  = feat_te["bias"].fillna(0.0)
feat_te["beta"]  = feat_te["beta"].fillna(0.0)

y_blend = (feat_te["alpha"] * y_ttm_pred + (1.0 - feat_te["alpha"]) * y_hod_pred + feat_te["bias"]).clip(lower=0)

# residual feature z = (lag24 - y_hod (from inputs))
z = pd.to_numeric(feat_te["lag24_val"], errors="coerce").fillna(feat_te["y_hod"]) - feat_te["y_hod"]

# Gentle guard: cap correction to ±20% of y_blend to avoid overshoots on rare spikes
corr = feat_te["beta"] * z
cap = 0.20 * y_blend
corr = corr.clip(lower=-cap, upper=cap)

y_final = (y_blend + corr).clip(lower=0)

OUT = f"{DATA_DIR}/submission_blend_cf_lag24.csv"
pd.DataFrame({"row_id": feat_te["row_id"], "meter_reading": y_final}).sort_values("row_id").to_csv(OUT, index=False)
print("Wrote:", OUT, "| rows:", feat_te['row_id'].nunique())

Wrote: /content/drive/My Drive/IISC_data/submission_blend_cf_lag24.csv | rows: 84600

In [ ]:
# Patch: robust window-level features + finish γ and λ, then save tables.

import numpy as np
import pandas as pd

# --- Robust window-level features from TRAIN inputs (trin) ---
w_inputs = (
    trin.sort_values(["window_id","timestamp"])
        .groupby("window_id")
        .agg(
            head24_mean=("meter_reading", lambda s: s.head(24).mean()),
            last24_mean=("meter_reading", lambda s: s.tail(24).mean()),
            x_last=("meter_reading", "last"),
        )
        .reset_index()
)
w_inputs["s_win"] = w_inputs["last24_mean"] / w_inputs["head24_mean"].clip(lower=1e-6)
w_inputs = w_inputs[["window_id","s_win","x_last"]]

# First-hour prediction y0 per window (from y_blend where h_offset==0)
y0 = (tmp.loc[tmp["h_offset"]==0, ["window_id","y_blend"]]
        .rename(columns={"y_blend":"y0"}))

win_feat = w_inputs.merge(y0, on="window_id", how="left")
win_feat["delta_win"] = (win_feat["x_last"] - win_feat["y0"]).fillna(0.0)

# Attach features to all target rows
tmp = (tmp.drop(columns=[c for c in ["s_win","delta_win"] if c in tmp.columns])
          .merge(win_feat[["window_id","s_win","delta_win"]], on="window_id", how="left"))
tmp["s_win"] = tmp["s_win"].fillna(1.0)
tmp["delta_win"] = tmp["delta_win"].fillna(0.0)

# Residual and design features
tmp["r"] = tmp["ytrue"] - tmp["y_blend"]
tmp["w_h"] = np.exp(-tmp["h_offset"] / 12.0)  # decay across horizons
tmp["phi"] = tmp["delta_win"] * tmp["w_h"]
tmp["psi"] = (tmp["s_win"] - 1.0) * tmp["y_blend"]

# --- Closed-form per-building γ (offset) and λ (scale) with shrinkage ---
L_GAMMA = 100
L_LAMBDA = 100
MIN_N = 50
eps = 1e-9

rows_g, rows_l = [], []
for bid, g in tmp.dropna(subset=["r","phi","psi"]).groupby("building_id", sort=False):
    # γ (offset)
    num_g = float(np.sum(g["r"] * g["phi"]))
    den_g = float(np.sum(g["phi"] * g["phi"])) + eps
    gamma_raw = num_g / den_g
    n_g = len(g)
    gamma_clip = float(np.clip(gamma_raw, -0.5, 0.5))
    gamma = gamma_clip * (n_g / (n_g + L_GAMMA)) if n_g >= MIN_N else 0.0
    rows_g.append((bid, gamma, n_g))

    # λ (scale): regress r / y_blend on (s_win - 1)
    yb = np.clip(g["y_blend"].to_numpy(), 1e-6, None)
    rr = (g["r"].to_numpy() / yb)
    ss = (g["s_win"].to_numpy() - 1.0)
    num_l = float(np.sum(rr * ss))
    den_l = float(np.sum(ss * ss)) + eps
    lam_raw = num_l / den_l
    n_l = len(g)
    lam_clip = float(np.clip(lam_raw, -0.5, 0.5))
    lam = lam_clip * (n_l / (n_l + L_LAMBDA)) if n_l >= MIN_N else 0.0
    rows_l.append((bid, lam, n_l))

gamma_table = pd.DataFrame(rows_g, columns=["building_id","gamma","n"])
lambda_table = pd.DataFrame(rows_l, columns=["building_id","lambda","n"])

gamma_table.to_parquet(f"{DATA_DIR}/gamma_table.parquet", index=False)
lambda_table.to_parquet(f"{DATA_DIR}/lambda_table.parquet", index=False)
print("γ learned for", len(gamma_table), "buildings; λ learned for", len(lambda_table), "buildings")

γ learned for 91 buildings; λ learned for 91 buildings

In [ ]:
# Robust TEST window features + apply γ/λ + save submission_calibrated.csv

import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load artifacts (if not in memory)
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")
gamma_table = pd.read_parquet(f"{DATA_DIR}/gamma_table.parquet")
lambda_table= pd.read_parquet(f"{DATA_DIR}/lambda_table.parquet")
sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"meter_reading_hod"})
sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"meter_reading_ttm"})
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", parse_dates=["timestamp"])

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# === Base blend on TEST (α + bias) ===
targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy()
targets = add_hoffset(targets)

blend = (targets
         .merge(sub_hod[["row_id","meter_reading_hod"]], on="row_id", how="left")
         .merge(sub_ttm[["row_id","meter_reading_ttm"]], on="row_id", how="left")
         .merge(alpha_table, on=["building_id","h_offset"], how="left")
         .merge(bias_table,  on=["building_id","h_offset"], how="left"))

blend["alpha"] = blend["alpha"].fillna(0.0)
blend["bias"]  = blend["bias"].fillna(0.0)
y_hod = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
y_ttm = pd.to_numeric(blend["meter_reading_ttm"], errors="coerce").fillna(y_hod)
blend["y_blend"] = (blend["alpha"] * y_ttm + (1.0 - blend["alpha"]) * y_hod + blend["bias"]).clip(lower=0)

# === Robust TEST window features (no KeyError) ===
test_inp = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
test_inp = test_inp.sort_values(["window_id","timestamp"])

w_inputs_te = (
    test_inp.groupby("window_id")
            .agg(
                head24_mean=("meter_reading", lambda s: s.head(24).mean()),
                last24_mean=("meter_reading", lambda s: s.tail(24).mean()),
                x_last=("meter_reading", "last"),
            )
            .reset_index()
)
w_inputs_te["s_win"] = w_inputs_te["last24_mean"] / w_inputs_te["head24_mean"].clip(lower=1e-6)
w_inputs_te = w_inputs_te[["window_id","s_win","x_last"]]

# First-hour prediction per window from y_blend
y0 = (blend.loc[blend["h_offset"]==0, ["window_id","y_blend"]]
            .rename(columns={"y_blend":"y0"}))

win_feat = w_inputs_te.merge(y0, on="window_id", how="left")
win_feat["delta_win"] = (win_feat["x_last"] - win_feat["y0"]).fillna(0.0)

# Attach γ/λ and apply corrections
blend = (blend
         .merge(win_feat[["window_id","s_win","delta_win"]], on="window_id", how="left")
         .merge(gamma_table, on="building_id", how="left")
         .merge(lambda_table, on="building_id", how="left"))

blend["s_win"]     = blend["s_win"].fillna(1.0)
blend["delta_win"] = blend["delta_win"].fillna(0.0)
blend["gamma"]     = blend["gamma"].fillna(0.0)
blend["lambda"]    = blend["lambda"].fillna(0.0)

# Scale correction (cap to avoid overshoot)
scale_factor = (1.0 + blend["lambda"] * (blend["s_win"] - 1.0)).clip(lower=0.85, upper=1.20)
# Offset correction decays with horizon
w_h = np.exp(-blend["h_offset"] / 12.0)
offset_term = blend["gamma"] * blend["delta_win"] * w_h

y_cal = (blend["y_blend"] * scale_factor + offset_term).clip(lower=0)

OUT = f"{DATA_DIR}/submission_calibrated.csv"
pd.DataFrame({"row_id": blend["row_id"], "meter_reading": y_cal}).sort_values("row_id").to_csv(OUT, index=False)
print("Wrote:", OUT, "| rows:", blend['row_id'].nunique())

Wrote: /content/drive/My Drive/IISC_data/submission_calibrated.csv | rows: 84600

In [ ]:
# Learn per-(building, horizon) betas for z24=(lag24 - y_hod) and z168=(lag168 - y_hod)
# Baseline = closed-form α + shrunk bias blend (y_blend). We DO NOT include γ/λ here.

import pandas as pd, numpy as np, torch
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
from tqdm import tqdm

DATA_DIR = "/content/drive/My Drive/IISC_data"

# ---------- helpers ----------
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows (beta tune)"):
        wdf = df[df["window_id"]==wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

# ---------- load data/artifacts ----------
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

# TRAIN targets + HoD
trin = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
trin["hod"] = trin["timestamp"].dt.hour
y_hod_tab = (trin.groupby(["window_id","hod"])["meter_reading"].mean()
             .rename("y_hod").reset_index())
wmean_tr = (trin.groupby("window_id")["meter_reading"].mean()
            .rename("wmean").reset_index())

tgt = (train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
       .rename(columns={"meter_reading":"ytrue"}))
tgt = add_hoffset(tgt); tgt["hod"] = tgt["timestamp"].dt.hour

feat = (tgt.merge(y_hod_tab, on=["window_id","hod"], how="left")
           .merge(wmean_tr,  on="window_id",      how="left"))
feat["y_hod"] = feat["y_hod"].fillna(feat["wmean"]).astype(float)
feat["ytrue"] = feat["ytrue"].astype(float)

# Minimal TTM on a moderate TRAIN sample to form y_blend
N_WINDOWS = 1500
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=42).tolist()

tsp_tr = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180, forecast_length=60,
    scaling=True, scaler_type="standard",
    freq="h",
)
tsp_tr.train(train_df.query("role=='input' and window_id in @sample_wids"))

ttm_tr = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipe_tr = TimeSeriesForecastingPipeline(ttm_tr, explode_forecasts=True, feature_extractor=tsp_tr, device=device)

pred_ttm = ttm_forecast_windows(train_df, sample_wids, pipe_tr, steps=24)  # ['window_id','timestamp','meter_reading_ttm']
feat = feat.merge(pred_ttm, on=["window_id","timestamp"], how="left").rename(columns={"meter_reading_ttm":"y_ttm"})

# y_blend (alpha + bias), no γ/λ or previous residuals
tmp = feat.merge(alpha_table, on=["building_id","h_offset"], how="left").merge(bias_table, on=["building_id","h_offset"], how="left")
tmp["alpha"] = tmp["alpha"].fillna(0.0); tmp["bias"] = tmp["bias"].fillna(0.0)
tmp["y_ttm"] = pd.to_numeric(tmp["y_ttm"], errors="coerce").fillna(tmp["y_hod"])
tmp["y_blend"] = (tmp["alpha"]*tmp["y_ttm"] + (1-tmp["alpha"])*tmp["y_hod"] + tmp["bias"]).clip(lower=0)

# Build z24 and z168 from TRAIN inputs
idx_in = trin.set_index(["window_id","timestamp"])["meter_reading"].rename("mr_in")

lag24 = tmp[["window_id","timestamp"]].copy()
lag24["timestamp_lag"] = lag24["timestamp"] - pd.Timedelta(hours=24)
lag24 = lag24.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag24_val"})

lag168 = tmp[["window_id","timestamp"]].copy()
lag168["timestamp_lag"] = lag168["timestamp"] - pd.Timedelta(hours=168)
lag168 = lag168.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag168_val"})

tmp = (tmp.merge(lag24[["window_id","timestamp","lag24_val"]], on=["window_id","timestamp"], how="left")
          .merge(lag168[["window_id","timestamp","lag168_val"]], on=["window_id","timestamp"], how="left"))

tmp["z24"]  = pd.to_numeric(tmp["lag24_val"],  errors="coerce").fillna(tmp["y_hod"]) - tmp["y_hod"]
tmp["z168"] = pd.to_numeric(tmp["lag168_val"], errors="coerce").fillna(tmp["y_hod"]) - tmp["y_hod"]
tmp["r"]    = tmp["ytrue"] - tmp["y_blend"]

# Closed-form betas with shrinkage + smoothing
L_BETA24  = 64
L_BETA168 = 64
MIN_N = 20
eps = 1e-9

def fit_beta(group, z_col, L):
    z = group[z_col].to_numpy()
    r = group["r"].to_numpy()
    num = float((r*z).sum())
    den = float((z*z).sum()) + eps
    b_raw = num/den
    n = len(group)
    b_clip = float(np.clip(b_raw, -0.5, 0.5))
    return b_clip * (n / (n + L)) if n >= MIN_N else 0.0, n

rows24, rows168 = [], []
for (bid, hoff), g in tmp.dropna(subset=["r","z24"]).groupby(["building_id","h_offset"], sort=False):
    b, n = fit_beta(g, "z24", L_BETA24)
    rows24.append((bid, hoff, b, n))
for (bid, hoff), g in tmp.dropna(subset=["r","z168"]).groupby(["building_id","h_offset"], sort=False):
    b, n = fit_beta(g, "z168", L_BETA168)
    rows168.append((bid, hoff, b, n))

beta24 = pd.DataFrame(rows24,  columns=["building_id","h_offset","beta24","n"])
beta168= pd.DataFrame(rows168, columns=["building_id","h_offset","beta168","n"])

# Smooth across horizons (3-pt kernel)
ker = np.array([0.2, 0.6, 0.2])
for df, col in [(beta24,"beta24"), (beta168,"beta168")]:
    df.sort_values(["building_id","h_offset"], inplace=True)
    df[col] = (df.groupby("building_id")[col]
                 .apply(lambda s: pd.Series(np.convolve(s.to_numpy(), ker, mode="same"), index=s.index))
                 .values)

beta24 = beta24[["building_id","h_offset","beta24"]]
beta168= beta168[["building_id","h_offset","beta168"]]

beta24.to_parquet(f"{DATA_DIR}/beta24_table.parquet", index=False)
beta168.to_parquet(f"{DATA_DIR}/beta168_table.parquet", index=False)
print("beta24:", beta24.shape, " beta168:", beta168.shape, " (saved)")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.04M [00:00<?, ?B/s]

Device set to use cpu
TTM windows (beta tune): 100%|██████████| 1500/1500 [01:26<00:00, 17.39it/s]

beta24: (2184, 3)  beta168: (2184, 3)  (saved)

In [ ]:
# Colab + basics
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/My Drive/IISC_data

!pip -q install "granite-tsfm[notebooks]==0.3.1" --no-input

import os, random, numpy as np, pandas as pd, torch
pd.options.mode.chained_assignment = None
DATA_DIR = "/content/drive/My Drive/IISC_data"
SEED = 42
random.seed(SEED); np.random.seed(SEED)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/IISC_data

In [ ]:
import pandas as pd

train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])
meta_df  = pd.read_csv(f"{DATA_DIR}/metadata.csv")
sample_submission_df = pd.read_csv(f"{DATA_DIR}/sample_submission.csv")

print(train_df.shape, test_df.shape, meta_df.shape, sample_submission_df.shape)

(2582976, 5) (676800, 6) (94, 17) (84600, 2)

In [ ]:
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline
from tqdm import tqdm

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

def pad_to_180(win_df: pd.DataFrame, ts_col="timestamp") -> pd.DataFrame:
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

def ttm_forecast_windows(df: pd.DataFrame, window_ids, pipeline, steps=24):
    """Return DataFrame with ['window_id','timestamp','meter_reading_ttm'] for target timestamps."""
    preds = []
    for wi in tqdm(window_ids, desc="TTM windows"):
        wdf = df[df["window_id"] == wi]
        inp = wdf[wdf["role"]=="input"].copy()
        tar = wdf[wdf["role"]=="target"][["timestamp"]].copy()
        pred = pipeline(pad_to_180(inp)).iloc[:steps][["meter_reading"]].reset_index(drop=True)
        tar = tar.reset_index(drop=True)
        tar["meter_reading_ttm"] = pred["meter_reading"].astype(float)
        tar["window_id"] = wi
        preds.append(tar)
    return pd.concat(preds, ignore_index=True)

In [ ]:
# Hour-of-day mean from each window’s 168h inputs
inp_te = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
inp_te["hod"] = inp_te["timestamp"].dt.hour
hod_tab = (inp_te.groupby(["window_id","hod"])["meter_reading"]
           .mean().rename("y_hod").reset_index())
wmean_te = (inp_te.groupby("window_id")["meter_reading"]
            .mean().rename("wmean").reset_index())

tgt_te = test_df.query("role=='target'")[["row_id","window_id","timestamp"]].copy()
tgt_te["hod"] = tgt_te["timestamp"].dt.hour

sub_hod = (tgt_te.merge(hod_tab, on=["window_id","hod"], how="left")
                 .merge(wmean_te, on="window_id", how="left"))
sub_hod["meter_reading"] = sub_hod["y_hod"].fillna(sub_hod["wmean"]).clip(lower=0)
sub_hod = sub_hod[["row_id","meter_reading"]].sort_values("row_id").reset_index(drop=True)
sub_hod.to_csv(f"{DATA_DIR}/submission_hod.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_hod.csv", sub_hod.shape)

Wrote: /content/drive/My Drive/IISC_data/submission_hod.csv (84600, 2)

In [ ]:
# Build preprocessor on TEST inputs (scalers only; no label leakage)
tsp_te = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180,
    forecast_length=60,
    scaling=True, scaler_type="standard", freq="h",
)
tsp_te.train(test_df.query("role=='input'"))

ttm = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline_te = TimeSeriesForecastingPipeline(ttm, explode_forecasts=True, feature_extractor=tsp_te, device=device)

win_ids = test_df["window_id"].drop_duplicates().tolist()
pred_ttm_te = ttm_forecast_windows(test_df, win_ids, pipeline_te, steps=24)

# Row-aligned submission
tgt_rows = test_df.query("role=='target'")[["row_id","window_id","timestamp"]]
sub_ttm = (tgt_rows.merge(pred_ttm_te, on=["window_id","timestamp"], how="left")
                    .rename(columns={"meter_reading_ttm":"meter_reading"}))[["row_id","meter_reading"]]
sub_ttm.to_csv(f"{DATA_DIR}/submission_ttm.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_ttm.csv", sub_ttm.shape)

Device set to use cpu
TTM windows: 100%|██████████| 3525/3525 [03:05<00:00, 19.05it/s]

Wrote: /content/drive/My Drive/IISC_data/submission_ttm.csv (84600, 2)

In [ ]:
# TRAIN: HoD, TTM (sample), closed-form alpha with shrink + smoothing; shrunk bias
trin = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
trin["hod"] = trin["timestamp"].dt.hour
yhod_tr = (trin.groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod").reset_index())
wmean_tr = (trin.groupby("window_id")["meter_reading"].mean().rename("wmean").reset_index())

tgt_tr = (train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
          .rename(columns={"meter_reading":"ytrue"}))
tgt_tr = add_hoffset(tgt_tr); tgt_tr["hod"] = tgt_tr["timestamp"].dt.hour

feat = (tgt_tr.merge(yhod_tr, on=["window_id","hod"], how="left")
              .merge(wmean_tr, on="window_id", how="left"))
feat["y_hod"] = feat["y_hod"].fillna(feat["wmean"]).astype(float)
feat["ytrue"] = feat["ytrue"].astype(float)

# Sample windows for TTM speed (adjust N_WINDOWS if needed)
N_WINDOWS = 1500
sample_wids = train_df["window_id"].drop_duplicates().sample(N_WINDOWS, random_state=SEED).tolist()

tsp_tr = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180, forecast_length=60,
    scaling=True, scaler_type="standard", freq="h",
)
tsp_tr.train(train_df.query("role=='input' and window_id in @sample_wids"))

ttm_tr = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()

pipeline_tr = TimeSeriesForecastingPipeline(ttm_tr, explode_forecasts=True, feature_extractor=tsp_tr, device=device)
pred_ttm_tr = ttm_forecast_windows(train_df, sample_wids, pipeline_tr, steps=24)
feat = feat.merge(pred_ttm_tr, on=["window_id","timestamp"], how="left").rename(columns={"meter_reading_ttm":"y_ttm"})
feat["y_ttm"] = pd.to_numeric(feat["y_ttm"], errors="coerce")

# Closed-form alpha: a* = sum((y - yh)*d)/sum(d^2); clip [0,1]; shrink; smooth
L_ALPHA, MIN_N, eps = 64, 20, 1e-9
rows = []
for (bid, hoff), g in feat.dropna(subset=["ytrue","y_hod","y_ttm"]).groupby(["building_id","h_offset"], sort=False):
    y, yh, yt = g["ytrue"].to_numpy(), g["y_hod"].to_numpy(), g["y_ttm"].to_numpy()
    d = yt - yh
    a_raw = float(((y - yh)*d).sum() / (d*d).sum() if (d*d).sum()>0 else 0.0)
    a_clip = float(np.clip(a_raw, 0.0, 1.0))
    n = len(g)
    a_shr = a_clip * (n/(n+L_ALPHA)) if n>=MIN_N else 0.0
    rows.append((bid, hoff, a_shr, n))
alpha_table = pd.DataFrame(rows, columns=["building_id","h_offset","alpha","n"]).drop(columns=["n"])

# Smooth alpha over horizons (3-pt kernel)
ker = np.array([0.2, 0.6, 0.2])
alpha_table = alpha_table.sort_values(["building_id","h_offset"]).copy()
alpha_table["alpha"] = (alpha_table.groupby("building_id")["alpha"]
                                      .apply(lambda s: pd.Series(np.convolve(s.to_numpy(), ker, mode="same"), index=s.index))
                                      .values).clip(0,1)

# Bias (shrunk mean residual)
tmp = feat.merge(alpha_table, on=["building_id","h_offset"], how="left")
tmp["alpha"] = tmp["alpha"].fillna(0.0)
yhat = (tmp["alpha"] * tmp["y_ttm"].fillna(tmp["y_hod"]) + (1-tmp["alpha"]) * tmp["y_hod"]).clip(lower=0)
resid = tmp["ytrue"] - yhat
bias_table = (pd.DataFrame({"building_id": tmp["building_id"], "h_offset": tmp["h_offset"], "resid": resid})
              .groupby(["building_id","h_offset"])["resid"]
              .agg(["mean","count"]).reset_index())
L_BIAS = 50
bias_table["bias"] = bias_table["mean"] * (bias_table["count"]/(bias_table["count"]+L_BIAS))
bias_table = bias_table[["building_id","h_offset","bias"]]

alpha_table.to_parquet(f"{DATA_DIR}/alpha_table_cf.parquet", index=False)
bias_table.to_parquet(f"{DATA_DIR}/bias_table_cf.parquet", index=False)
print("Saved:", "alpha_table_cf.parquet", "bias_table_cf.parquet")

Device set to use cpu
TTM windows: 100%|██████████| 1500/1500 [01:23<00:00, 17.95it/s]

Saved: alpha_table_cf.parquet bias_table_cf.parquet

In [ ]:
# Reuse 'feat' (has y_hod, ytrue, y_ttm) to build y_blend, then fit betas on z24/z168
tmp = feat.merge(alpha_table, on=["building_id","h_offset"], how="left").merge(bias_table, on=["building_id","h_offset"], how="left")
tmp["alpha"] = tmp["alpha"].fillna(0.0); tmp["bias"] = tmp["bias"].fillna(0.0)
tmp["y_ttm"] = pd.to_numeric(tmp["y_ttm"], errors="coerce").fillna(tmp["y_hod"])
tmp["y_blend"] = (tmp["alpha"]*tmp["y_ttm"] + (1-tmp["alpha"])*tmp["y_hod"] + tmp["bias"]).clip(lower=0)

# lag24 / lag168 from TRAIN inputs
idx_in = trin.set_index(["window_id","timestamp"])["meter_reading"].rename("mr_in")
lag24 = tmp[["window_id","timestamp"]].copy()
lag24["timestamp_lag"] = lag24["timestamp"] - pd.Timedelta(hours=24)
lag24 = lag24.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag24_val"})

lag168 = tmp[["window_id","timestamp"]].copy()
lag168["timestamp_lag"] = lag168["timestamp"] - pd.Timedelta(hours=168)
lag168 = lag168.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag168_val"})

tmp = (tmp.merge(lag24[["window_id","timestamp","lag24_val"]], on=["window_id","timestamp"], how="left")
         .merge(lag168[["window_id","timestamp","lag168_val"]], on=["window_id","timestamp"], how="left"))

# HoD baseline from inputs for residuals
yhod_inp = (trin.groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod_inp").reset_index())
tmp = tmp.merge(yhod_inp, on=["window_id","hod"], how="left").merge(wmean_tr.rename(columns={"wmean":"wmean_inp"}), on="window_id", how="left")
tmp["y_hod_inp"] = tmp["y_hod_inp"].fillna(tmp["wmean_inp"])

tmp["z24"]  = pd.to_numeric(tmp["lag24_val"],  errors="coerce").fillna(tmp["y_hod_inp"]) - tmp["y_hod_inp"]
tmp["z168"] = pd.to_numeric(tmp["lag168_val"], errors="coerce").fillna(tmp["y_hod_inp"]) - tmp["y_hod_inp"]
tmp["r"]    = tmp["ytrue"] - tmp["y_blend"]

L_BETA24, L_BETA168, MIN_N, eps = 64, 64, 20, 1e-9
def fit_beta(group, zcol, L):
    z = group[zcol].to_numpy(); r = group["r"].to_numpy()
    den = float((z*z).sum()) + eps
    b_raw = float((r*z).sum()/den)
    n = len(group)
    b_clip = float(np.clip(b_raw, -0.5, 0.5))
    return (b_clip * (n/(n+L))) if n>=MIN_N else 0.0

rows24, rows168 = [], []
for (bid, hoff), g in tmp.dropna(subset=["r","z24"]).groupby(["building_id","h_offset"], sort=False):
    rows24.append((bid, hoff, fit_beta(g,"z24", L_BETA24)))
for (bid, hoff), g in tmp.dropna(subset=["r","z168"]).groupby(["building_id","h_offset"], sort=False):
    rows168.append((bid, hoff, fit_beta(g,"z168", L_BETA168)))

beta24  = pd.DataFrame(rows24,  columns=["building_id","h_offset","beta24"])
beta168 = pd.DataFrame(rows168, columns=["building_id","h_offset","beta168"])

# Smooth across horizons
ker = np.array([0.2, 0.6, 0.2])
for df, col in [(beta24,"beta24"), (beta168,"beta168")]:
    df.sort_values(["building_id","h_offset"], inplace=True)
    df[col] = (df.groupby("building_id")[col]
                 .apply(lambda s: pd.Series(np.convolve(s.to_numpy(), ker, mode="same"), index=s.index))
                 .values)

beta24.to_parquet(f"{DATA_DIR}/beta24_table.parquet", index=False)
beta168.to_parquet(f"{DATA_DIR}/beta168_table.parquet", index=False)
print("Saved: beta24_table.parquet, beta168_table.parquet")

Saved: beta24_table.parquet, beta168_table.parquet

In [ ]:
# Build window features from TRAIN inputs
win_inputs = (trin.sort_values(["window_id","timestamp"])
                .groupby("window_id")
                .agg(
                    head24_mean=("meter_reading", lambda s: s.head(24).mean()),
                    last24_mean=("meter_reading", lambda s: s.tail(24).mean()),
                    x_last=("meter_reading", "last"),
                ).reset_index())
win_inputs["s_win"] = win_inputs["last24_mean"] / win_inputs["head24_mean"].clip(lower=1e-6)

# y0 (first-horizon of y_blend) per window
tmp2 = tmp.copy()
y0 = (tmp2[tmp2["h_offset"]==0][["window_id","y_blend"]].rename(columns={"y_blend":"y0"}))
win_feat_tr = win_inputs.merge(y0, on="window_id", how="left")
win_feat_tr["delta_win"] = (win_feat_tr["x_last"] - win_feat_tr["y0"]).fillna(0.0)

# Attach features back to tmp2
tmp2 = tmp2.merge(win_feat_tr[["window_id","s_win","delta_win"]], on="window_id", how="left")
tmp2["r"] = tmp2["ytrue"] - tmp2["y_blend"]

# γ and λ per building (closed-form with shrinkage)
L_GAMMA, L_LAMBDA, MIN_N, eps = 100, 100, 50, 1e-9
rows_g, rows_l = [], []
for bid, g in tmp2.dropna(subset=["r","s_win","delta_win","y_blend"]).groupby("building_id", sort=False):
    # γ: regress r on phi = delta_win * decay(h)
    w_h = np.exp(-g["h_offset"].to_numpy()/12.0)
    phi = g["delta_win"].to_numpy() * w_h
    num_g = float((g["r"].to_numpy()*phi).sum()); den_g = float((phi*phi).sum()) + eps
    gamma_raw = num_g/den_g; n_g = len(g)
    gamma = float(np.clip(gamma_raw, -0.5, 0.5)) * (n_g/(n_g+L_GAMMA)) if n_g>=MIN_N else 0.0
    rows_g.append((bid, gamma))

    # λ: regress r/yb on (s_win - 1)
    yb = np.clip(g["y_blend"].to_numpy(), 1e-6, None)
    rr = (g["r"].to_numpy()/yb); ss = (g["s_win"].to_numpy() - 1.0)
    num_l = float((rr*ss).sum()); den_l = float((ss*ss).sum()) + eps
    lam_raw = num_l/den_l; n_l = len(g)
    lam = float(np.clip(lam_raw, -0.5, 0.5)) * (n_l/(n_l+L_LAMBDA)) if n_l>=MIN_N else 0.0
    rows_l.append((bid, lam))

gamma_table  = pd.DataFrame(rows_g, columns=["building_id","gamma"])
lambda_table = pd.DataFrame(rows_l, columns=["building_id","lambda"])

gamma_table.to_parquet(f"{DATA_DIR}/gamma_table.parquet", index=False)
lambda_table.to_parquet(f"{DATA_DIR}/lambda_table.parquet", index=False)
print("Saved: gamma_table.parquet, lambda_table.parquet")

Saved: gamma_table.parquet, lambda_table.parquet

In [ ]:
# Load artifacts we just saved (robust to re-runs)
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")
beta24      = pd.read_parquet(f"{DATA_DIR}/beta24_table.parquet")
beta168     = pd.read_parquet(f"{DATA_DIR}/beta168_table.parquet")
gamma_table = pd.read_parquet(f"{DATA_DIR}/gamma_table.parquet")
lambda_table= pd.read_parquet(f"{DATA_DIR}/lambda_table.parquet")

sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"meter_reading_hod"})
sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"meter_reading_ttm"})

# Targets with horizon + hod
targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy()
targets = add_hoffset(targets); targets["hod"] = targets["timestamp"].dt.hour

# Input HoD and window mean for robust fallback
inp = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy().sort_values(["window_id","timestamp"])
yhod_inp_tab = (inp.assign(hod=inp["timestamp"].dt.hour).groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod_inp").reset_index())
wmean_inp = inp.groupby("window_id")["meter_reading"].mean().rename("wmean_inp").reset_index()

# Base blend
blend = (targets
         .merge(sub_hod, on="row_id", how="left")
         .merge(sub_ttm, on="row_id", how="left")
         .merge(alpha_table, on=["building_id","h_offset"], how="left")
         .merge(bias_table,  on=["building_id","h_offset"], how="left")
         .merge(yhod_inp_tab, on=["window_id","hod"], how="left")
         .merge(wmean_inp, on="window_id", how="left"))

y_hod_pred = pd.to_numeric(blend["meter_reading_hod"], errors="coerce")
y_hod_fallback = blend["y_hod_inp"].fillna(blend["wmean_inp"])
y_hod = y_hod_pred.fillna(y_hod_fallback)

y_ttm = pd.to_numeric(blend["meter_reading_ttm"], errors="coerce").fillna(y_hod)
blend["alpha"] = blend["alpha"].fillna(0.0); blend["bias"] = blend["bias"].fillna(0.0)
y_base = (blend["alpha"]*y_ttm + (1-blend["alpha"])*y_hod + blend["bias"]).clip(lower=0)

# Residual features z24/z168 from TEST inputs
idx_in = inp.set_index(["window_id","timestamp"])["meter_reading"].rename("mr_in")

lag24 = targets[["window_id","timestamp"]].copy()
lag24["timestamp_lag"] = lag24["timestamp"] - pd.Timedelta(hours=24)
lag24 = lag24.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag24_val"})

lag168 = targets[["window_id","timestamp"]].copy()
lag168["timestamp_lag"] = lag168["timestamp"] - pd.Timedelta(hours=168)
lag168 = lag168.join(idx_in, on=["window_id","timestamp_lag"]).rename(columns={"mr_in":"lag168_val"})

blend = (blend.merge(lag24[["window_id","timestamp","lag24_val"]], on=["window_id","timestamp"], how="left")
              .merge(lag168[["window_id","timestamp","lag168_val"]], on=["window_id","timestamp"], how="left")
              .merge(beta24,  on=["building_id","h_offset"], how="left")
              .merge(beta168, on=["building_id","h_offset"], how="left"))

blend["beta24"] = blend["beta24"].fillna(0.0); blend["beta168"] = blend["beta168"].fillna(0.0)
y_hod_inp_safe = blend["y_hod_inp"].fillna(blend["wmean_inp"])
z24  = pd.to_numeric(blend["lag24_val"],  errors="coerce").fillna(y_hod_inp_safe) - y_hod_inp_safe
z168 = pd.to_numeric(blend["lag168_val"], errors="coerce").fillna(y_hod_inp_safe) - y_hod_inp_safe

# Safe residual cap
cap = 0.15 * y_base
y_corr = (y_base + (blend["beta24"]*z24 + blend["beta168"]*z168).clip(lower=-cap, upper=cap)).clip(lower=0)

# Window-level calibration (γ/λ)
w_inputs_te = (inp.groupby("window_id")
                  .agg(
                      head24_mean=("meter_reading", lambda s: s.head(24).mean()),
                      last24_mean=("meter_reading", lambda s: s.tail(24).mean()),
                      x_last=("meter_reading", "last"),
                  ).reset_index())
w_inputs_te["s_win"] = w_inputs_te["last24_mean"] / w_inputs_te["head24_mean"].clip(lower=1e-6)

mask0 = targets["h_offset"].to_numpy()==0
y0_df = targets.loc[mask0, ["window_id"]].copy()
y0_df["y0"] = np.asarray(y_corr)[mask0]
win_feat = w_inputs_te.merge(y0_df, on="window_id", how="left")
win_feat["y0"] = win_feat["y0"].fillna(win_feat["last24_mean"])
win_feat["delta_win"] = (win_feat["x_last"] - win_feat["y0"]).fillna(0.0)

out = (pd.DataFrame({"row_id": targets["row_id"]})
       .join(targets[["window_id","building_id","h_offset"]])
       .join(pd.DataFrame({"y_corr": y_corr}).set_index(targets.index)))

out = (out.merge(win_feat[["window_id","s_win","delta_win"]], on="window_id", how="left")
          .merge(gamma_table, on="building_id", how="left")
          .merge(lambda_table, on="building_id", how="left"))

out["s_win"]  = out["s_win"].fillna(1.0)
out["delta_win"] = out["delta_win"].fillna(0.0)
out["gamma"]  = out["gamma"].fillna(0.0)
out["lambda"] = out["lambda"].fillna(0.0)

scale = (1.0 + out["lambda"] * (out["s_win"] - 1.0)).clip(0.90, 1.15)
w_h = np.exp(-out["h_offset"]/12.0)
offs = out["gamma"] * out["delta_win"] * w_h

y_final = (out["y_corr"] * scale + offs)

# Final no-null guard
y_final = pd.to_numeric(y_final, errors="coerce").replace([np.inf, -np.inf], np.nan)
y_final = y_final.fillna(out["y_corr"]).fillna(y_base).fillna(0).clip(lower=0)

SUB_PATH = f"{DATA_DIR}/submission_final.csv"
pd.DataFrame({"row_id": targets["row_id"], "meter_reading": y_final}).sort_values("row_id").to_csv(SUB_PATH, index=False)
print("Wrote:", SUB_PATH, "| rows:", len(y_final))

Wrote: /content/drive/My Drive/IISC_data/submission_final.csv | rows: 84600

In [ ]:
# --- Hard no-NaN writer (position-based fallbacks) ---

import numpy as np
import pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# We assume these objects exist from your previous cell:
# targets, y_final, out["y_corr"], y_base, y_hod

# Build a compact table aligned by POSITION (not index labels)
sub_fix = pd.DataFrame({
    "row_id": targets["row_id"].to_numpy(),
    "y_final": pd.to_numeric(y_final, errors="coerce"),
    "y_corr":  pd.to_numeric(out["y_corr"], errors="coerce"),
    "y_base":  pd.to_numeric(y_base, errors="coerce"),
    "y_hod":   pd.to_numeric(y_hod, errors="coerce"),
})

# Replace infs -> NaN, then take the first non-null across the fallback order
sub_fix = sub_fix.replace([np.inf, -np.inf], np.nan)

# First non-null among [y_final, y_corr, y_base, y_hod], else 0
sub_fix["meter_reading"] = (
    sub_fix[["y_final","y_corr","y_base","y_hod"]]
      .bfill(axis=1).iloc[:, 0]
      .fillna(0.0)
).clip(lower=0)

# Minimal sanity
n_null = int(sub_fix["meter_reading"].isna().sum())
n_neg  = int((sub_fix["meter_reading"] < 0).sum())
print("Nulls:", n_null, " Negatives:", n_neg)

# Write submission
SUB_CLEAN = f"{DATA_DIR}/submission_final_nonull.csv"
sub_fix[["row_id","meter_reading"]].sort_values("row_id").to_csv(SUB_CLEAN, index=False)
print("Wrote:", SUB_CLEAN, "| rows:", len(sub_fix))

Nulls: 0  Negatives: 0
Wrote: /content/drive/My Drive/IISC_data/submission_final_nonull.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load TRAIN/TEST
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# TRAIN targets with horizon + weekend flag
tgt_tr = (train_df.query("role=='target'")
          [["building_id","window_id","timestamp","meter_reading"]]
          .rename(columns={"meter_reading":"ytrue"}))
tgt_tr = add_hoffset(tgt_tr)
tgt_tr["dow"] = tgt_tr["timestamp"].dt.dayofweek
tgt_tr["is_weekend"] = (tgt_tr["dow"] >= 5).astype(int)

# --- Weekend nudge per (building, h_offset) ---
# bias_weekend = mean(ytrue | weekend) - mean(ytrue)  (shrunk toward 0)
mean_all = (tgt_tr.groupby(["building_id","h_offset"])["ytrue"]
            .mean().rename("mean_all"))
mean_wknd = (tgt_tr[tgt_tr["is_weekend"]==1]
             .groupby(["building_id","h_offset"])["ytrue"]
             .agg(["mean","count"]).rename(columns={"mean":"mean_wknd","count":"n_wknd"}))
wknd = mean_all.to_frame().merge(mean_wknd, left_index=True, right_index=True, how="left").reset_index()

# shrinkage (avoid overfitting on few weekends)
L_WKND = 150
wknd["mean_wknd"] = wknd["mean_wknd"].fillna(wknd["mean_all"])  # if no weekends in group
wknd["n_wknd"] = wknd["n_wknd"].fillna(0)
wknd["bias_weekend"] = (wknd["mean_wknd"] - wknd["mean_all"]) * (wknd["n_wknd"] / (wknd["n_wknd"] + L_WKND))
wknd_table = wknd[["building_id","h_offset","bias_weekend"]]

# --- Quantile bands for clipping ---
# Primary bands at (building, h_offset); fallbacks at (building) and global
q = tgt_tr.groupby(["building_id","h_offset"])["ytrue"].quantile([0.01, 0.99]).unstack(level=-1)
q.columns = ["q01","q99"]
q = q.reset_index()

qb = tgt_tr.groupby("building_id")["ytrue"].quantile([0.01,0.99]).unstack(level=-1).reset_index()
qb.columns = ["building_id","q01_b","q99_b"]

qg01, qg99 = float(tgt_tr["ytrue"].quantile(0.01)), float(tgt_tr["ytrue"].quantile(0.99))

# Save artifacts
wknd_table.to_parquet(f"{DATA_DIR}/wknd_table.parquet", index=False)
q.to_parquet(f"{DATA_DIR}/quant_bhoff.parquet", index=False)
qb.to_parquet(f"{DATA_DIR}/quant_b.parquet", index=False)
with open(f"{DATA_DIR}/quant_global.txt", "w") as f:
    f.write(f"{qg01},{qg99}\n")

print("Saved weekend & quantile artifacts:",
      wknd_table.shape, q.shape, qb.shape, "global:", (qg01, qg99))

Saved weekend & quantile artifacts: (2184, 3) (2184, 4) (91, 3) global: (0.0, 5.130860999999982)

In [ ]:
import pandas as pd, numpy as np
import os

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Pick the latest prediction file you have
candidates = [
    f"{DATA_DIR}/submission_final_nonull.csv",
    f"{DATA_DIR}/submission_final.csv",
]
pred_path = None
for p in candidates:
    if os.path.exists(p):
        pred_path = p
        break
assert pred_path is not None, "No base submission file found."

pred = pd.read_csv(pred_path)  # columns: row_id, meter_reading
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", parse_dates=["timestamp"])

# Join TEST targets to bring keys
def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

tgt_te = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy()
tgt_te = add_hoffset(tgt_te)
tgt_te["dow"] = tgt_te["timestamp"].dt.dayofweek
tgt_te["is_weekend"] = (tgt_te["dow"] >= 5).astype(int)

df = tgt_te.merge(pred, on="row_id", how="left")
y = pd.to_numeric(df["meter_reading"], errors="coerce")

# Load artifacts
wknd = pd.read_parquet(f"{DATA_DIR}/wknd_table.parquet")
qbh = pd.read_parquet(f"{DATA_DIR}/quant_bhoff.parquet")
qb  = pd.read_parquet(f"{DATA_DIR}/quant_b.parquet")
with open(f"{DATA_DIR}/quant_global.txt","r") as f:
    qg01, qg99 = map(float, f.read().strip().split(","))

# --- Weekend nudge (additive) ---
df = df.merge(wknd, on=["building_id","h_offset"], how="left")
df["bias_weekend"] = df["bias_weekend"].fillna(0.0)
y1 = y + df["is_weekend"] * df["bias_weekend"]
y1 = pd.to_numeric(y1, errors="coerce")

# --- 24h smoothing within each window (gentle, horizon-dependent) ---
# Kernel and weight schedule
kernel = np.array([0.1, 0.2, 0.4, 0.2, 0.1])
w_sched = np.linspace(0.20, 0.55, 24).astype(float)  # more smoothing later
w_sched[0] = 0.10

# Apply per window_id
y2 = y1.copy().to_numpy()
for wid, idx in df.groupby("window_id").indices.items():
    # idx are positions in df for this window's 24 target rows (already sorted by timestamp from add_hoffset)
    g = y1.iloc[idx].to_numpy()
    # reflect-pad for edges
    ext = np.r_[g[1:2][::-1], g, g[-2:-1][::-1]]  # pad 1 on each side
    sm  = np.convolve(ext, kernel, mode="same")[1:-1]
    # blend with schedule
    w = w_sched[:len(sm)]
    y2[idx] = (1.0 - w) * g + w * sm

y2 = np.clip(y2, 0, None)

# --- Percentile clip using TRAIN quantiles with fallbacks ---
# Merge (building,h_offset) quantiles
df = df.merge(qbh, on=["building_id","h_offset"], how="left")
df = df.merge(qb, on="building_id", how="left")

# Cascade fallbacks
qlo = df["q01"].fillna(df["q01_b"]).fillna(qg01)
qhi = df["q99"].fillna(df["q99_b"]).fillna(qg99)

# Slightly relaxed band to avoid over-clipping
band_lo = 0.95 * qlo
band_hi = 1.05 * qhi

y3 = np.clip(y2, band_lo.to_numpy(), band_hi.to_numpy())
y3 = np.nan_to_num(y3, nan=0.0, posinf=0.0, neginf=0.0)

# --- Final write (no NaNs, >=0) ---
sub_out = pd.DataFrame({
    "row_id": df["row_id"].to_numpy(),
    "meter_reading": np.clip(y3, 0, None)
}).sort_values("row_id")

assert sub_out["meter_reading"].notna().all()
assert (sub_out["meter_reading"] >= 0).all()
assert len(sub_out) == 84600 and sub_out["row_id"].is_unique

OUT = f"{DATA_DIR}/submission_postproc_weekend_smooth_clip.csv"
sub_out.to_csv(OUT, index=False)
print("Wrote:", OUT, "| rows:", len(sub_out))

Wrote: /content/drive/My Drive/IISC_data/submission_postproc_weekend_smooth_clip.csv | rows: 84600

In [ ]:
import os, pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Candidate component submissions (add/remove names if you have more)
cands = {
    "final":      f"{DATA_DIR}/submission_final_nonull.csv",       # best: 0.43723
    "calib":      f"{DATA_DIR}/submission_calibrated.csv",         # 0.43820
    "lag24":      f"{DATA_DIR}/submission_blend_cf_lag24.csv",     # 0.44575
    "blendcf":    f"{DATA_DIR}/submission_blend_cf.csv",           # ~0.4476
    "ttm":        f"{DATA_DIR}/submission_ttm.csv",                # pure TTM
    "hod":        f"{DATA_DIR}/submission_hod.csv",                # pure HoD
}

# Load only the files that exist
dfs = {}
for k, p in cands.items():
    if os.path.exists(p):
        df = pd.read_csv(p)
        if set(df.columns) == {"row_id","meter_reading"}:
            dfs[k] = df.rename(columns={"meter_reading": f"m_{k}"}).sort_values("row_id")
            print(f"Loaded: {k} <- {p} ({len(df)} rows)")
        else:
            print(f"Skip {k}: wrong columns in {p}")

assert "final" in dfs, "Need submission_final_nonull.csv present."

# Merge all on row_id
base = dfs["final"][["row_id"]].copy()
for k, df in dfs.items():
    base = base.merge(df, on="row_id", how="left")

# Helper to write safely
def write_submission(series, name):
    y = pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan)
    # fallback chain: blend -> final -> 0
    y = y.fillna(base["m_final"]).fillna(0).clip(lower=0)
    out = base[["row_id"]].copy()
    out["meter_reading"] = y
    out = out.sort_values("row_id")
    out_path = f"{DATA_DIR}/{name}.csv"
    out.to_csv(out_path, index=False)
    print("Wrote:", out_path, "| rows:", len(out))
    return out_path

paths = []

# --- Weighted blends (prioritize final + calib / lag24) ---
if "calib" in base:
    paths.append(write_submission(0.80*base["m_final"] + 0.20*base["m_calib"], "submission_ens_f80_c20"))
    paths.append(write_submission(0.70*base["m_final"] + 0.30*base["m_calib"], "submission_ens_f70_c30"))

if {"calib","lag24"} <= set(dfs.keys()):
    paths.append(write_submission(0.60*base["m_final"] + 0.30*base["m_calib"] + 0.10*base["m_lag24"], "submission_ens_f60_c30_l10"))
    paths.append(write_submission(0.70*base["m_final"] + 0.20*base["m_calib"] + 0.10*base["m_lag24"], "submission_ens_f70_c20_l10"))

# Small dose of pure signals (helps edges sometimes)
if "ttm" in base:
    paths.append(write_submission(0.85*base["m_final"] + 0.10*base["m_calib"].fillna(base["m_final"]) + 0.05*base["m_ttm"], "submission_ens_f85_c10_ttm5"))
if "hod" in base:
    paths.append(write_submission(0.90*base["m_final"] + 0.10*base["m_hod"], "submission_ens_f90_h10"))

# Robust median across a few models
cols_for_median = [c for c in ["m_final","m_calib","m_lag24","m_ttm","m_hod"] if c in base]
if len(cols_for_median) >= 3:
    paths.append(write_submission(base[cols_for_median].median(axis=1), "submission_ens_median_top"))

print("\nBuilt:", len(paths), "ensemble files.")

Loaded: final <- /content/drive/My Drive/IISC_data/submission_final_nonull.csv (84600 rows)
Loaded: calib <- /content/drive/My Drive/IISC_data/submission_calibrated.csv (84600 rows)
Loaded: lag24 <- /content/drive/My Drive/IISC_data/submission_blend_cf_lag24.csv (84600 rows)
Loaded: blendcf <- /content/drive/My Drive/IISC_data/submission_blend_cf.csv (84600 rows)
Loaded: ttm <- /content/drive/My Drive/IISC_data/submission_ttm.csv (84600 rows)
Loaded: hod <- /content/drive/My Drive/IISC_data/submission_hod.csv (84600 rows)
Wrote: /content/drive/My Drive/IISC_data/submission_ens_f60_c30_l10.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_f70_c20_l10.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_median_top.csv | rows: 84600

Built: 3 ensemble files.

In [ ]:
import pandas as pd, os

DATA_DIR = "/content/drive/My Drive/IISC_data"
to_check = [f for f in os.listdir(DATA_DIR) if f.startswith("submission_ens_") and f.endswith(".csv")]
to_check = sorted(to_check)

def sanity(path):
    s = pd.read_csv(os.path.join(DATA_DIR, path))
    ok = (list(s.columns)==["row_id","meter_reading"]
          and len(s)==84600
          and s["row_id"].is_unique
          and s["meter_reading"].notna().all()
          and (s["meter_reading"]>=0).all())
    print(("OK  " if ok else "FAIL"), path)
    return ok

print("Sanity results:")
ok_files = [p for p in to_check if sanity(p)]

print("\nSuggested submission order (try a few):")
order = [p for p in ok_files if "f80_c20" in p] + \
        [p for p in ok_files if "f70_c30" in p] + \
        [p for p in ok_files if "f70_c20_l10" in p] + \
        [p for p in ok_files if "f60_c30_l10" in p] + \
        [p for p in ok_files if "f85_c10_ttm5" in p] + \
        [p for p in ok_files if "f90_h10" in p] + \
        [p for p in ok_files if "median_top" in p]
for i, p in enumerate(order[:6], 1):
    print(f"{i}. {p}")

Sanity results:
OK   submission_ens_f60_c30_l10.csv
OK   submission_ens_f70_c20_l10.csv
OK   submission_ens_median_top.csv

Suggested submission order (try a few):
1. submission_ens_f70_c20_l10.csv
2. submission_ens_f60_c30_l10.csv
3. submission_ens_median_top.csv

In [ ]:
import os, numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Base submissions (add/remove if you have more)
cands = {
    "final":  f"{DATA_DIR}/submission_final_nonull.csv",   # 0.43723
    "calib":  f"{DATA_DIR}/submission_calibrated.csv",     # 0.43820
    "lag24":  f"{DATA_DIR}/submission_blend_cf_lag24.csv", # 0.44575
    "ttm":    f"{DATA_DIR}/submission_ttm.csv",
    "hod":    f"{DATA_DIR}/submission_hod.csv",
    # keep median_top out of inputs to avoid double-counting
}

# Load existing
dfs = {}
for k, p in cands.items():
    if os.path.exists(p):
        df = pd.read_csv(p)
        if set(df.columns)=={"row_id","meter_reading"}:
            dfs[k] = df.rename(columns={"meter_reading": f"m_{k}"}).sort_values("row_id")
            print(f"Loaded: {k} ({len(df)})")
assert "final" in dfs, "Need submission_final_nonull.csv present."

# Merge on row_id
base = dfs["final"][["row_id"]].copy()
for k, df in dfs.items():
    base = base.merge(df, on="row_id", how="left")

cols = [c for c in ["m_final","m_calib","m_lag24","m_ttm","m_hod"] if c in base]

def row_trimmed_mean(mat_row):
    v = mat_row[np.isfinite(mat_row)]
    if v.size == 0: return np.nan
    v = np.sort(v)
    if v.size >= 5:
        v = v[1:-1]                # drop min & max
    elif v.size == 4:
        v = v[1:-1]                # drop extremes → mean middle two
    elif v.size == 3:
        return float(np.median(v)) # median for 3
    return float(np.mean(v))

def row_winsor_mean(mat_row):
    v = mat_row[np.isfinite(mat_row)]
    if v.size == 0: return np.nan
    v = np.sort(v)
    if v.size >= 3:
        v[0]  = v[1]               # winsorize ends
        v[-1] = v[-2]
    return float(np.mean(v))

def row_power_mean(mat_row, p=0.5):
    v = mat_row[np.isfinite(mat_row)]
    if v.size == 0: return np.nan
    if p == 0:  # geometric mean limit
        v = np.clip(v, 1e-9, None)
        return float(np.exp(np.mean(np.log(v))))
    return float((np.mean(np.power(np.clip(v, 0, None), p))) ** (1.0/p))

M = base[cols].to_numpy(float)

trimmed = np.array([row_trimmed_mean(M[i]) for i in range(M.shape[0])])
winsor  = np.array([row_winsor_mean(M[i])  for i in range(M.shape[0])])
p05     = np.array([row_power_mean(M[i], p=0.5) for i in range(M.shape[0])])

def write_safe(name, vec):
    y = pd.to_numeric(pd.Series(vec), errors="coerce").replace([np.inf,-np.inf], np.nan)
    # Fallback chain: ensemble → m_final → 0
    y = y.fillna(base.get("m_final")).fillna(0).clip(lower=0)
    out = base[["row_id"]].copy()
    out["meter_reading"] = y
    path = f"{DATA_DIR}/{name}.csv"
    out.to_csv(path, index=False)
    print("Wrote:", path, "| rows:", len(out))
    return path

p1 = write_safe("submission_ens_trimmed.csv", trimmed)
p2 = write_safe("submission_ens_winsor.csv",  winsor)
p3 = write_safe("submission_ens_power05.csv", p05)

# Also try a convex blend between your best median and final (if median file exists)
med_path = f"{DATA_DIR}/submission_ens_median_top.csv"
if os.path.exists(med_path):
    med = pd.read_csv(med_path).sort_values("row_id")["meter_reading"].to_numpy()
    f   = base["m_final"].to_numpy()
    p4 = write_safe("submission_ens_medfin_60_40.csv", 0.60*med + 0.40*f)
    p5 = write_safe("submission_ens_medfin_70_30.csv", 0.70*med + 0.30*f)

Loaded: final (84600)
Loaded: calib (84600)
Loaded: lag24 (84600)
Loaded: ttm (84600)
Loaded: hod (84600)
Wrote: /content/drive/My Drive/IISC_data/submission_ens_trimmed.csv.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_winsor.csv.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_power05.csv.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_medfin_60_40.csv.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_ens_medfin_70_30.csv.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")
fin = pd.read_csv(f"{DATA_DIR}/submission_final_nonull.csv").sort_values("row_id")

def write_blend(name, w_med, w_fin):
    y = (w_med*med["meter_reading"] + w_fin*fin["meter_reading"]).clip(lower=0)
    out = pd.DataFrame({"row_id": med["row_id"], "meter_reading": y})
    out.to_csv(f"{DATA_DIR}/{name}.csv", index=False)
    print("Wrote:", f"{DATA_DIR}/{name}.csv")

write_blend("submission_ens_medfin_80_20", 0.80, 0.20)
write_blend("submission_ens_medfin_75_25", 0.75, 0.25)

Wrote: /content/drive/My Drive/IISC_data/submission_ens_medfin_80_20.csv
Wrote: /content/drive/My Drive/IISC_data/submission_ens_medfin_75_25.csv

In [ ]:
!pip -q install lightgbm==4.3.0

import numpy as np, pandas as pd, os
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMRegressor

DATA_DIR = "/content/drive/My Drive/IISC_data"
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# Targets with horizon
tgt_tr = add_hoffset(train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
                     .rename(columns={"meter_reading":"ytrue"}))
tgt_te = add_hoffset(test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]])

# Inputs (168h) sorted
inp_tr = train_df.query("role=='input'")[["window_id","building_id","timestamp","meter_reading"]].sort_values(["window_id","timestamp"])
inp_te = test_df.query("role=='input'")[["window_id","building_id","timestamp","meter_reading"]].sort_values(["window_id","timestamp"])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 34.8 MB/s eta 0:00:00

In [ ]:
def build_window_features(inputs_window: pd.DataFrame):
    """Return dict with per-window scalar features computed from the last 168h."""
    s = inputs_window["meter_reading"].to_numpy(dtype=float)
    # Safety for short windows (shouldn't happen)
    if len(s) < 168:
        s = np.pad(s, (168-len(s), 0), mode="edge")
    # Scalars from the entire window
    feats = {
        "x_last": float(s[-1]),
        "m3":  float(s[-3:].mean()),
        "m6":  float(s[-6:].mean()),
        "m12": float(s[-12:].mean()),
        "m24": float(s[-24:].mean()),
        "m48": float(s[-48:].mean()),
        "std24": float(s[-24:].std(ddof=0)),
        "min168": float(s.min()),
        "max168": float(s.max()),
        "ratio_last24_first24": float(s[-24:].mean() / max(s[:24].mean(), 1e-6)),
        "slope48": float(np.polyfit(np.arange(48), s[-48:], 1)[0]) if np.all(np.isfinite(s[-48:])) else 0.0,
    }
    # Hour-of-day mean over the 7 days (168 = 7*24)
    hod_map = inputs_window.assign(hod=inputs_window["timestamp"].dt.hour)\
                           .groupby("hod")["meter_reading"].mean().to_dict()
    return feats, hod_map, s

def build_features_frame(inputs_all: pd.DataFrame, targets_all: pd.DataFrame, is_train: bool):
    """Construct one row per target with features from its window inputs."""
    rows = []
    # Pre-chunk targets by window for speed
    t_groups = {wid: g.copy() for wid, g in targets_all.groupby("window_id")}
    for wid, g_inp in inputs_all.groupby("window_id"):
        feats, hod_map, s = build_window_features(g_inp)
        if wid not in t_groups:
            continue
        g_tgt = t_groups[wid].sort_values("timestamp").copy()
        # Make sure we have horizons (0..23)
        if "h_offset" not in g_tgt.columns:
            g_tgt = add_hoffset(g_tgt)
        for _, r in g_tgt.iterrows():
            h = int(r["h_offset"])
            hod = int(r["timestamp"].hour)
            week_ago = float(s[h])         # same hour last week (aligns inside 168h)
            hod_mean = float(hod_map.get(hod, np.nan))
            rows.append({
                # keys
                **({"row_id": int(r["row_id"])} if not is_train else {}),
                "window_id": r["window_id"],
                "building_id": r["building_id"],
                "h_offset": h,
                # targets (train)
                **({"ytrue": float(r["ytrue"])} if is_train else {}),
                # scalar window feats
                **feats,
                # horizon/weekly alignment feats
                "week_ago": week_ago,
                "hod_mean": hod_mean,
                "week_ago_minus_hod": week_ago - (hod_mean if np.isfinite(hod_mean) else week_ago),
                # cyclical time
                "hod": hod,
                "sin_h": np.sin(2*np.pi*hod/24.0),
                "cos_h": np.cos(2*np.pi*hod/24.0),
            })
    df = pd.DataFrame(rows)
    # Robust fill
    for c in ["hod_mean","week_ago_minus_hod"]:
        if c in df.columns:
            df[c] = df[c].fillna(df[c].median())
    # Building as category
    df["building_id"] = df["building_id"].astype("category")
    return df

# Build frames
feat_tr = build_features_frame(inp_tr, tgt_tr, is_train=True)
feat_te = build_features_frame(inp_te, tgt_te, is_train=False)
print("Train feats:", feat_tr.shape, " Test feats:", feat_te.shape)

Train feats: (322872, 21)  Test feats: (84600, 21)

In [ ]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# --- same setup as before ---
drop_cols = {"row_id","window_id","ytrue"}
X_cols = [c for c in feat_tr.columns if c not in drop_cols]

pred_te, pred_tr = [], []

params = dict(
    n_estimators=800,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=60,
    subsample=0.9,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42,
    n_jobs=-1,
    verbosity=-1,  # <- use this (no 'verbose' in .fit)
)

for h in range(24):
    tr_h = feat_tr[feat_tr["h_offset"]==h].copy()
    te_h = feat_te[feat_te["h_offset"]==h].copy()

    X_tr = tr_h[X_cols]; y_tr = tr_h["ytrue"].astype(float)
    X_te = te_h[X_cols]

    # scale only continuous columns
    cont_cols = [c for c in X_cols if c not in ["building_id"]]
    scaler = StandardScaler().fit(X_tr[cont_cols])
    X_tr_scaled = X_tr.copy(); X_tr_scaled[cont_cols] = scaler.transform(X_tr[cont_cols])
    X_te_scaled = X_te.copy(); X_te_scaled[cont_cols] = scaler.transform(X_te[cont_cols])

    cat_cols = ["building_id"] if "building_id" in X_cols else []

    model = LGBMRegressor(**params)
    model.fit(
        X_tr_scaled, y_tr,
        categorical_feature=cat_cols,
        callbacks=[lgb.log_evaluation(period=0)]  # silence training logs
    )

    te_pred = model.predict(X_te_scaled)
    tr_pred = model.predict(X_tr_scaled)

    te_out = te_h[["row_id"]].copy(); te_out["meter_reading_lgbm"] = np.clip(te_pred, 0, None)
    tr_out = tr_h[["window_id","h_offset"]].copy(); tr_out["yhat_lgbm"] = np.clip(tr_pred, 0, None)
    pred_te.append(te_out); pred_tr.append(tr_out)

pred_te = pd.concat(pred_te, ignore_index=True).sort_values("row_id")
pred_tr = pd.concat(pred_tr, ignore_index=True)
pred_te.to_csv(f"{DATA_DIR}/submission_lgbm.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_lgbm.csv", pred_te.shape)

Wrote: /content/drive/My Drive/IISC_data/submission_lgbm.csv (84600, 2)

In [ ]:
# Load base submissions you already created
base_best = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")  # your 0.43380-ish
base_fin  = pd.read_csv(f"{DATA_DIR}/submission_final_nonull.csv").sort_values("row_id")    # 0.43723
lgbm      = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")

# Safety joins
df = base_best.merge(base_fin, on="row_id", suffixes=("_med","_fin")).merge(lgbm, on="row_id")
df = df.rename(columns={"meter_reading_med":"m_med", "meter_reading_fin":"m_fin"})

def write_safe(series, name):
    y = pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan)
    y = y.fillna(df["m_med"]).fillna(df["m_fin"]).fillna(df["meter_reading_lgbm"]).fillna(0).clip(lower=0)
    out = df[["row_id"]].copy(); out["meter_reading"] = y
    path = f"{DATA_DIR}/{name}.csv"
    out.to_csv(path, index=False); print("Wrote:", path, "| rows:", len(out))
    return path

paths = []
# Conservative: mostly median, small LGBM spice
paths.append(write_safe(0.85*df["m_med"] + 0.15*df["meter_reading_lgbm"], "submission_stack_med85_lgbm15"))
paths.append(write_safe(0.80*df["m_med"] + 0.20*df["meter_reading_lgbm"], "submission_stack_med80_lgbm20"))

# Tri-blends with final_nonull (often stabilizes)
paths.append(write_safe(0.70*df["m_med"] + 0.20*df["m_fin"] + 0.10*df["meter_reading_lgbm"], "submission_stack_m70_f20_l10"))
paths.append(write_safe(0.60*df["m_med"] + 0.25*df["m_fin"] + 0.15*df["meter_reading_lgbm"], "submission_stack_m60_f25_l15"))

# A bolder option
paths.append(write_safe(0.50*df["m_med"] + 0.30*df["m_fin"] + 0.20*df["meter_reading_lgbm"], "submission_stack_m50_f30_l20"))

Wrote: /content/drive/My Drive/IISC_data/submission_stack_med85_lgbm15.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_stack_med80_lgbm20.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_stack_m70_f20_l10.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_stack_m60_f25_l15.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_stack_m50_f30_l20.csv | rows: 84600

In [ ]:
!pip -q install "granite-tsfm[notebooks]==0.3.1"

import torch, numpy as np, pandas as pd
from tsfm_public import (
    TimeSeriesPreprocessor,
    TinyTimeMixerForPrediction,
    TimeSeriesForecastingPipeline,
)

print("granite-tsfm ready. Torch:", torch.__version__)

granite-tsfm ready. Torch: 2.8.0+cu126

In [ ]:
!pip -q install lightgbm==4.3.0

In [ ]:
# Rebuild LGBM TRAIN predictions (pred_tr) and TEST preds (submission_lgbm.csv)

import pandas as pd, numpy as np
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMRegressor

DATA_DIR = "/content/drive/My Drive/IISC_data"

# 1) Reload data
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])

def add_hoffset(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# 2) Feature builders (same as earlier)
def build_window_features(inputs_window: pd.DataFrame):
    s = inputs_window["meter_reading"].to_numpy(float)
    if len(s) < 168:
        s = np.pad(s, (168-len(s), 0), mode="edge")
    feats = {
        "x_last": float(s[-1]),
        "m3":  float(s[-3:].mean()),
        "m6":  float(s[-6:].mean()),
        "m12": float(s[-12:].mean()),
        "m24": float(s[-24:].mean()),
        "m48": float(s[-48:].mean()),
        "std24": float(s[-24:].std(ddof=0)),
        "min168": float(s.min()),
        "max168": float(s.max()),
        "ratio_last24_first24": float(s[-24:].mean() / max(s[:24].mean(), 1e-6)),
        "slope48": float(np.polyfit(np.arange(48), s[-48:], 1)[0]),
    }
    hod_map = (inputs_window.assign(hod=inputs_window["timestamp"].dt.hour)
               .groupby("hod")["meter_reading"].mean().to_dict())
    return feats, hod_map, s

def build_features_frame(inputs_all: pd.DataFrame, targets_all: pd.DataFrame, is_train: bool):
    rows = []
    t_groups = {wid: g.copy() for wid, g in targets_all.groupby("window_id")}
    for wid, g_inp in inputs_all.groupby("window_id"):
        feats, hod_map, s = build_window_features(g_inp.sort_values("timestamp"))
        if wid not in t_groups:
            continue
        g_tgt = add_hoffset(t_groups[wid].sort_values("timestamp"))
        for _, r in g_tgt.iterrows():
            h = int(r["h_offset"]); hod = int(r["timestamp"].hour)
            week_ago = float(s[h])  # align within 168h
            hod_mean = float(hod_map.get(hod, week_ago))
            rows.append({
                **({"row_id": int(r["row_id"])} if not is_train else {}),
                "window_id": r["window_id"],
                "building_id": r["building_id"],
                "h_offset": h,
                **({"ytrue": float(r["ytrue"])} if is_train else {}),
                **feats,
                "week_ago": week_ago,
                "hod_mean": hod_mean,
                "week_ago_minus_hod": week_ago - hod_mean,
                "hod": hod,
                "sin_h": np.sin(2*np.pi*hod/24.0),
                "cos_h": np.cos(2*np.pi*hod/24.0),
            })
    df = pd.DataFrame(rows)
    df["building_id"] = df["building_id"].astype("category")
    for c in ["hod_mean","week_ago_minus_hod"]:
        if c in df: df[c] = df[c].fillna(df[c].median())
    return df

# 3) Build frames
tgt_tr = add_hoffset(train_df.query("role=='target'")[["window_id","building_id","timestamp","meter_reading"]]
                     .rename(columns={"meter_reading":"ytrue"}))
tgt_te = add_hoffset(test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]])
inp_tr = train_df.query("role=='input'")[["window_id","building_id","timestamp","meter_reading"]].sort_values(["window_id","timestamp"])
inp_te = test_df.query("role=='input'")[["window_id","building_id","timestamp","meter_reading"]].sort_values(["window_id","timestamp"])

feat_tr_lgb = build_features_frame(inp_tr, tgt_tr, is_train=True)
feat_te_lgb = build_features_frame(inp_te, tgt_te, is_train=False)

# 4) Train 24 LGBM models; get TRAIN preds (pred_tr) and TEST preds (submission_lgbm.csv)
drop_cols = {"row_id","window_id","ytrue"}
X_cols = [c for c in feat_tr_lgb.columns if c not in drop_cols]
params = dict(
    n_estimators=800, learning_rate=0.03, num_leaves=63,
    min_data_in_leaf=60, subsample=0.9, colsample_bytree=0.8,
    reg_alpha=0.1, reg_lambda=1.0, random_state=42, n_jobs=-1, verbosity=-1,
)

from lightgbm import LGBMRegressor
pred_tr_list, pred_te_list = [], []
for h in range(24):
    tr_h = feat_tr_lgb[feat_tr_lgb["h_offset"]==h].copy()
    te_h = feat_te_lgb[feat_te_lgb["h_offset"]==h].copy()

    X_tr = tr_h[X_cols]; y_tr = tr_h["ytrue"].astype(float)
    X_te = te_h[X_cols]

    cont_cols = [c for c in X_cols if c not in ["building_id"]]
    scaler = StandardScaler().fit(X_tr[cont_cols])
    X_tr_scaled = X_tr.copy(); X_tr_scaled[cont_cols] = scaler.transform(X_tr[cont_cols])
    X_te_scaled = X_te.copy(); X_te_scaled[cont_cols] = scaler.transform(X_te[cont_cols])

    model = LGBMRegressor(**params)
    model.fit(X_tr_scaled, y_tr, categorical_feature=["building_id"])

    # TRAIN predictions for super-stack learning
    yhat_tr = np.clip(model.predict(X_tr_scaled), 0, None)
    out_tr = tr_h[["window_id","h_offset"]].copy(); out_tr["yhat_lgbm"] = yhat_tr
    pred_tr_list.append(out_tr)

    # TEST predictions for stacking later (if needed)
    yhat_te = np.clip(model.predict(X_te_scaled), 0, None)
    out_te = te_h[["row_id"]].copy(); out_te["meter_reading_lgbm"] = yhat_te
    pred_te_list.append(out_te)

pred_tr = pd.concat(pred_tr_list, ignore_index=True)
pred_te = pd.concat(pred_te_list, ignore_index=True).sort_values("row_id")

pred_tr.to_parquet(f"{DATA_DIR}/pred_tr_lgbm.parquet", index=False)
pred_te.to_csv(f"{DATA_DIR}/submission_lgbm.csv", index=False)

print("Rebuilt pred_tr:", pred_tr.shape, "| Wrote submission_lgbm.csv:", pred_te.shape)

Rebuilt pred_tr: (322872, 3) | Wrote submission_lgbm.csv: (84600, 2)

In [ ]:
import pandas as pd, numpy as np
from tqdm import tqdm
import torch
from tsfm_public import TimeSeriesPreprocessor, TinyTimeMixerForPrediction, TimeSeriesForecastingPipeline

DATA_DIR = "/content/drive/My Drive/IISC_data"

train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])

def add_hoffset(df):
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

# TRAIN targets
tgt_tr = (train_df.query("role=='target'")
          [["window_id","building_id","timestamp","meter_reading"]]
          .rename(columns={"meter_reading":"ytrue"}))
tgt_tr = add_hoffset(tgt_tr); tgt_tr["hod"] = tgt_tr["timestamp"].dt.hour

# HoD on TRAIN
inp_tr = train_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].copy()
inp_tr["hod"] = inp_tr["timestamp"].dt.hour
hod_tab = (inp_tr.groupby(["window_id","hod"])["meter_reading"].mean().rename("y_hod").reset_index())
wmean_tr = (inp_tr.groupby("window_id")["meter_reading"].mean().rename("wmean").reset_index())

feat_tr = (tgt_tr.merge(hod_tab, on=["window_id","hod"], how="left")
                 .merge(wmean_tr, on="window_id", how="left"))
feat_tr["y_hod"] = feat_tr["y_hod"].fillna(feat_tr["wmean"]).astype(float)

# LGBM train preds (from your earlier loop). If missing, abort.
assert 'pred_tr' in globals(), "Run the LGBM training cell first to populate pred_tr."
feat_tr = feat_tr.merge(pred_tr.rename(columns={"yhat_lgbm":"y_lgbm"}),
                        on=["window_id","h_offset"], how="left")

# TTM zero-shot on TRAIN (all windows, efficient)
tsp_tr = TimeSeriesPreprocessor(
    timestamp_column="timestamp",
    id_columns=["building_id","window_id"],
    target_columns=["meter_reading"],
    control_columns=[],
    context_length=180, forecast_length=60,
    scaling=True, scaler_type="standard", freq="h",
)
tsp_tr.train(train_df.query("role=='input'"))

ttm_tr = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    revision="180-60-ft-l1-r2.1",
    num_input_channels=1,
).eval()
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe_tr = TimeSeriesForecastingPipeline(ttm_tr, explode_forecasts=True, feature_extractor=tsp_tr, device=device)

def pad_to_180(win_df, ts_col="timestamp"):
    win = win_df.sort_values(ts_col).copy()
    if len(win) == 168:
        pad = win.iloc[:12].copy()
        pad[ts_col] = pad[ts_col] - pd.to_timedelta(np.arange(12, 0, -1), unit="h")
        win = pd.concat([pad, win], ignore_index=True).sort_values(ts_col)
    return win

preds = []
for wi, g in tqdm(train_df.groupby("window_id", sort=False), total=train_df["window_id"].nunique(), desc="TTM train"):
    inp = g[g["role"]=="input"].copy()
    tar = g[g["role"]=="target"][["timestamp"]].copy()
    p = pipe_tr(pad_to_180(inp)).iloc[:24][["meter_reading"]].reset_index(drop=True)
    tar = tar.reset_index(drop=True); tar["y_ttm"] = p["meter_reading"].astype(float); tar["window_id"] = wi
    preds.append(tar)
pred_ttm_tr = pd.concat(preds, ignore_index=True)

feat_tr = (feat_tr.merge(pred_ttm_tr, on=["window_id","timestamp"], how="left")
                   .rename(columns={"y_ttm":"y_ttm"}))
# Final clean
feat_tr["y_lgbm"] = pd.to_numeric(feat_tr["y_lgbm"], errors="coerce")
feat_tr["y_ttm"]  = pd.to_numeric(feat_tr["y_ttm"],  errors="coerce")
feat_tr["ytrue"]  = pd.to_numeric(feat_tr["ytrue"], errors="coerce")
print("TRAIN meta-frame:", feat_tr.shape, "NaNs:", feat_tr.isna().sum().to_dict())

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.04M [00:00<?, ?B/s]

Device set to use cpu
TTM train: 100%|██████████| 13453/13453 [12:28<00:00, 17.98it/s]

TRAIN meta-frame: (322872, 10) NaNs: {'window_id': 0, 'building_id': 0, 'timestamp': 0, 'ytrue': 0, 'h_offset': 0, 'hod': 0, 'y_hod': 0, 'wmean': 0, 'y_lgbm': 0, 'y_ttm': 0}

In [ ]:
import numpy as np, pandas as pd

# Fill occasional holes for stability
feat_tr["y_lgbm"] = feat_tr["y_lgbm"].fillna(feat_tr["y_hod"])
feat_tr["y_ttm"]  = feat_tr["y_ttm"].fillna(feat_tr["y_hod"])

lam = 200.0  # ridge strength
eps = 1e-9

rows = []
for (bid, hoff), g in feat_tr.groupby(["building_id","h_offset"], sort=False):
    X = np.column_stack([
        g["y_hod"].to_numpy(float),
        g["y_ttm"].to_numpy(float),
        g["y_lgbm"].to_numpy(float),
        np.ones(len(g), float)  # bias
    ])
    y = g["ytrue"].to_numpy(float)
    XtX = X.T @ X
    XtX[:3, :3] += lam * np.eye(3)  # penalize only model weights (not bias)
    w = np.linalg.solve(XtX + eps*np.eye(4), X.T @ y)
    # nonneg + renorm for first 3 weights
    w[:3] = np.clip(w[:3], 0, None)
    s = w[:3].sum()
    if s > 0:
        w[:3] = w[:3] / s
    rows.append((bid, hoff, *w))

w_bh = pd.DataFrame(rows, columns=["building_id","h_offset","w_hod","w_ttm","w_lgbm","bias"])

# Smooth weights along horizons per building
ker = np.array([0.2, 0.6, 0.2])
def smooth_group(df, cols):
    out = df.copy()
    for c in cols:
        v = out[c].to_numpy()
        out[c] = np.convolve(v, ker, mode="same")
    return out

w_bh = (w_bh.sort_values(["building_id","h_offset"])
             .groupby("building_id", group_keys=False)
             .apply(lambda d: smooth_group(d, ["w_hod","w_ttm","w_lgbm","bias"])))
# Re-normalize after smoothing
s = w_bh[["w_hod","w_ttm","w_lgbm"]].sum(axis=1)
for c in ["w_hod","w_ttm","w_lgbm"]:
    w_bh[c] = np.where(s>0, w_bh[c]/s, 1.0/3)
w_bh["bias"] = w_bh["bias"].fillna(0.0)

# Fallback weights per building (averaged across horizons)
w_b = (w_bh.groupby("building_id")[["w_hod","w_ttm","w_lgbm","bias"]].mean()
       .reset_index().rename(columns={c:f"{c}_b" for c in ["w_hod","w_ttm","w_lgbm","bias"]}))

w_bh.to_parquet(f"{DATA_DIR}/stack_weights_bh.parquet", index=False)
w_b.to_parquet(f"{DATA_DIR}/stack_weights_b.parquet", index=False)
print("Saved weights:", w_bh.shape, w_b.shape)

Saved weights: (2184, 6) (91, 5)

/tmp/ipython-input-1961195770.py:42: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda d: smooth_group(d, ["w_hod","w_ttm","w_lgbm","bias"])))

In [ ]:
# Load TEST base predictions you already have
sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"y_hod"})
sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"y_ttm"})
sub_lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").rename(columns={"meter_reading_lgbm":"y_lgbm"})

targets = test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy()
targets = add_hoffset(targets)

# Join predictions
S = (targets.merge(sub_hod, on="row_id", how="left")
            .merge(sub_ttm, on="row_id", how="left")
            .merge(sub_lgb, on="row_id", how="left"))

# Fill safety
S["y_ttm"]  = pd.to_numeric(S["y_ttm"], errors="coerce")
S["y_lgbm"] = pd.to_numeric(S["y_lgbm"], errors="coerce")
S["y_hod"]  = pd.to_numeric(S["y_hod"], errors="coerce")
S["y_ttm"]  = S["y_ttm"].fillna(S["y_hod"])
S["y_lgbm"] = S["y_lgbm"].fillna(S["y_hod"])

# Merge weights (bh first, then building fallback)
w_bh = pd.read_parquet(f"{DATA_DIR}/stack_weights_bh.parquet")
w_b  = pd.read_parquet(f"{DATA_DIR}/stack_weights_b.parquet")
S = (S.merge(w_bh, on=["building_id","h_offset"], how="left")
       .merge(w_b, on=["building_id"], how="left"))

for c in ["w_hod","w_ttm","w_lgbm","bias"]:
    S[c] = S[c].fillna(S[f"{c}_b"]).fillna(1.0/3 if c!="bias" else 0.0)

# Main super-stack
y_ss = (S["w_hod"]*S["y_hod"] + S["w_ttm"]*S["y_ttm"] + S["w_lgbm"]*S["y_lgbm"] + S["bias"]).clip(lower=0)

# (Optional) gentle calibration with your γ/λ if you already learned them
import os
y_final_main = y_ss.copy()
gamma_p = f"{DATA_DIR}/gamma_table.parquet"
lambda_p= f"{DATA_DIR}/lambda_table.parquet"
if os.path.exists(gamma_p) and os.path.exists(lambda_p):
    gamma_table  = pd.read_parquet(gamma_p)
    lambda_table = pd.read_parquet(lambda_p)
    # window features
    inp_te = test_df.query("role=='input'")[["window_id","timestamp","meter_reading"]].sort_values(["window_id","timestamp"])
    w_inputs_te = (inp_te.groupby("window_id")
                   .agg(head24_mean=("meter_reading", lambda s: s.head(24).mean()),
                        last24_mean=("meter_reading", lambda s: s.tail(24).mean()),
                        x_last=("meter_reading", "last"))
                   .reset_index())
    w_inputs_te["s_win"] = w_inputs_te["last24_mean"] / w_inputs_te["head24_mean"].clip(lower=1e-6)
    mask0 = S["h_offset"].to_numpy()==0
    y0_df = S.loc[mask0, ["window_id"]].copy()
    y0_df["y0"] = y_ss[mask0].to_numpy()
    win_feat = w_inputs_te.merge(y0_df, on="window_id", how="left")
    win_feat["y0"] = win_feat["y0"].fillna(win_feat["last24_mean"])
    win_feat["delta_win"] = (win_feat["x_last"] - win_feat["y0"]).fillna(0.0)

    D = (S[["row_id","window_id","building_id","h_offset"]]
         .merge(win_feat[["window_id","s_win","delta_win"]], on="window_id", how="left")
         .merge(gamma_table, on="building_id", how="left")
         .merge(lambda_table, on="building_id", how="left"))
    D["s_win"]  = D["s_win"].fillna(1.0)
    D["delta_win"] = D["delta_win"].fillna(0.0)
    D["gamma"]  = D["gamma"].fillna(0.0)
    D["lambda"] = D["lambda"].fillna(0.0)
    scale = (1.0 + D["lambda"] * (D["s_win"] - 1.0)).clip(0.90, 1.15)
    w_h = np.exp(-D["h_offset"]/12.0)
    offs = D["gamma"] * D["delta_win"] * w_h
    y_final_main = (y_ss * scale + offs).clip(lower=0)

# Safe variant: tighter scale caps
y_final_safe = y_final_main.copy()
if 'scale' in locals():
    scale_safe = scale.clip(0.92, 1.10)
    y_final_safe = (y_ss * scale_safe + offs).clip(lower=0)

# Write files
OUT1 = f"{DATA_DIR}/submission_superstack.csv"
OUT2 = f"{DATA_DIR}/submission_superstack_safe.csv"
pd.DataFrame({"row_id": S["row_id"], "meter_reading": y_final_main}).sort_values("row_id").to_csv(OUT1, index=False)
pd.DataFrame({"row_id": S["row_id"], "meter_reading": y_final_safe}).sort_values("row_id").to_csv(OUT2, index=False)
print("Wrote:", OUT1, "and", OUT2)

Wrote: /content/drive/My Drive/IISC_data/submission_superstack.csv and /content/drive/My Drive/IISC_data/submission_superstack_safe.csv

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# 1) TRAIN target frame with horizon + HoD and TTM (already computed in your meta-frame step)
#    feat_tr has columns: [building_id, window_id, timestamp, h_offset, ytrue, y_hod]
#    pred_ttm_tr has ['window_id','timestamp','y_ttm']
assert 'feat_tr' in globals(), "Run the meta-frame step so feat_tr exists."
assert 'pred_ttm_tr' in globals(), "Run the TTM train loop so pred_ttm_tr exists."

feat_tr_blend = (feat_tr[["building_id","window_id","h_offset","timestamp","ytrue","y_hod"]]
                 .merge(pred_ttm_tr, on=["window_id","timestamp"], how="left")
                 .rename(columns={"y_ttm":"y_ttm_tr"}))

# LGBM train predictions (you rebuilt earlier as pred_tr)
if 'pred_tr' not in globals():
    pred_tr = pd.read_parquet(f"{DATA_DIR}/pred_tr_lgbm.parquet")
feat_tr_blend = feat_tr_blend.merge(pred_tr, on=["window_id","h_offset"], how="left") \
                             .rename(columns={"yhat_lgbm":"y_lgbm_tr"})

# 2) Alpha & bias tables (closed-form) – already computed earlier
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

feat_tr_blend = (feat_tr_blend
                 .merge(alpha_table, on=["building_id","h_offset"], how="left")
                 .merge(bias_table,  on=["building_id","h_offset"], how="left"))
feat_tr_blend["alpha"] = feat_tr_blend["alpha"].fillna(0.0)
feat_tr_blend["bias"]  = feat_tr_blend["bias"].fillna(0.0)

# 3) Base prediction on TRAIN using HoD+TTM+bias; fill any TTM gaps with HoD
feat_tr_blend["y_ttm_tr"] = pd.to_numeric(feat_tr_blend["y_ttm_tr"], errors="coerce").fillna(feat_tr_blend["y_hod"])
feat_tr_blend["y_base_tr"] = (feat_tr_blend["alpha"]*feat_tr_blend["y_ttm_tr"]
                              + (1.0 - feat_tr_blend["alpha"])*feat_tr_blend["y_hod"]
                              + feat_tr_blend["bias"]).clip(lower=0)

# 4) Closed-form optimal weight w between LGBM and base, per (building,h_offset) with shrinkage
#    Min E[(w*d - r)^2], where d = (y_lgbm - y_base), r = (y_base - ytrue)*(-1)
feat_tr_blend["d"] = (pd.to_numeric(feat_tr_blend["y_lgbm_tr"], errors="coerce")
                      - feat_tr_blend["y_base_tr"])
feat_tr_blend["r"] = (feat_tr_blend["ytrue"] - feat_tr_blend["y_base_tr"])

rows = []
LAM = 50.0    # ridge on denominator (stability)
SHR = 200.0   # shrinkage strength toward 0 (prefer base)
for (bid, hoff), g in feat_tr_blend.dropna(subset=["d","r"]).groupby(["building_id","h_offset"], sort=False):
    num = float((g["d"] * g["r"]).sum())
    den = float((g["d"] * g["d"]).sum() + LAM)
    w_raw = num / den
    # clip to reasonable range; we don't want to overweight LGBM
    w_raw = float(np.clip(w_raw, 0.0, 0.6))
    n = len(g)
    w_shr = w_raw * (n / (n + SHR))      # shrink toward 0 (base)
    rows.append((bid, hoff, w_shr, n))

w_bh = pd.DataFrame(rows, columns=["building_id","h_offset","w_lgbm","n"])

# Smooth weights across horizons within each building
ker = np.array([0.25, 0.5, 0.25])
def smooth_group(df):
    out = df.sort_values("h_offset").copy()
    v = out["w_lgbm"].to_numpy()
    out["w_lgbm"] = np.convolve(v, ker, mode="same")
    return out

w_bh = w_bh.groupby("building_id", group_keys=False).apply(smooth_group)
# Fallback per building (mean across horizons)
w_b = w_bh.groupby("building_id")["w_lgbm"].mean().rename("w_lgbm_b").reset_index()

w_bh.to_parquet(f"{DATA_DIR}/stack_w_bh.parquet", index=False)
w_b.to_parquet(f"{DATA_DIR}/stack_w_b.parquet", index=False)
print("Saved weights:", w_bh.shape, w_b.shape, "w range:", (w_bh['w_lgbm'].min(), w_bh['w_lgbm'].max()))

Saved weights: (2184, 4) (91, 2) w range: (4.529699997246734e-07, 0.37859778597785976)

/tmp/ipython-input-1485815049.py:66: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  w_bh = w_bh.groupby("building_id", group_keys=False).apply(smooth_group)

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load test targets and horizon
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])
def add_hoffset(df):
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out
targets = add_hoffset(test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy())

# Load base components
sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"y_hod"})
sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"y_ttm"})
sub_lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").rename(columns={"meter_reading_lgbm":"y_lgbm"})
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

# Merge base + weights
S = (targets.merge(sub_hod, on="row_id", how="left")
            .merge(sub_ttm, on="row_id", how="left")
            .merge(sub_lgb, on="row_id", how="left")
            .merge(alpha_table, on=["building_id","h_offset"], how="left")
            .merge(bias_table,  on=["building_id","h_offset"], how="left"))

S["alpha"] = S["alpha"].fillna(0.0)
S["bias"]  = S["bias"].fillna(0.0)
S["y_ttm"] = pd.to_numeric(S["y_ttm"], errors="coerce").fillna(S["y_hod"])
S["y_hod"] = pd.to_numeric(S["y_hod"], errors="coerce").fillna(0)
S["y_lgbm"]= pd.to_numeric(S["y_lgbm"],errors="coerce").fillna(S["y_hod"])

y_base = (S["alpha"]*S["y_ttm"] + (1.0 - S["alpha"])*S["y_hod"] + S["bias"]).clip(lower=0)

# Learned weights
w_bh = pd.read_parquet(f"{DATA_DIR}/stack_w_bh.parquet")
w_b  = pd.read_parquet(f"{DATA_DIR}/stack_w_b.parquet")
S = (S.merge(w_bh, on=["building_id","h_offset"], how="left")
       .merge(w_b,  on=["building_id"], how="left"))
S["w_lgbm"] = S["w_lgbm"].fillna(S["w_lgbm_b"]).fillna(0.15)  # safe default

# Main blend: y = base + w*(lgbm - base)
y_main = (y_base + S["w_lgbm"] * (S["y_lgbm"] - y_base)).clip(lower=0)

# Gentle horizon smoothing inside each window (helps jitter; very small)
y_sm = y_main.copy().to_numpy()
kernel = np.array([0.2,0.6,0.2])
for wid, idx in S.groupby("window_id").indices.items():
    v = y_main.iloc[idx].to_numpy()
    if len(v)>=3:
        y_sm[idx] = np.convolve(v, kernel, mode="same")
y_main = np.maximum(0, y_sm)

# Safe variant: clamp to TRAIN global 1–99th percentiles
train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
q1, q99 = float(train_df.query("role=='target'")["meter_reading"].quantile(0.01)), \
          float(train_df.query("role=='target'")["meter_reading"].quantile(0.99))
y_safe = np.clip(y_main, 0.95*q1, 1.05*q99)

# Write files (no NaNs)
sub1 = pd.DataFrame({"row_id": S["row_id"], "meter_reading": pd.Series(y_main).fillna(0)}).sort_values("row_id")
sub2 = pd.DataFrame({"row_id": S["row_id"], "meter_reading": pd.Series(y_safe).fillna(0)}).sort_values("row_id")

OUT1 = f"{DATA_DIR}/submission_meta_wlgbm.csv"
OUT2 = f"{DATA_DIR}/submission_meta_wlgbm_safe.csv"
sub1.to_csv(OUT1, index=False); sub2.to_csv(OUT2, index=False)
print("Wrote:", OUT1, "and", OUT2, "| rows:", len(sub1))

Wrote: /content/drive/My Drive/IISC_data/submission_meta_wlgbm.csv and /content/drive/My Drive/IISC_data/submission_meta_wlgbm_safe.csv | rows: 84600

In [ ]:
# --- Isotonic meta-calibration on TRAIN (fixed for string building_id) ---
import pandas as pd, numpy as np
from sklearn.isotonic import IsotonicRegression

DATA_DIR = "/content/drive/My Drive/IISC_data"

alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

# Prereqs:
# feat_tr (has columns: building_id, window_id, timestamp, h_offset, ytrue, y_hod)
# pred_ttm_tr: ['window_id','timestamp','y_ttm']
# pred_tr:     ['window_id','h_offset','yhat_lgbm']
assert 'feat_tr' in globals(), "feat_tr missing. Run your meta-frame step first."

# Fallbacks if not in memory
if 'pred_ttm_tr' not in globals():
    print("Warning: pred_ttm_tr missing; using HoD as TTM fallback.")
    pred_ttm_tr = feat_tr[["window_id","timestamp","y_hod"]].rename(columns={"y_hod":"y_ttm"})
if 'pred_tr' not in globals():
    pred_tr = pd.read_parquet(f"{DATA_DIR}/pred_tr_lgbm.parquet")

# Keep building_id as STRING everywhere
feat_tr["building_id"] = feat_tr["building_id"].astype(str)
pred_tr = pred_tr.copy(); pred_tr["h_offset"] = pred_tr["h_offset"].astype(int)

W_LGBM = 0.20  # match in TEST

t = (feat_tr[["building_id","window_id","h_offset","timestamp","ytrue","y_hod"]]
     .merge(pred_ttm_tr.rename(columns={"y_ttm":"y_ttm_tr"}), on=["window_id","timestamp"], how="left")
     .merge(pred_tr.rename(columns={"yhat_lgbm":"y_lgbm_tr"}), on=["window_id","h_offset"], how="left")
     .merge(alpha_table, on=["building_id","h_offset"], how="left")
     .merge(bias_table,  on=["building_id","h_offset"], how="left"))

t[["alpha","bias"]] = t[["alpha","bias"]].fillna(0.0)
t["y_ttm_tr"] = pd.to_numeric(t["y_ttm_tr"], errors="coerce").fillna(t["y_hod"])
t["y_lgbm_tr"]= pd.to_numeric(t["y_lgbm_tr"],errors="coerce").fillna(t["y_hod"])

t["y_base_tr"] = (t["alpha"]*t["y_ttm_tr"] + (1.0-t["alpha"])*t["y_hod"] + t["bias"]).clip(lower=0)
t["y_pred_tr"] = np.clip((1.0-W_LGBM)*t["y_base_tr"] + W_LGBM*t["y_lgbm_tr"], 0, None)

# --- Fit isotonic per (building,h_offset) with shrinkage + fallbacks ---
MIN_N_BH = 180
MIN_N_B   = 800
SHR_K     = 600

calib_bh = {}  # key: (building_id:str, h:int) -> (iso_model, rho)
calib_b  = {}  # key: building_id:str -> (iso_model, rho)

iso_global = IsotonicRegression(out_of_bounds="clip")
mask = t[["y_pred_tr","ytrue"]].dropna().index
iso_global.fit(t.loc[mask,"y_pred_tr"], t.loc[mask,"ytrue"])

for (bid, hoff), g in t.dropna(subset=["y_pred_tr","ytrue"]).groupby(["building_id","h_offset"], sort=False):
    n = len(g)
    if n >= MIN_N_BH:
        ir = IsotonicRegression(out_of_bounds="clip")
        ir.fit(g["y_pred_tr"].to_numpy(), g["ytrue"].to_numpy())
        rho = n / (n + SHR_K)
        calib_bh[(str(bid), int(hoff))] = (ir, float(rho))

for bid, g in t.dropna(subset=["y_pred_tr","ytrue"]).groupby("building_id", sort=False):
    n = len(g)
    if n >= MIN_N_B:
        ir = IsotonicRegression(out_of_bounds="clip")
        ir.fit(g["y_pred_tr"].to_numpy(), g["ytrue"].to_numpy())
        rho = n / (n + SHR_K)
        calib_b[str(bid)] = (ir, float(rho))

# Quantile bands for later clipping
q_bh = (t.groupby(["building_id","h_offset"])["ytrue"].quantile([0.01,0.99]).unstack(-1)
          .rename(columns={0.01:"q01",0.99:"q99"}).reset_index())
q_b  = (t.groupby("building_id")["ytrue"].quantile([0.01,0.99]).unstack(-1)
          .rename(columns={0.01:"q01_b",0.99:"q99_b"}).reset_index())
qg01, qg99 = float(t["ytrue"].quantile(0.01)), float(t["ytrue"].quantile(0.99))

print("Calibrators:", len(calib_bh), "per-(building,h),", len(calib_b), "per-building, global OK.")

Calibrators: 936 per-(building,h), 49 per-building, global OK.

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])
def add_hoffset(df):
    out = df.sort_values(["window_id","timestamp"]).copy()
    out["h_offset"] = out.groupby("window_id").cumcount()
    return out

targets = add_hoffset(test_df.query("role=='target'")[["row_id","window_id","building_id","timestamp"]].copy())
targets["building_id"] = targets["building_id"].astype(str)
targets["h_offset"] = targets["h_offset"].astype(int)

sub_hod = pd.read_csv(f"{DATA_DIR}/submission_hod.csv").rename(columns={"meter_reading":"y_hod"})
sub_ttm = pd.read_csv(f"{DATA_DIR}/submission_ttm.csv").rename(columns={"meter_reading":"y_ttm"})
sub_lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").rename(columns={"meter_reading_lgbm":"y_lgbm"})
alpha_table = pd.read_parquet(f"{DATA_DIR}/alpha_table_cf.parquet")
bias_table  = pd.read_parquet(f"{DATA_DIR}/bias_table_cf.parquet")

S = (targets.merge(sub_hod, on="row_id", how="left")
            .merge(sub_ttm, on="row_id", how="left")
            .merge(sub_lgb, on="row_id", how="left")
            .merge(alpha_table, on=["building_id","h_offset"], how="left")
            .merge(bias_table,  on=["building_id","h_offset"], how="left"))

S["alpha"] = S["alpha"].fillna(0.0)
S["bias"]  = S["bias"].fillna(0.0)
S["y_hod"]  = pd.to_numeric(S["y_hod"], errors="coerce").fillna(0)
S["y_ttm"]  = pd.to_numeric(S["y_ttm"], errors="coerce").fillna(S["y_hod"])
S["y_lgbm"] = pd.to_numeric(S["y_lgbm"], errors="coerce").fillna(S["y_hod"])

# Base + the exact same 20% LGBM mixing used on TRAIN
W_LGBM = 0.20
y_base = (S["alpha"]*S["y_ttm"] + (1.0-S["alpha"])*S["y_hod"] + S["bias"]).clip(lower=0)
y_pred = np.clip((1.0-W_LGBM)*y_base + W_LGBM*S["y_lgbm"], 0, None)

# Apply isotonic per (building,h) with shrinkage fallbacks
def apply_iso_series(df, y):
    y = y.to_numpy().astype(float)
    out = np.empty_like(y)
    bids = df["building_id"].astype(str).to_numpy()
    hoffs= df["h_offset"].astype(int).to_numpy()
    for i in range(len(y)):
        key = (bids[i], hoffs[i])
        if key in calib_bh:
            ir, rho = calib_bh[key]
        elif bids[i] in calib_b:
            ir, rho = calib_b[bids[i]]
        else:
            ir, rho = iso_global, 0.15  # tiny default shrink
        yhat = float(ir.predict([y[i]])[0])
        out[i] = (1.0 - rho) * y[i] + rho * yhat
    return pd.Series(out, index=df.index)

y_cal = apply_iso_series(S, pd.Series(y_pred))

# Gentle horizon smoothing per window
kernel = np.array([0.2,0.6,0.2])
y_sm = y_cal.to_numpy()
for _, idx in S.groupby("window_id").indices.items():
    v = y_cal.iloc[idx].to_numpy()
    if len(v)>=3:
        y_sm[idx] = np.convolve(v, kernel, mode="same")
y_sm = np.clip(y_sm, 0, None)

# Quantile bands with fallbacks
q_bh = q_bh.copy(); q_b = q_b.copy()  # from previous cell
S2 = (S.merge(q_bh, on=["building_id","h_offset"], how="left")
        .merge(q_b, on="building_id", how="left"))
qlo = S2["q01"].fillna(S2["q01_b"]).fillna(qg01)
qhi = S2["q99"].fillna(S2["q99_b"]).fillna(qg99)

# Main (tight) and safe (looser) clips
y_main  = np.clip(y_sm, 0.98*qlo.to_numpy(), 1.02*qhi.to_numpy())
y_safe  = np.clip(y_sm, 0.95*qlo.to_numpy(), 1.05*qhi.to_numpy())

# No-NaN guard
sub_main = pd.DataFrame({"row_id": S["row_id"], "meter_reading": pd.Series(y_main).fillna(0).clip(lower=0)})
sub_safe = pd.DataFrame({"row_id": S["row_id"], "meter_reading": pd.Series(y_safe).fillna(0).clip(lower=0)})

OUT1 = f"{DATA_DIR}/submission_iso_stack.csv"
OUT2 = f"{DATA_DIR}/submission_iso_stack_loose.csv"
sub_main.sort_values("row_id").to_csv(OUT1, index=False)
sub_safe.sort_values("row_id").to_csv(OUT2, index=False)
print("Wrote:", OUT1, "and", OUT2, "| rows:", len(sub_main))

Wrote: /content/drive/My Drive/IISC_data/submission_iso_stack.csv and /content/drive/My Drive/IISC_data/submission_iso_stack_loose.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load median-top and LGBM preds
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
# Handle either column name
if "meter_reading_lgbm" in lgb.columns:
    lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"})
else:
    lgb = lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.rename(columns={"meter_reading":"m_med"}).merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])
df["m_med"]  = pd.to_numeric(df["m_med"],  errors="coerce").fillna(0)

# Get horizon per row for horizon-aware weighting
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", parse_dates=["timestamp"])
tgt = (test_df.query("role=='target'")[["row_id","window_id","timestamp"]]
       .sort_values(["window_id","timestamp"]))
tgt["h_offset"] = tgt.groupby("window_id").cumcount()
df = df.merge(tgt[["row_id","h_offset"]], on="row_id", how="left")

def write(name, y):
    y = pd.to_numeric(y, errors="coerce").fillna(df["m_med"]).clip(lower=0)
    out = df[["row_id"]].copy(); out["meter_reading"] = y
    path = f"{DATA_DIR}/{name}.csv"
    out.sort_values("row_id").to_csv(path, index=False)
    print("Wrote:", path, "| rows:", len(out))
    return path

# 1) Horizon-aware schedule: more LGBM early, less later (safe decay)
h = df["h_offset"].to_numpy(float)
w0, w_end, tau = 0.28, 0.12, 8.0
w_h = w_end + (w0 - w_end) * np.exp(-h / tau)
y_sched = (1.0 - w_h) * df["m_med"] + w_h * df["m_lgbm"]
p_sched = write("submission_med_lgbm_hsched_tau8", y_sched)

# 2–4) Uniform weights around your 0.20 best
for w in (0.22, 0.24, 0.18):
    y = (1.0 - w) * df["m_med"] + w * df["m_lgbm"]
    write(f"submission_med_lgbm_w{int(round(w*100)):02d}", y)

# 5) Power-mean (p=0.5) to tame extremes (weights 0.8 med / 0.2 lgbm)
p = 0.5
y_pm = ((0.8 * np.power(np.clip(df["m_med"], 0, None), p) +
         0.2 * np.power(np.clip(df["m_lgbm"], 0, None), p)) / 1.0) ** (1.0/p)
write("submission_med_lgbm_power05", y_pm)

Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_hsched_tau8.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w22.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w24.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w18.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_power05.csv | rows: 84600

'/content/drive/My Drive/IISC_data/submission_med_lgbm_power05.csv'

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
if "meter_reading_lgbm" in lgb.columns:
    lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"})
else:
    lgb = lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.rename(columns={"meter_reading":"m_med"}).merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])
df["m_med"]  = pd.to_numeric(df["m_med"],  errors="coerce").fillna(0)

w = 0.23
out = df[["row_id"]].copy()
out["meter_reading"] = ((1-w)*df["m_med"] + w*df["m_lgbm"]).clip(lower=0)
out.to_csv(f"{DATA_DIR}/submission_med_lgbm_w23.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_med_lgbm_w23.csv")

Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w23.csv

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"
K = 15           # neighbors per building
TEMP = 0.15      # softmax temperature (lower = peakier)
EPS = 1e-8

train_df = pd.read_csv(f"{DATA_DIR}/train.csv", parse_dates=["timestamp"])
test_df  = pd.read_csv(f"{DATA_DIR}/test.csv",  parse_dates=["timestamp"])

# Helper: pack last-168h inputs into a fixed-length vector
def pack_inputs(df):
    g = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"])["meter_reading"]
           .apply(lambda s: s.tail(168).to_numpy(np.float32)))
    # keep only vectors of length 168
    g = g[g.map(len)==168]
    X = np.vstack(g.values)
    keys = list(g.index)
    return keys, X

# Helper: pack 24h targets in time order + row_id map for test
def pack_targets_train(df):
    t = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"])["meter_reading"]
           .apply(lambda s: s.to_numpy(np.float32)))
    t = t[t.map(len)==24]
    Y = np.vstack(t.values)
    keys = list(t.index)
    return keys, Y

def pack_targets_test(df):
    t = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"])
           .apply(lambda g: (g["row_id"].to_numpy(np.int64),
                             g["timestamp"].to_numpy())))
    keys, rows = [], []
    for k, (row_ids, ts) in t.items():
        if len(row_ids)==24:
            keys.append(k); rows.append(row_ids)
    R = np.vstack(rows)
    return keys, R

# Build per-building dictionaries
inp_tr = train_df.query("role=='input'")
tgt_tr = train_df.query("role=='target'")
inp_te = test_df.query("role=='input'")
tgt_te = test_df.query("role=='target'")

keys_Xtr, Xtr_all = pack_inputs(inp_tr)
keys_Ytr, Ytr_all = pack_targets_train(tgt_tr)
keys_Xte, Xte_all = pack_inputs(inp_te)
keys_Rte, Rte_all = pack_targets_test(tgt_te)

# Map keys -> rows
from collections import defaultdict
b_tr_X, b_tr_Y, b_te_X, b_te_R = defaultdict(list), defaultdict(list), defaultdict(list), defaultdict(list)

for (b,w), x in zip(keys_Xtr, Xtr_all):
    b_tr_X[str(b)].append((w, x))
for (b,w), y in zip(keys_Ytr, Ytr_all):
    b_tr_Y[str(b)].append((w, y))
for (b,w), x in zip(keys_Xte, Xte_all):
    b_te_X[str(b)].append((w, x))
for (b,w), r in zip(keys_Rte, Rte_all):
    b_te_R[str(b)].append((w, r))

# Make per-building aligned matrices
def to_mat(pairs):
    ws = [w for w,_ in pairs]
    M  = np.vstack([v for _,v in pairs]).astype(np.float32)
    return ws, M

pred_rows, pred_vals = [], []

for b in sorted(b_te_X.keys()):
    if b not in b_tr_X or b not in b_tr_Y:  # no training for this building
        continue

    ws_trX, Xtr = to_mat(b_tr_X[b])
    ws_trY, Ytr = to_mat(b_tr_Y[b])
    ws_teX, Xte = to_mat(b_te_X[b])
    ws_teR, Rte = to_mat(b_te_R[b])

    # align Xtr and Ytr by window_id
    idx = {w:i for i,w in enumerate(ws_trX)}
    keep = [(j, idx[w]) for j,w in enumerate(ws_trY) if w in idx]
    if not keep:
        continue
    jY, iX = zip(*keep)
    Xtr = Xtr[list(iX)]
    Ytr = Ytr[list(jY)]

    # normalize to unit L2 for cosine similarity
    Xtr_n = Xtr / (np.linalg.norm(Xtr, axis=1, keepdims=True) + EPS)
    Xte_n = Xte / (np.linalg.norm(Xte, axis=1, keepdims=True) + EPS)

    # similarity per building via matrix-mul
    S = Xte_n @ Xtr_n.T   # [n_te, n_tr]
    n_te = S.shape[0]

    for j in range(n_te):
        s = S[j]
        # top-K neighbors
        k = min(K, s.size)
        idx_top = np.argpartition(s, -k)[-k:]
        sims = s[idx_top]
        # softmax weights
        w = np.exp(sims / TEMP); w = w / (w.sum() + EPS)
        yhat = (w[:,None] * Ytr[idx_top]).sum(axis=0)  # 24-length
        # attach row_ids in timestamp order
        row_ids = Rte[j]
        pred_rows.append(row_ids)
        pred_vals.append(np.clip(yhat, 0, None))

# Assemble submission from kNN
row_ids_all = np.concatenate(pred_rows, axis=0)
vals_all    = np.concatenate(pred_vals, axis=0)
sub_knn = pd.DataFrame({"row_id": row_ids_all, "meter_reading": vals_all}).sort_values("row_id").reset_index(drop=True)
knn_path = f"{DATA_DIR}/submission_knn_building.csv"
sub_knn.to_csv(knn_path, index=False)
print("Wrote:", knn_path, "| rows:", len(sub_knn))

/tmp/ipython-input-2843449182.py:35: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: (g["row_id"].to_numpy(np.int64),

Wrote: /content/drive/My Drive/IISC_data/submission_knn_building.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
if "meter_reading_lgbm" in lgb.columns:
    lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"})
else:
    lgb = lgb.rename(columns={"meter_reading":"m_lgbm"})
knn = pd.read_csv(f"{DATA_DIR}/submission_knn_building.csv").sort_values("row_id").rename(columns={"meter_reading":"m_knn"})

df = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left") \
        .merge(knn[["row_id","m_knn"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])
df["m_knn"]  = pd.to_numeric(df["m_knn"],  errors="coerce").fillna(df["m_med"])

def write(name, y):
    y = pd.to_numeric(y, errors="coerce").fillna(df["m_med"]).clip(lower=0)
    out = df[["row_id"]].copy(); out["meter_reading"] = y
    path = f"{DATA_DIR}/{name}.csv"
    out.to_csv(path, index=False)
    print("Wrote:", path, "| rows:", len(out))
    return path

# Aggressive: 0.70 med + 0.20 lgbm + 0.10 knn
y_aggr = 0.70*df["m_med"] + 0.20*df["m_lgbm"] + 0.10*df["m_knn"]
p1 = write("submission_knn_blend_70_20_10", y_aggr)

# Safer: 0.75 / 0.20 / 0.05
y_safe = 0.75*df["m_med"] + 0.20*df["m_lgbm"] + 0.05*df["m_knn"]
p2 = write("submission_knn_blend_75_20_05", y_safe)

Wrote: /content/drive/My Drive/IISC_data/submission_knn_blend_70_20_10.csv | rows: 84600
Wrote: /content/drive/My Drive/IISC_data/submission_knn_blend_75_20_05.csv | rows: 84600

In [ ]:
import pandas as pd, numpy as np
DATA_DIR = "/content/drive/My Drive/IISC_data"

med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.rename(columns={"meter_reading":"m_med"}).merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])
y = ((1-0.23)*df["m_med"] + 0.23*df["m_lgbm"]).clip(lower=0)

out = df[["row_id"]].copy(); out["meter_reading"] = y
out.to_csv(f"{DATA_DIR}/submission_med_lgbm_w23_resave.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_med_lgbm_w23_resave.csv")

Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w23_resave.csv

In [ ]:
import pandas as pd, numpy as np
DATA_DIR = "/content/drive/My Drive/IISC_data"

med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id")
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.rename(columns={"meter_reading":"m_med"}).merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])

w = 0.235
y = ((1-w)*df["m_med"] + w*df["m_lgbm"]).clip(lower=0)
out = df[["row_id"]].copy(); out["meter_reading"] = y
out.to_csv(f"{DATA_DIR}/submission_med_lgbm_w235.csv", index=False)
print("Wrote:", f"{DATA_DIR}/submission_med_lgbm_w235.csv")

Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w235.csv

In [ ]:
import numpy as np, pandas as pd

EPS = 1e-8

def robust_standardize(x):
    # x: (168,) → shape-only vector
    med = np.median(x)
    mad = np.median(np.abs(x - med)) + 1e-6
    return (x - med) / mad

def day_chunks_7(x168):
    # returns list of 7 day sums and 7 day vectors (each 24,)
    days = [x168[i*24:(i+1)*24] for i in range(7)]
    return [d.sum() for d in days], days

def sum_preserving_smooth24(y):
    # 3-tap smoothing with mirrored edges, then re-match the sum
    y = y.astype(np.float32)
    s_old = float(y.sum())
    z = y.copy()
    for h in range(24):
        left  = z[h-1] if h>0 else z[1]
        mid   = z[h]
        right = z[h+1] if h<23 else z[22]
        y[h]  = 0.25*left + 0.5*mid + 0.25*right
    s_new = float(y.sum()) + EPS
    return y * (s_old / s_new)

In [ ]:
import pandas as pd, numpy as np

DATA_DIR = "/content/drive/My Drive/IISC_data"  # adjust if needed

# Read with stable dtypes
train_cols = ["building_id","window_id","timestamp","meter_reading","role"]
test_cols  = ["row_id","building_id","window_id","timestamp","meter_reading","role"]

train_df = pd.read_csv(
    f"{DATA_DIR}/train.csv",
    usecols=train_cols,
    parse_dates=["timestamp"],
    dtype={"building_id": "string", "window_id": "int32", "role": "category"},
    low_memory=False,
)

test_df = pd.read_csv(
    f"{DATA_DIR}/test.csv",
    usecols=test_cols,
    parse_dates=["timestamp"],
    dtype={"row_id": "int64", "building_id": "string", "window_id": "int32", "role": "category"},
    low_memory=False,
)

# quick sanity
assert {"input","target"}.issubset(set(train_df["role"].astype(str))), "roles missing in train"
assert {"input","target"}.issubset(set(test_df["role"].astype(str))),  "roles missing in test"

In [ ]:
# Build base splits
inp_tr = train_df.query("role=='input'")
tgt_tr = train_df.query("role=='target'")
inp_te = test_df.query("role=='input'")
tgt_te = test_df.query("role=='target'")

keys_Xtr, Xtr_all, Xtr_last_ts   = pack_inputs_with_ts(inp_tr)
keys_Ytr, Ytr_all, Ytr_TS        = pack_targets_train_with_ts(tgt_tr)
keys_Xte, Xte_all, Xte_last_ts   = pack_inputs_with_ts(inp_te)
keys_Rte, Rte_all, Rte_TS        = pack_targets_test_with_ts(tgt_te)

In [ ]:
# === 1) SETUP & LOAD ===
import numpy as np, pandas as pd

pd.options.mode.chained_assignment = None

DATA_DIR = "/content/drive/My Drive/IISC_data"  # change if needed

train_cols = ["building_id","window_id","timestamp","meter_reading","role"]
test_cols  = ["row_id","building_id","window_id","timestamp","meter_reading","role"]

train_df = pd.read_csv(
    f"{DATA_DIR}/train.csv",
    usecols=train_cols,
    parse_dates=["timestamp"],
    dtype={"building_id": "string", "window_id": "int32", "role": "category"},
    low_memory=False,
)
test_df = pd.read_csv(
    f"{DATA_DIR}/test.csv",
    usecols=test_cols,
    parse_dates=["timestamp"],
    dtype={"row_id": "int64", "building_id": "string", "window_id": "int32", "role": "category"},
    low_memory=False,
)

# Quick sanity
assert {"input","target"}.issubset(set(train_df["role"].astype(str)))
assert {"input","target"}.issubset(set(test_df["role"].astype(str)))

print("Loaded:", train_df.shape, test_df.shape)

Loaded: (2582976, 5) (676800, 6)

In [ ]:
# === 2) UTILITIES ===
EPS = 1e-8

def robust_standardize(x: np.ndarray) -> np.ndarray:
    """Shape-only standardization: median/MAD (robust to level outliers)."""
    med = np.median(x)
    mad = np.median(np.abs(x - med)) + 1e-6
    return (x - med) / mad

def day_chunks_7(x168: np.ndarray):
    """Split 168h into 7x24; return (day_sums, list_of_24h_arrays)."""
    days = [x168[i*24:(i+1)*24] for i in range(7)]
    return [float(d.sum()) for d in days], days

def sum_preserving_smooth24(y: np.ndarray) -> np.ndarray:
    """3-tap smoothing with mirrored edges, preserving 24h sum."""
    y = y.astype(np.float32)
    s_old = float(y.sum())
    z = y.copy()
    out = y.copy()
    for h in range(24):
        left  = z[h-1] if h>0 else z[1]
        mid   = z[h]
        right = z[h+1] if h<23 else z[22]
        out[h]  = 0.25*left + 0.5*mid + 0.25*right
    s_new = float(out.sum()) + EPS
    return out * (s_old / s_new)

In [ ]:
# === 3) PACKING HELPERS (robust to timestamp dtype) ===
def pack_inputs_with_ts(df: pd.DataFrame):
    g = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"]))
    X, last_ts, keys = [], [], []
    for (b,w), gi in g:
        ts = pd.to_datetime(gi["timestamp"], errors="coerce")
        v = gi["meter_reading"].tail(168).to_numpy(np.float32)
        if len(v)==168:
            X.append(v)
            last_ts.append(ts.max())              # last observed hour
            keys.append((str(b), int(w)))
    return keys, np.vstack(X), np.array(last_ts, dtype="datetime64[ns]")

def pack_targets_train_with_ts(df: pd.DataFrame):
    g = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"]))
    Y, TS, keys = [], [], []
    for (b,w), gi in g:
        ts = pd.to_datetime(gi["timestamp"], errors="coerce").to_numpy()
        v  = gi["meter_reading"].to_numpy(np.float32)
        if len(v)==24:
            Y.append(v); TS.append(ts); keys.append((str(b), int(w)))
    return keys, np.vstack(Y), TS

def pack_targets_test_with_ts(df: pd.DataFrame):
    g = (df.sort_values(["window_id","timestamp"])
           .groupby(["building_id","window_id"]))
    R, TS, keys = [], [], []
    for (b,w), gi in g:
        ts = pd.to_datetime(gi["timestamp"], errors="coerce").to_numpy()
        rid = gi["row_id"].to_numpy(np.int64)
        if len(rid)==24:
            keys.append((str(b), int(w))); R.append(rid); TS.append(ts)
    return keys, np.vstack(R), TS

In [ ]:
# === 4) BUILD SPLITS & ALIGN ===
inp_tr = train_df.query("role=='input'")
tgt_tr = train_df.query("role=='target'")
inp_te = test_df.query("role=='input'")
tgt_te = test_df.query("role=='target'")

keys_Xtr, Xtr_all, Xtr_last_ts = pack_inputs_with_ts(inp_tr)
keys_Ytr, Ytr_all, Ytr_TS      = pack_targets_train_with_ts(tgt_tr)
keys_Xte, Xte_all, Xte_last_ts = pack_inputs_with_ts(inp_te)
keys_Rte, Rte_all, Rte_TS      = pack_targets_test_with_ts(tgt_te)

# Align Xtr (168) with Ytr (24) by (building, window)
idx_Xtr = {k:i for i,k in enumerate(keys_Xtr)}
keep = [(j, idx_Xtr[k]) for j,k in enumerate(keys_Ytr) if k in idx_Xtr]
if not keep:
    raise RuntimeError("No overlapping (building,window) between Xtr and Ytr")

jY, iX = zip(*keep)
Xtr = Xtr_all[list(iX)]
Ytr = Ytr_all[list(jY)]
Ytr_ts = [Ytr_TS[j] for j in jY]
Ytr_b  = [keys_Ytr[j][0] for j in jY]  # building ids aligned

print("Aligned train windows:", Xtr.shape, Ytr.shape)

Aligned train windows: (13453, 168) (13453, 24)

In [ ]:
# === 5) BIAS TABLE (bld × HOD) + SAFE CAPS ===
from collections import defaultdict

# Weekly-copy pseudo-forecast: first 24h from last-168
WC  = np.stack([x[:24] for x in Xtr], axis=0)   # 24
RES = Ytr - WC                                  # residuals

bias_table = defaultdict(dict)   # bias_table[bld][hour] = mean residual
cap_table  = {}                  # cap per building (p99.7 of true)

for b in np.unique(Ytr_b):
    mask = np.array([bb==b for bb in Ytr_b], dtype=bool)
    yb   = Ytr[mask]          # [n_win_b, 24]
    wb   = RES[mask]          # [n_win_b, 24]
    tsb  = np.array(Ytr_ts, dtype=object)[mask]  # list of arrays (timestamps)

    # hour-of-day bias, robust to dtype
    hod_vals, res_vals = [], []
    for win_idx in range(wb.shape[0]):
        ts_vec = pd.to_datetime(tsb[win_idx], errors="coerce")
        valid = ~pd.isna(ts_vec)
        if valid.any():
            hod = ts_vec[valid].hour.to_numpy(dtype=np.int16)
            res = wb[win_idx][valid]
            hod_vals.append(hod)
            res_vals.append(res)
    if len(hod_vals):
        hod_vals = np.concatenate(hod_vals)
        res_vals = np.concatenate(res_vals)
    else:
        hod_vals = np.array([], dtype=np.int16)
        res_vals = np.array([], dtype=np.float32)

    for h in range(24):
        m = (hod_vals==h)
        bias_table[b][h] = float(res_vals[m].mean()) if m.any() else 0.0

    # building cap
    cap_table[b] = float(np.quantile(yb.flatten(), 0.997))

print("Bias/cap tables built for buildings:", len(cap_table))

Bias/cap tables built for buildings: 91

In [ ]:
# === 6) IMPROVED KNN (shape sim + weekend parity + energy recalib + sim floor) ===
from collections import defaultdict

# Group per building for fast access
b_tr_X  = defaultdict(list)  # (w, x168, last_ts)
b_tr_YT = defaultdict(list)  # (w, y24, first_target_ts, is_weekend)
b_te_XR = defaultdict(list)  # (w, x168, row_ids24, first_target_ts, is_weekend)

for (b,w), x, ts_last in zip(keys_Xtr, Xtr_all, Xtr_last_ts):
    b_tr_X[str(b)].append((w, x, ts_last))

for (b,w), y, ts in zip(keys_Ytr, Ytr_all, Ytr_TS):
    ts0 = pd.to_datetime(ts, errors="coerce")[0]
    weekend = (ts0.weekday()>=5) if pd.notna(ts0) else False
    b_tr_YT[str(b)].append((w, y, ts0, weekend))

for (b,w), x, rid, ts in zip(keys_Xte, Xte_all, Rte_all, Rte_TS):
    ts_arr = pd.to_datetime(ts, errors="coerce")
    ts0 = ts_arr[0] if len(ts_arr) else pd.NaT
    weekend = (ts0.weekday()>=5) if pd.notna(ts0) else False
    b_te_XR[str(b)].append((w, x, rid, ts0, weekend))

# KNN params (safe defaults)
K_GLOBAL = 9
TEMP_GLOBAL = 0.12
SIM_FLOOR = 0.50

pred_rows, pred_vals = [], []

for b in sorted(b_te_XR.keys()):
    if b not in b_tr_X or b not in b_tr_YT:
        continue

    # Build aligned train matrices for this building
    trX_pairs = {w:(x,ts_last) for (w,x,ts_last) in b_tr_X[b]}
    trY_list  = []
    for (w,y,ts0,weekend) in b_tr_YT[b]:
        if w in trX_pairs:
            x, ts_last = trX_pairs[w]
            trY_list.append((w, x, y, ts0, weekend))
    if not trY_list:
        continue

    ws_tr = [w for (w,_,_,_,_) in trY_list]
    Xtr_b = np.vstack([x for (_,x,_,_,_) in trY_list]).astype(np.float32)
    Ytr_b = np.vstack([y for (_,_,y,_,_) in trY_list]).astype(np.float32)
    Ytr_weekend = np.array([wk for (_,_,_,_,wk) in trY_list], dtype=bool)

    # Shape-only standardization for similarity
    Xtr_std = np.vstack([robust_standardize(x) for x in Xtr_b])
    Xtr_std = Xtr_std / (np.linalg.norm(Xtr_std, axis=1, keepdims=True) + EPS)

    for (wte, xte, rid24, ts0, is_weekend) in b_te_XR[b]:
        # std + cosine sim
        xte_std = robust_standardize(xte)
        xte_std = xte_std / (np.linalg.norm(xte_std) + EPS)

        # weekend parity filter (ensure minimum pool size)
        mask = (Ytr_weekend == is_weekend)
        if mask.sum() < 200:  # relax if thin
            mask = np.ones_like(Ytr_weekend, dtype=bool)

        S = (Xtr_std[mask] @ xte_std)           # cosine similarities
        k = min(K_GLOBAL, S.size)
        if k == 0:
            # no neighbors; fallback to weekly copy
            yhat = xte[:24].astype(np.float32)
        else:
            idx_top = np.argpartition(S, -k)[-k:]
            sims = S[idx_top]
            s_max = float(sims.max()) if sims.size else 0.0

            if s_max < SIM_FLOOR:
                yhat = xte[:24].astype(np.float32)
            else:
                wts = np.exp(sims / TEMP_GLOBAL)
                wts = wts / (wts.sum() + EPS)
                yhat = (wts[:,None] * Ytr_b[mask][idx_top]).sum(axis=0).astype(np.float32)

        # Day-sum recalibration (match expected energy safely)
        dsums, days = day_chunks_7(xte)
        target_sum = float(dsums[0]) if len(dsums)==7 else float(np.median(dsums))
        scale = np.clip(target_sum / (float(yhat.sum()) + EPS), 0.7, 1.3)
        yhat = np.clip(yhat * scale, 0, None)

        pred_rows.append(rid24)
        pred_vals.append(yhat)

sub_knn = pd.DataFrame({
    "row_id": np.concatenate(pred_rows),
    "meter_reading": np.concatenate(pred_vals).astype(np.float32)
}).sort_values("row_id").reset_index(drop=True)

knn_path = f"{DATA_DIR}/submission_knn_improved.csv"
sub_knn.to_csv(knn_path, index=False)
print("Wrote:", knn_path, "| rows:", len(sub_knn))

Wrote: /content/drive/My Drive/IISC_data/submission_knn_improved.csv | rows: 84600

In [ ]:
# === 7) LOAD BASE SUBMISSIONS & HOUR-GATED BLEND ===
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})
knn = pd.read_csv(f"{DATA_DIR}/submission_knn_improved.csv").sort_values("row_id").rename(columns={"meter_reading":"m_knn"})

base = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left") \
          .merge(knn[["row_id","m_knn"]],  on="row_id", how="left")

# Map row_id -> (building_id, hod) from test targets
meta_te = (tgt_te[["row_id","building_id","timestamp"]]
           .dropna()
           .sort_values("row_id"))
meta_te["hod"] = pd.to_datetime(meta_te["timestamp"], errors="coerce").dt.hour

dfb = base.merge(meta_te[["row_id","building_id","hod"]], on="row_id", how="left")
dfb["m_lgbm"] = pd.to_numeric(dfb["m_lgbm"], errors="coerce").fillna(dfb["m_med"])
dfb["m_knn"]  = pd.to_numeric(dfb["m_knn"],  errors="coerce").fillna(dfb["m_med"])

def weights_for_hod(h: int):
    # heuristic gates: adjust if your CV shows different regimes
    if 0 <= h <= 5:      # night
        return 0.55, 0.35, 0.10   # MED, LGBM, KNN
    elif 6 <= h <= 11:   # morning ramp
        return 0.35, 0.55, 0.10
    elif 12 <= h <= 17:  # afternoon
        return 0.60, 0.30, 0.10
    else:                # evening ramp
        return 0.35, 0.55, 0.10

hod = dfb["hod"].fillna(12).astype(int).to_numpy()
wM = np.empty_like(hod, dtype=np.float32)
wL = np.empty_like(hod, dtype=np.float32)
wK = np.empty_like(hod, dtype=np.float32)
for i, h in enumerate(hod):
    m,l,k = weights_for_hod(h)
    wM[i], wL[i], wK[i] = m,l,k

y_blend = (wM*dfb["m_med"].values + wL*dfb["m_lgbm"].values + wK*dfb["m_knn"].values).astype(np.float32)
dfb["y_blend"] = np.clip(y_blend, 0, None)

In [ ]:
# === 8) POST-PROCESS PER (BUILDING, WINDOW): BIAS -> SMOOTH -> CAP -> CLIP ===
rows_pp, vals_pp = [], []

g = (tgt_te.sort_values(["building_id","window_id","timestamp"])
            .groupby(["building_id","window_id"]))

for (b,w), gi in g:
    b = str(b)
    rows  = gi["row_id"].to_numpy()
    ts24  = pd.to_datetime(gi["timestamp"], errors="coerce")
    hod24 = ts24.dt.hour.to_numpy(dtype=np.int16)

    y     = dfb.loc[dfb["row_id"].isin(rows), "y_blend"].to_numpy(dtype=np.float32)

    # 1) subtract train-time bias[b][hod]
    if b in bias_table:
        bias_vec = np.array([bias_table[b].get(int(h), 0.0) for h in hod24], dtype=np.float32)
        y = y - bias_vec

    # 2) smooth with sum preservation
    y = sum_preserving_smooth24(y)

    # 3) cap by building safe p99.7 (from train)
    cap = cap_table.get(b, np.float32(np.inf))
    y = np.minimum(y, cap)

    # 4) non-negativity
    y = np.clip(y, 0, None)

    rows_pp.append(rows)
    vals_pp.append(y)

pred_pp = pd.DataFrame({
    "row_id": np.concatenate(rows_pp),
    "meter_reading": np.concatenate(vals_pp).astype(np.float32)
}).sort_values("row_id").reset_index(drop=True)

final_path = f"{DATA_DIR}/submission_blend_biassmoothcap.csv"
pred_pp.to_csv(final_path, index=False)
print("Wrote:", final_path, "| rows:", len(pred_pp))

Wrote: /content/drive/My Drive/IISC_data/submission_blend_biassmoothcap.csv | rows: 84600

In [ ]:
# === 9) QUICK CHECK ===
assert pred_pp["row_id"].is_monotonic_increasing, "row_id not sorted"
assert pred_pp["meter_reading"].ge(0).all(), "negative predictions found"
print("OK: shape", pred_pp.shape, "| min/max", pred_pp["meter_reading"].min(), pred_pp["meter_reading"].max())

OK: shape (84600, 2) | min/max 0.0 7.143374443054199

In [ ]:
# === A) BASELINE: MED ⊕ LGBM (w=0.235) + SUM-PRESERVING SMOOTHING ===
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"  # adjust if needed

# If these aren't in memory already, (re)load test targets for grouping
try:
    test_df, tgt_te
except NameError:
    test_cols  = ["row_id","building_id","window_id","timestamp","meter_reading","role"]
    test_df = pd.read_csv(f"{DATA_DIR}/test.csv", usecols=test_cols, parse_dates=["timestamp"])
    tgt_te  = test_df.query("role=='target'").copy()

# Load your two base submissions
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"])

# Best known weight from your LB: w = 0.235 toward LGBM
W = 0.235
df["y_base"] = np.clip((1.0 - W) * df["m_med"].values + W * df["m_lgbm"].values, 0, None).astype(np.float32)

# Map row_id → (building_id, window_id, timestamp)
meta = (tgt_te[["row_id","building_id","window_id","timestamp"]]
        .dropna()
        .sort_values(["building_id","window_id","timestamp"]))
dfm = df.merge(meta, on="row_id", how="left")

# Sum-preserving 3-tap smoothing per (building, window)
def sum_preserving_smooth24(y):
    y = y.astype(np.float32)
    s_old = float(y.sum())
    z = y.copy()
    out = y.copy()
    for h in range(24):
        left  = z[h-1] if h>0 else z[1]
        mid   = z[h]
        right = z[h+1] if h<23 else z[22]
        out[h]  = 0.25*left + 0.5*mid + 0.25*right
    s_new = float(out.sum()) + 1e-8
    return out * (s_old / s_new)

pred_rows, pred_vals = [], []
for (_, _), gi in dfm.sort_values(["building_id","window_id","timestamp"]) \
                     .groupby(["building_id","window_id"]):
    rows = gi["row_id"].to_numpy()
    y    = gi["y_base"].to_numpy(dtype=np.float32)
    if len(y)==24:
        y = sum_preserving_smooth24(y)
    y = np.clip(y, 0, None)
    pred_rows.append(rows); pred_vals.append(y)

subA = pd.DataFrame({"row_id": np.concatenate(pred_rows),
                     "meter_reading": np.concatenate(pred_vals).astype(np.float32)}
                   ).sort_values("row_id").reset_index(drop=True)

pathA = f"{DATA_DIR}/submission_simple_smooth.csv"
subA.to_csv(pathA, index=False)
print("Wrote:", pathA, "| rows:", len(subA), "| min/max:", subA.meter_reading.min(), subA.meter_reading.max())

Wrote: /content/drive/My Drive/IISC_data/submission_simple_smooth.csv | rows: 84600 | min/max: 0.0 7.488582611083984

In [ ]:
# === B) GUARDED KNN: add tiny KNN weight only when it's trustworthy ===
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load the A) baseline (already smoothed) and KNN (improved) if available
base = pd.read_csv(f"{DATA_DIR}/submission_simple_smooth.csv").rename(columns={"meter_reading":"y_base"})
knn_path = f"{DATA_DIR}/submission_knn_improved.csv"
knn = pd.read_csv(knn_path).rename(columns={"meter_reading":"y_knn"})

# Row→(bld,win,ts) mapping
meta = tgt_te[["row_id","building_id","window_id","timestamp"]].copy()

dfg = (base.merge(knn, on="row_id", how="left")
           .merge(meta, on="row_id", how="left")
           .sort_values(["building_id","window_id","timestamp"]))

def cos_sim(a, b):
    a = a.astype(np.float32); b = b.astype(np.float32)
    na = np.linalg.norm(a); nb = np.linalg.norm(b)
    if na < 1e-8 or nb < 1e-8: return 0.0
    return float(a @ b / (na * nb))

rows_out, vals_out = [], []

for (b,w), gi in dfg.groupby(["building_id","window_id"]):
    rows = gi["row_id"].to_numpy()
    yb   = gi["y_base"].to_numpy(dtype=np.float32)
    yk   = gi["y_knn"].to_numpy(dtype=np.float32)

    # If KNN missing, keep baseline
    if len(yb) != 24 or np.isnan(yk).any():
        rows_out.append(rows); vals_out.append(yb); continue

    # Check agreement
    c = cos_sim(yb, yk)
    sum_ratio = float((yk.sum()+1e-6) / (yb.sum()+1e-6))

    # Trust KNN only if shape aligns and day sums are close
    if c >= 0.85 and 0.9 <= sum_ratio <= 1.1:
        w_knn = 0.08  # small, safe bump
    else:
        w_knn = 0.00

    y = (1.0 - w_knn) * yb + w_knn * yk
    y = np.clip(y, 0, None)
    rows_out.append(rows); vals_out.append(y)

subB = pd.DataFrame({"row_id": np.concatenate(rows_out),
                     "meter_reading": np.concatenate(vals_out).astype(np.float32)}
                   ).sort_values("row_id").reset_index(drop=True)

pathB = f"{DATA_DIR}/submission_guarded_knn.csv"
subB.to_csv(pathB, index=False)
print("Wrote:", pathB, "| rows:", len(subB))

Wrote: /content/drive/My Drive/IISC_data/submission_guarded_knn.csv | rows: 84600

In [ ]:
# === C) BIAS-LITE (λ=0.3) PER HOUR-OF-DAY + SMOOTH ===
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Needs bias_table from your earlier cell.
if "bias_table" not in globals():
    raise RuntimeError("bias_table not found in this runtime. Re-run the bias-table cell from earlier first.")

base = pd.read_csv(f"{DATA_DIR}/submission_simple_smooth.csv").rename(columns={"meter_reading":"y_base"})
meta = tgt_te[["row_id","building_id","window_id","timestamp"]].copy()
meta["hod"] = pd.to_datetime(meta["timestamp"], errors="coerce").dt.hour.astype("Int16")

dfc = base.merge(meta, on="row_id", how="left").sort_values(["building_id","window_id","timestamp"])

def sum_preserving_smooth24(y):
    y = y.astype(np.float32)
    s_old = float(y.sum())
    z = y.copy()
    out = y.copy()
    for h in range(24):
        left  = z[h-1] if h>0 else z[1]
        mid   = z[h]
        right = z[h+1] if h<23 else z[22]
        out[h]  = 0.25*left + 0.5*mid + 0.25*right
    s_new = float(out.sum()) + 1e-8
    return out * (s_old / s_new)

LAM = 0.30  # gentle correction factor
rows_out, vals_out = [], []

for (b,w), gi in dfc.groupby(["building_id","window_id"]):
    b = str(b)
    rows = gi["row_id"].to_numpy()
    y    = gi["y_base"].to_numpy(dtype=np.float32)
    hod  = gi["hod"].to_numpy()

    if b in bias_table and len(y)==24:
        bias_vec = np.array([bias_table[b].get(int(h), 0.0) for h in hod], dtype=np.float32)
        y = y - LAM * bias_vec  # partial correction only

    y = sum_preserving_smooth24(np.clip(y, 0, None))
    y = np.clip(y, 0, None)
    rows_out.append(rows); vals_out.append(y)

subC = pd.DataFrame({"row_id": np.concatenate(rows_out),
                     "meter_reading": np.concatenate(vals_out).astype(np.float32)}
                   ).sort_values("row_id").reset_index(drop=True)

pathC = f"{DATA_DIR}/submission_biaslite_smooth.csv"
subC.to_csv(pathC, index=False)
print("Wrote:", pathC, "| rows:", len(subC))

Wrote: /content/drive/My Drive/IISC_data/submission_biaslite_smooth.csv | rows: 84600

In [ ]:
import os, numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load test once (we need target grouping + 168h inputs)
test_cols  = ["row_id","building_id","window_id","timestamp","meter_reading","role"]
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", usecols=test_cols, parse_dates=["timestamp"])
inp_te  = test_df.query("role=='input'").copy()
tgt_te  = test_df.query("role=='target'").copy()

# Load your two strong base submissions
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

base = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
base["m_lgbm"] = pd.to_numeric(base["m_lgbm"], errors="coerce").fillna(base["m_med"])

In [ ]:
# Map row_id -> (bld, win, ts) to keep daily grouping intact
meta = (tgt_te[["row_id","building_id","window_id","timestamp"]]
        .sort_values(["building_id","window_id","timestamp"]))

df0 = base.merge(meta, on="row_id", how="left")
W0 = 0.235
df0["meter_reading"] = np.clip((1.0 - W0)*df0["m_med"].values + W0*df0["m_lgbm"].values, 0, None).astype(np.float32)

sub0 = df0[["row_id","meter_reading"]].sort_values("row_id").reset_index(drop=True)
p0 = f"{DATA_DIR}/submission_w235_exact.csv"
sub0.to_csv(p0, index=False)
print("Wrote:", p0, "| rows:", len(sub0))

Wrote: /content/drive/My Drive/IISC_data/submission_w235_exact.csv | rows: 84600

In [ ]:
# Cache last-168 per (bld,win) from test inputs; also compute rampiness quantile
g = (inp_te.sort_values(["building_id","window_id","timestamp"])
          .groupby(["building_id","window_id"])["meter_reading"])

x168_map = {}
ramp_scores = []

for (b,w), s in g:
    v = s.tail(168).to_numpy(np.float32)
    if len(v) == 168:
        x168_map[(str(b), int(w))] = v
        # rampiness: max abs diff of last day (recent 24h)
        last24 = v[-24:]
        ramp_scores.append(float(np.max(np.abs(np.diff(last24)))))

# thresholds to detect "rampy" days
q75 = np.quantile(ramp_scores, 0.75) if ramp_scores else 0.0
q90 = np.quantile(ramp_scores, 0.90) if ramp_scores else 0.0
print("Ramp thresholds:", q75, q90, "| cached windows:", len(x168_map))

Ramp thresholds: 2.611800193786621 4.245199966430664 | cached windows: 3525

In [ ]:
def robust_standardize(x):
    med = np.median(x)
    mad = np.median(np.abs(x - med)) + 1e-6
    return (x - med) / mad

def cos_sim(a, b):
    na = np.linalg.norm(a); nb = np.linalg.norm(b)
    if na < 1e-8 or nb < 1e-8: return 0.0
    return float(np.dot(a, b) / (na * nb))

def day_chunks_7(x168):
    return [x168[i*24:(i+1)*24] for i in range(7)]

def adaptive_blend_window(y_base_24, x168, ramp_q75, ramp_q90):
    """
    y_base_24: base 24-vector (MED⊕LGBM w=0.235)
    x168: last-168 vector
    Returns: adjusted 24-vector (no smoothing, clipped >=0)
    """
    days = day_chunks_7(x168)    # [d0 ... d6], d6 is most recent day
    if len(days) != 7 or any(len(d)!=24 for d in days):
        return np.clip(y_base_24, 0, None)

    prev_day = days[-1]
    weekago  = days[0]

    # 1) ramp-aware LGBM weight tweak around your 0.235
    ramp_score = float(np.max(np.abs(np.diff(prev_day))))
    if ramp_score >= ramp_q90:
        w_lgbm = 0.32   # very rampy → trust LGBM more
    elif ramp_score >= ramp_q75:
        w_lgbm = 0.27
    else:
        w_lgbm = 0.20   # flat → lean safer

    # reconstruct an *adaptive* base from the two columns we have
    # NOTE: we don't have per-hour separate med/lgbm anymore here,
    # so we start from provided y_base_24 (already at 0.235)
    # and nudge toward or away from LGBM by mixing with weekly copy.
    y = y_base_24.copy()

    # 2) tiny weekly-copy assist only if shapes align
    c = cos_sim(robust_standardize(prev_day), robust_standardize(weekago))
    energy_ratio = (weekago.sum()+1e-6)/(prev_day.sum()+1e-6)
    if c >= 0.88 and 0.85 <= energy_ratio <= 1.15:
        alpha_wc = min(0.12, max(0.0, (c - 0.88) / 0.12))  # 0..0.12 as c goes 0.88→1.0
        y = (1.0 - alpha_wc)*y + alpha_wc*weekago

    # 3) energy calibration to robust next-day expectation:
    # use median of last 3 day sums (prev 1–3 days), safer than week-ago
    day_sums = np.array([d.sum() for d in days[-3:]], dtype=np.float32)
    target_sum = float(np.median(day_sums))
    scale = np.clip(target_sum / (float(y.sum()) + 1e-8), 0.90, 1.10)
    y = np.clip(y * scale, 0, None)

    return y.astype(np.float32)

In [ ]:
# Start from your exact w=0.235 blend (sub0)
df2 = sub0.merge(tgt_te[["row_id","building_id","window_id"]], on="row_id", how="left") \
          .rename(columns={"meter_reading":"y_base"})

rows_out, vals_out = [], []

for (b,w), gi in df2.sort_values(["building_id","window_id"]).groupby(["building_id","window_id"]):
    key = (str(b), int(w))
    rows = gi["row_id"].to_numpy()
    yb   = gi["y_base"].to_numpy(dtype=np.float32)
    if key in x168_map and len(yb)==24:
        y_adj = adaptive_blend_window(yb, x168_map[key], q75, q90)
    else:
        y_adj = np.clip(yb, 0, None)
    rows_out.append(rows); vals_out.append(y_adj)

sub2 = pd.DataFrame({"row_id": np.concatenate(rows_out),
                     "meter_reading": np.concatenate(vals_out).astype(np.float32)}
                   ).sort_values("row_id").reset_index(drop=True)

p2 = f"{DATA_DIR}/submission_adapt_weekcal.csv"
sub2.to_csv(p2, index=False)
print("Wrote:", p2, "| rows:", len(sub2), "| min/max:", sub2.meter_reading.min(), sub2.meter_reading.max())

Wrote: /content/drive/My Drive/IISC_data/submission_adapt_weekcal.csv | rows: 84600 | min/max: 0.0 8.180899620056152

In [ ]:
knn_path = f"{DATA_DIR}/submission_knn_improved.csv"
use_knn = os.path.exists(knn_path)
print("KNN file exists:", use_knn)

if use_knn:
    knn = pd.read_csv(knn_path).rename(columns={"meter_reading":"y_knn"})
    df3 = sub2.rename(columns={"meter_reading":"y_now"}) \
              .merge(knn, on="row_id", how="left") \
              .merge(tgt_te[["row_id","building_id","window_id","timestamp"]], on="row_id", how="left") \
              .sort_values(["building_id","window_id","timestamp"])

    def cos_sim(a, b):
        na = np.linalg.norm(a); nb = np.linalg.norm(b)
        if na < 1e-8 or nb < 1e-8: return 0.0
        return float(np.dot(a, b) / (na * nb))

    rows_out, vals_out = [], []
    for (b,w), gi in df3.groupby(["building_id","window_id"]):
        rows = gi["row_id"].to_numpy()
        y0   = gi["y_now"].to_numpy(dtype=np.float32)
        yk   = gi["y_knn"].to_numpy(dtype=np.float32)

        if len(y0)==24 and not np.isnan(yk).any():
            c = cos_sim(y0, yk)
            sum_ratio = float((yk.sum()+1e-6)/(y0.sum()+1e-6))
            w_knn = 0.08 if (c >= 0.90 and 0.95 <= sum_ratio <= 1.05) else 0.00
            y = np.clip((1.0 - w_knn)*y0 + w_knn*yk, 0, None)
        else:
            y = y0

        rows_out.append(rows); vals_out.append(y)

    sub3 = pd.DataFrame({"row_id": np.concatenate(rows_out),
                         "meter_reading": np.concatenate(vals_out).astype(np.float32)}
                       ).sort_values("row_id").reset_index(drop=True)

    p3 = f"{DATA_DIR}/submission_adapt_weekcal_guardedknn.csv"
    sub3.to_csv(p3, index=False)
    print("Wrote:", p3, "| rows:", len(sub3))

KNN file exists: True
Wrote: /content/drive/My Drive/IISC_data/submission_adapt_weekcal_guardedknn.csv | rows: 84600

In [ ]:
import os, numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"

# Load test
test_cols = ["row_id","building_id","window_id","timestamp","meter_reading","role"]
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", usecols=test_cols, parse_dates=["timestamp"])
inp_te  = test_df.query("role=='input'").copy()
tgt_te  = test_df.query("role=='target'").copy()

# Load base submissions
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

base = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
base["m_lgbm"] = pd.to_numeric(base["m_lgbm"], errors="coerce").fillna(base["m_med"])

# Map row_id → (bld, win, ts) for grouping
meta = (tgt_te[["row_id","building_id","window_id","timestamp"]]
        .sort_values(["building_id","window_id","timestamp"]))
df_base = base.merge(meta, on="row_id", how="left")

# Cache last-168 per (bld,win) and rampiness thresholds
g = (inp_te.sort_values(["building_id","window_id","timestamp"])
          .groupby(["building_id","window_id"])["meter_reading"])
x168_map, ramp_scores = {}, []
for (b,w), s in g:
    v = s.tail(168).to_numpy(np.float32)
    if len(v)==168:
        x168_map[(str(b), int(w))] = v
        last24 = v[-24:]
        ramp_scores.append(float(np.max(np.abs(np.diff(last24)))))

q75 = np.quantile(ramp_scores, 0.75) if ramp_scores else 0.0
q90 = np.quantile(ramp_scores, 0.90) if ramp_scores else 0.0
print("Cached windows:", len(x168_map), "| rampiness Q75/Q90:", q75, q90)

# Optional KNN predictions (from your improved KNN)
knn_path = f"{DATA_DIR}/submission_knn_improved.csv"
HAS_KNN = os.path.exists(knn_path)
if HAS_KNN:
    knn_df = pd.read_csv(knn_path).rename(columns={"meter_reading":"y_knn"}).sort_values("row_id")
    print("Found KNN file:", knn_path)
else:
    print("KNN file not found, guarded KNN variants will skip KNN.")

Cached windows: 3525 | rampiness Q75/Q90: 2.611800193786621 4.245199966430664
Found KNN file: /content/drive/My Drive/IISC_data/submission_knn_improved.csv

In [ ]:
def robust_standardize(x):
    med = np.median(x); mad = np.median(np.abs(x - med)) + 1e-6
    return (x - med) / mad

def cos_sim(a, b):
    na = np.linalg.norm(a); nb = np.linalg.norm(b)
    if na < 1e-8 or nb < 1e-8: return 0.0
    return float(np.dot(a, b) / (na * nb))

def day_chunks_7(x168):  # [24]*7
    return [x168[i*24:(i+1)*24] for i in range(7)]

def anti_spike_isolated(y, factor=1.80, max_fixes=2):
    """Trim at most 2 isolated needles; no sum re-match."""
    y = y.astype(np.float32).copy()
    fixes = 0
    for i in range(1, 23):
        if fixes >= max_fixes: break
        if y[i] > max(y[i-1], y[i+1]) * factor:
            y[i] = 0.5 * (y[i-1] + y[i+1])
            fixes += 1
    return y

def window_adjust(y_med24, y_lgb24, x168, W, alpha_max, c_thresh, e_tol, ramp_q75, ramp_q90,
                  use_knn=False, y_knn24=None, knn_w=0.05, knn_c=0.93, knn_sum_lo=0.98, knn_sum_hi=1.02,
                  use_antispike=False):
    """
    Build per-window 24h prediction with tiny, safe adjustments.
    y_med24, y_lgb24: arrays length 24 (from MED/LGBM for this window)
    x168: last-168 vector
    W: global LGBM weight
    alpha_max: max weekly-copy assist (<=0.12)
    c_thresh: cosine threshold for allowing weekly assist (0.90–0.92+)
    e_tol: energy cal tolerance, e.g., 0.08 → ±8%
    """
    y = np.clip((1.0 - W)*y_med24 + W*y_lgb24, 0, None).astype(np.float32)

    days = day_chunks_7(x168)
    if len(days)==7 and all(len(d)==24 for d in days):
        prev_day, weekago = days[-1], days[0]

        # ramp-aware nudge of W around given global W (±0.03 band)
        ramp = float(np.max(np.abs(np.diff(prev_day))))
        if ramp >= ramp_q90:   W_eff = min(W+0.03, 0.35)
        elif ramp >= ramp_q75: W_eff = min(W+0.02, 0.35)
        else:                  W_eff = max(W-0.02, 0.15)
        y = np.clip((1.0 - W_eff)*y_med24 + W_eff*y_lgb24, 0, None)

        # weekly-copy assist (shape+level agreement only)
        c = cos_sim(robust_standardize(prev_day), robust_standardize(weekago))
        er = (weekago.sum()+1e-6)/(prev_day.sum()+1e-6)
        if c >= c_thresh and (1.0 - e_tol) <= er <= (1.0 + e_tol):
            # scale alpha smoothly from threshold to 1.0
            alpha = np.clip((c - c_thresh) / (1.0 - c_thresh + 1e-9), 0.0, 1.0) * alpha_max
            y = (1.0 - alpha)*y + alpha*weekago

        # soft per-window energy calibration to robust expectation (median of last 3 days)
        target_sum = float(np.median([d.sum() for d in days[-3:]]))
        scale = np.clip(target_sum / (float(y.sum()) + 1e-8), 1.0 - e_tol, 1.0 + e_tol)
        y = y * scale

    # optional guarded KNN
    if use_knn and y_knn24 is not None and len(y_knn24)==24:
        c2 = cos_sim(y, y_knn24)
        sr = float((y_knn24.sum()+1e-6)/(y.sum()+1e-6))
        if c2 >= knn_c and knn_sum_lo <= sr <= knn_sum_hi:
            y = (1.0 - knn_w)*y + knn_w*y_knn24

    # optional anti-spike on isolated needles
    if use_antispike:
        y = anti_spike_isolated(y, factor=1.80, max_fixes=2)

    return np.clip(y, 0, None).astype(np.float32)

In [ ]:
# Prepare per-window MED/LGB arrays (for speed)
df_b = df_base.sort_values(["building_id","window_id","timestamp"]).copy()
df_b["m_lgbm"] = pd.to_numeric(df_b["m_lgbm"], errors="coerce").fillna(df_b["m_med"])

# If KNN present, merge it
if HAS_KNN:
    df_b = df_b.merge(knn_df, on="row_id", how="left")

def build_variant(tag, W, alpha_max, c_thresh, e_tol,
                  use_knn=False, knn_w=0.05, knn_c=0.93, knn_sum_lo=0.98, knn_sum_hi=1.02,
                  use_antispike=False):
    rows_all, vals_all = [], []
    for (b,w), gi in df_b.groupby(["building_id","window_id"], sort=False):
        key = (str(b), int(w))
        rows = gi["row_id"].to_numpy()
        y_med = gi["m_med"].to_numpy(np.float32)
        y_lgb = gi["m_lgbm"].to_numpy(np.float32)
        if len(y_med) != 24: continue

        x168 = x168_map.get(key, None)
        y_knn = gi["y_knn"].to_numpy(np.float32) if HAS_KNN and "y_knn" in gi else None

        y = window_adjust(
            y_med24=y_med, y_lgb24=y_lgb, x168=x168 if x168 is not None else np.zeros(168, np.float32),
            W=W, alpha_max=alpha_max, c_thresh=c_thresh, e_tol=e_tol,
            ramp_q75=q75, ramp_q90=q90,
            use_knn=(use_knn and HAS_KNN), y_knn24=(y_knn if (y_knn is not None and len(y_knn)==24) else None),
            knn_w=knn_w, knn_c=knn_c, knn_sum_lo=knn_sum_lo, knn_sum_hi=knn_sum_hi,
            use_antispike=use_antispike
        )
        rows_all.append(rows); vals_all.append(y)

    sub = pd.DataFrame({"row_id": np.concatenate(rows_all),
                        "meter_reading": np.concatenate(vals_all).astype(np.float32)}
                      ).sort_values("row_id").reset_index(drop=True)
    path = f"{DATA_DIR}/{tag}.csv"
    sub.to_csv(path, index=False)
    print("Wrote:", path, "| rows:", len(sub), "| min/max:", sub.meter_reading.min(), sub.meter_reading.max())
    return path

# === Variants ===
# v1: W=0.22, alpha=0.10, c>=0.92, energy ±9%   (conservative)
p1 = build_variant("submission_v1_W022_A010_C092_E009",
                   W=0.22, alpha_max=0.10, c_thresh=0.92, e_tol=0.09,
                   use_knn=False, use_antispike=False)

# v2: W=0.235, alpha=0.08, c>=0.92, energy ±8%  (tight around your best)  ← try first
p2 = build_variant("submission_v2_W0235_A008_C092_E008",
                   W=0.235, alpha_max=0.08, c_thresh=0.92, e_tol=0.08,
                   use_knn=False, use_antispike=False)

# v3: W=0.25, alpha=0.10, c>=0.90, energy ±10%  (slightly more trusting)
p3 = build_variant("submission_v3_W025_A010_C090_E010",
                   W=0.25, alpha_max=0.10, c_thresh=0.90, e_tol=0.10,
                   use_knn=False, use_antispike=False)

# v4: v2 + guarded KNN (+5%) only if very strong agreement           ← try second
p4 = build_variant("submission_v4_v2_plus_guardedknn",
                   W=0.235, alpha_max=0.08, c_thresh=0.92, e_tol=0.08,
                   use_knn=True, knn_w=0.05, knn_c=0.935, knn_sum_lo=0.985, knn_sum_hi=1.015,
                   use_antispike=False)

# v5: v2 + micro anti-spike (≤2 fixes/day)                            ← try third
p5 = build_variant("submission_v5_v2_plus_antispike",
                   W=0.235, alpha_max=0.08, c_thresh=0.92, e_tol=0.08,
                   use_knn=False, use_antispike=True)

# v6: v2 + guarded KNN + anti-spike (both)
p6 = build_variant("submission_v6_v2_knn_antispike",
                   W=0.235, alpha_max=0.08, c_thresh=0.92, e_tol=0.08,
                   use_knn=True, knn_w=0.05, knn_c=0.935, knn_sum_lo=0.985, knn_sum_hi=1.015,
                   use_antispike=True)

Wrote: /content/drive/My Drive/IISC_data/submission_v1_W022_A010_C092_E009.csv | rows: 84600 | min/max: 0.0 8.151924133300781
Wrote: /content/drive/My Drive/IISC_data/submission_v2_W0235_A008_C092_E008.csv | rows: 84600 | min/max: 0.0 8.122963905334473
Wrote: /content/drive/My Drive/IISC_data/submission_v3_W025_A010_C090_E010.csv | rows: 84600 | min/max: 0.0 8.09401798248291
Wrote: /content/drive/My Drive/IISC_data/submission_v4_v2_plus_guardedknn.csv | rows: 84600 | min/max: 0.0 8.122963905334473
Wrote: /content/drive/My Drive/IISC_data/submission_v5_v2_plus_antispike.csv | rows: 84600 | min/max: 0.0 7.631286144256592
Wrote: /content/drive/My Drive/IISC_data/submission_v6_v2_knn_antispike.csv | rows: 84600 | min/max: 0.0 7.631286144256592

In [ ]:
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"  # change if needed

# Load base submissions
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})
df = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"]).astype(np.float32)
df["m_med"]  = pd.to_numeric(df["m_med"],  errors="coerce").astype(np.float32)

# Pull hour-of-day from test targets
test_cols = ["row_id","timestamp","role"]
tgt_te = pd.read_csv(f"{DATA_DIR}/test.csv", usecols=test_cols, parse_dates=["timestamp"])
tgt_te = tgt_te.query("role=='target'")[["row_id","timestamp"]]
df = df.merge(tgt_te, on="row_id", how="left")
df["hod"] = pd.to_datetime(df["timestamp"], errors="coerce").dt.hour.fillna(12).astype(int)

# Hour-gated weight schedule for LGBM (tuned around your 0.235 best)
def w_lgbm(h):
    if   0 <= h <= 5:   return 0.22   # quiet night → lean safer
    elif 6 <= h <= 10:  return 0.27   # morning ramp → trust LGBM more
    elif 11 <= h <= 16: return 0.23   # midday → close to baseline
    elif 17 <= h <= 21: return 0.27   # evening ramp → trust LGBM more
    else:               return 0.24   # late hours slight tilt

w = df["hod"].apply(w_lgbm).astype(np.float32).to_numpy()
y = np.clip((1.0 - w) * df["m_med"].to_numpy() + w * df["m_lgbm"].to_numpy(), 0, None).astype(np.float32)

sub = pd.DataFrame({"row_id": df["row_id"], "meter_reading": y}).sort_values("row_id").reset_index(drop=True)
path = f"{DATA_DIR}/submission_hourgated_lean.csv"
sub.to_csv(path, index=False)
print("Wrote:", path, "| rows:", len(sub), "| min/max:", float(sub.meter_reading.min()), float(sub.meter_reading.max()))

Wrote: /content/drive/My Drive/IISC_data/submission_hourgated_lean.csv | rows: 84600 | min/max: 0.0 8.20401382446289

In [ ]:
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"  # change if needed

# ---- Load test (for grouping / inputs) ----
test_cols = ["row_id","building_id","window_id","timestamp","meter_reading","role"]
test_df = pd.read_csv(f"{DATA_DIR}/test.csv", usecols=test_cols, parse_dates=["timestamp"])
inp_te  = test_df.query("role=='input'").copy()
tgt_te  = test_df.query("role=='target'").copy()

# ---- Load base submissions ----
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"]).astype(np.float32)
df["m_med"]  = pd.to_numeric(df["m_med"],  errors="coerce").astype(np.float32)

# ---- Map row_id → (bld, win, ts, hod) ----
meta = tgt_te[["row_id","building_id","window_id","timestamp"]].copy()
meta["hod"] = pd.to_datetime(meta["timestamp"], errors="coerce").dt.hour.fillna(12).astype(int)
df = df.merge(meta, on="row_id", how="left").sort_values(["building_id","window_id","timestamp"])

# ---- Cache last-168 per (bld, win) ----
g = (inp_te.sort_values(["building_id","window_id","timestamp"])
          .groupby(["building_id","window_id"])["meter_reading"])
x168_map = {}
ramp_scores = []
for (b,w), s in g:
    v = s.tail(168).to_numpy(np.float32)
    if len(v)==168:
        x168_map[(str(b), int(w))] = v
        ramp_scores.append(float(np.max(np.abs(np.diff(v[-24:])))))
q75 = np.quantile(ramp_scores, 0.75) if ramp_scores else 0.0
q90 = np.quantile(ramp_scores, 0.90) if ramp_scores else 0.0

# ---- Helpers ----
def day_chunks_7(x168): return [x168[i*24:(i+1)*24] for i in range(7)]
def robust_standardize(x):
    med = np.median(x); mad = np.median(np.abs(x - med)) + 1e-6
    return (x - med) / mad
def cos_sim(a,b):
    na = np.linalg.norm(a); nb = np.linalg.norm(b)
    if na < 1e-8 or nb < 1e-8: return 0.0
    return float(np.dot(a,b)/(na*nb))
def anti_spike_once(y, factor=2.2):
    y = y.astype(np.float32).copy()
    for i in range(1,23):
        if y[i] > max(y[i-1], y[i+1]) * factor:
            y[i] = 0.5*(y[i-1]+y[i+1])
            break
    return y

# Hour-gated LGBM weight (leaner than last time)
def w_lgbm(h):
    if   0 <= h <= 5:   return 0.22
    elif 6 <= h <= 10:  return 0.275
    elif 11 <= h <= 16: return 0.235
    elif 17 <= h <= 21: return 0.275
    else:               return 0.24

# ---- Build per-window predictions ----
rows_all, vals_all = [], []
for (b,w), gi in df.groupby(["building_id","window_id"], sort=False):
    key = (str(b), int(w))
    rows = gi["row_id"].to_numpy()
    hods = gi["hod"].to_numpy()
    yM   = gi["m_med"].to_numpy(np.float32)
    yL   = gi["m_lgbm"].to_numpy(np.float32)
    if len(yM)!=24: continue

    # 1) Hour-gated blend
    w_vec = np.array([w_lgbm(int(h)) for h in hods], dtype=np.float32)
    y = np.clip((1.0 - w_vec)*yM + w_vec*yL, 0, None)

    # 2) Convex day-sum calibration (tight ±6%)
    x168 = x168_map.get(key, None)
    if x168 is not None and len(x168)==168:
        days = day_chunks_7(x168)  # [d0..d6] (d6 is prev_day, d0 weekago)
        if len(days)==7 and all(len(d)==24 for d in days):
            prev_day, weekago = days[-1], days[0]
            c = cos_sim(robust_standardize(prev_day), robust_standardize(weekago))
            # similarity-driven alpha for target day-sum: more weight on prev_day when c is high
            if c >= 0.94:   alpha = 0.75
            elif c >= 0.90: alpha = 0.65
            elif c >= 0.86: alpha = 0.55
            else:           alpha = 0.50
            target_sum = alpha*float(prev_day.sum()) + (1-alpha)*float(weekago.sum())
            scale = np.clip(target_sum / (float(y.sum()) + 1e-8), 0.94, 1.06)  # ±6%
            y = y * scale

    # 3) Micro anti-spike (at most one fix)
    y = anti_spike_once(y, factor=2.2)
    y = np.clip(y, 0, None).astype(np.float32)

    rows_all.append(rows); vals_all.append(y)

sub = pd.DataFrame({"row_id": np.concatenate(rows_all),
                    "meter_reading": np.concatenate(vals_all).astype(np.float32)}
                  ).sort_values("row_id").reset_index(drop=True)

path = f"{DATA_DIR}/submission_v7_hourgate_convexsum_antispike.csv"
sub.to_csv(path, index=False)
print("Wrote:", path, "| rows:", len(sub), "| min/max:", sub.meter_reading.min(), sub.meter_reading.max())

Wrote: /content/drive/My Drive/IISC_data/submission_v7_hourgate_convexsum_antispike.csv | rows: 84600 | min/max: 0.0 8.515666961669922

In [ ]:
import numpy as np
import pandas as pd

# =========================
# Config / Paths
# =========================
DATA_DIR = "/content/drive/My Drive/IISC_data"  # <-- change if needed
TRAIN_PATH = f"{DATA_DIR}/train.csv"
TEST_PATH  = f"{DATA_DIR}/test.csv"
SUB_MED    = f"{DATA_DIR}/submission_ens_median_top.csv"
SUB_LGBM   = f"{DATA_DIR}/submission_lgbm.csv"
OUT_PATH   = f"{DATA_DIR}/submission_nnls_hour_weights.csv"

# =========================
# 1) Load data
# =========================
train = pd.read_csv(TRAIN_PATH, parse_dates=["timestamp"])
test  = pd.read_csv(TEST_PATH,  parse_dates=["timestamp"])

# Two base TEST submissions (already computed by you)
sub_med = (pd.read_csv(SUB_MED)
             .sort_values("row_id")
             .rename(columns={"meter_reading":"m_med"}))
sub_lgb = pd.read_csv(SUB_LGBM).sort_values("row_id")
sub_lgb = (sub_lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"})
           if "meter_reading_lgbm" in sub_lgb.columns
           else sub_lgb.rename(columns={"meter_reading":"m_lgbm"}))

# =========================
# 2) Build train rolling windows (168 -> 24) without .apply()
# =========================
def pack_train_windows(df: pd.DataFrame):
    """Return aligned train windows:
       keys: list[(building_id, window_id)]
       X:    (n_win, 168) last-168 inputs
       Y:    (n_win, 24)  next-24 true targets
       T0:   list of first target timestamps per window (for reference)
    """
    df = df.sort_values(["building_id","window_id","timestamp"])
    inp = df[df["role"] == "input"]
    tgt = df[df["role"] == "target"]

    # last 168 hours per (bld, win)
    X_dict = {}
    for (b,w), gi in inp.groupby(["building_id","window_id"], sort=False):
        v = gi["meter_reading"].to_numpy(np.float32)
        if len(v) >= 168:
            X_dict[(str(b), int(w))] = v[-168:]

    # next 24 hours per (bld, win)
    Y_dict, T0_dict = {}, {}
    for (b,w), gi in tgt.groupby(["building_id","window_id"], sort=False):
        v = gi["meter_reading"].to_numpy(np.float32)
        if len(v) == 24:
            key = (str(b), int(w))
            Y_dict[key]  = v
            T0_dict[key] = pd.to_datetime(gi["timestamp"], errors="coerce").iloc[0]

    # align
    keys = sorted(set(X_dict.keys()) & set(Y_dict.keys()))
    X = np.stack([X_dict[k] for k in keys], axis=0)
    Y = np.stack([Y_dict[k] for k in keys], axis=0)
    T0 = [T0_dict[k] for k in keys]
    return keys, X, Y, T0

keys_tr, Xtr, Ytr, T0 = pack_train_windows(train)
print("Aligned train windows:", Xtr.shape, Ytr.shape)

# =========================
# 3) Proxies on train (leak-safe, simple)
# =========================
def weekly_copy_24(x168: np.ndarray) -> np.ndarray:
    """MED proxy: first 24h of the last-168 (i.e., same hours a week ago)."""
    return x168[:24].astype(np.float32)

def lgbm_proxy_from_x(x168: np.ndarray) -> np.ndarray:
    """LGBM proxy: tiny fixed linear combo of lags {1, 24, 168}.
       This approximates a lags-ridge and tracks LGBM's behavior reasonably well.
    """
    last24 = x168[-24:]
    lag1   = np.r_[last24[-1], last24[:-1]]
    lag24  = x168[-48:-24]
    lag168 = x168[:24]
    return (0.50*lag1 + 0.30*lag24 + 0.20*lag168).astype(np.float32)

med_proxy = np.stack([weekly_copy_24(x)   for x in Xtr], axis=0)
lgb_proxy = np.stack([lgbm_proxy_from_x(x) for x in Xtr], axis=0)

# =========================
# 4) Learn hour-of-day weights (NNLS + sum-to-one via tiny grid)
# =========================
# For each hour h, solve:
#   min_{w in [0,1]}  MSE( y_h , (1-w)*med_h + w*lgb_h )
# This is equivalent to non-negative weights that sum to 1.
W_h = np.zeros(24, dtype=np.float32)
grid = np.linspace(0.00, 1.00, 101)  # 0..1 in 0.01 steps

for h in range(24):
    y = Ytr[:, h]
    m = med_proxy[:, h]
    l = lgb_proxy[:, h]
    best_w, best_mse = 0.5, 1e18
    # try all convex weights on a fine grid
    for w in grid:
        yhat = (1.0 - w)*m + w*l
        mse  = np.mean((y - yhat)**2)
        if mse < best_mse:
            best_mse, best_w = mse, float(w)
    W_h[h] = best_w

print("Learned LGBM hour-weights:", np.round(W_h, 3))

# =========================
# 5) Apply learned hour-weights to TEST submissions
# =========================
test_tgt = test[test["role"]=="target"][["row_id","timestamp"]].copy()
test_tgt["hod"] = pd.to_datetime(test_tgt["timestamp"], errors="coerce").dt.hour.astype(int)

sub = (sub_med.merge(sub_lgb[["row_id","m_lgbm"]], on="row_id", how="left")
              .merge(test_tgt[["row_id","hod"]],       on="row_id", how="left")
              .sort_values("row_id"))
sub["m_lgbm"] = pd.to_numeric(sub["m_lgbm"], errors="coerce").fillna(sub["m_med"]).astype(np.float32)
sub["m_med"]  = pd.to_numeric(sub["m_med"],  errors="coerce").astype(np.float32)

# map hod -> weight, then blend
w_map = {h: W_h[h] for h in range(24)}
w_vec = sub["hod"].map(w_map).astype(np.float32).to_numpy()

y_pred = (1.0 - w_vec) * sub["m_med"].to_numpy() + w_vec * sub["m_lgbm"].to_numpy()
y_pred = np.clip(y_pred.astype(np.float32), 0, None)

out = pd.DataFrame({"row_id": sub["row_id"], "meter_reading": y_pred}).sort_values("row_id").reset_index(drop=True)
out.to_csv(OUT_PATH, index=False)
print(f"Wrote: {OUT_PATH} | rows: {len(out)} | min/max: {float(out.meter_reading.min()):.6f}/{float(out.meter_reading.max()):.6f}")

Aligned train windows: (13453, 168) (13453, 24)
Learned LGBM hour-weights: [1.   0.95 0.97 0.97 0.99 0.88 0.67 0.69 0.66 0.7  0.66 0.75 0.76 0.7
 0.8  0.92 0.8  0.82 0.84 0.88 0.9  0.84 0.93 0.89]
Wrote: /content/drive/My Drive/IISC_data/submission_nnls_hour_weights.csv | rows: 84600 | min/max: 0.000000/8.836600

In [ ]:
import numpy as np, pandas as pd

DATA_DIR = "/content/drive/My Drive/IISC_data"  # change if needed
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df["m_med"]  = pd.to_numeric(df["m_med"],  errors="coerce").astype(np.float32)
df["m_lgbm"] = pd.to_numeric(df["m_lgbm"], errors="coerce").fillna(df["m_med"]).astype(np.float32)

def write_blend(w, suffix=None):
    y = np.clip((1.0 - w)*df["m_med"].to_numpy() + w*df["m_lgbm"].to_numpy(), 0, None).astype(np.float32)
    out = pd.DataFrame({"row_id": df["row_id"], "meter_reading": y}).sort_values("row_id").reset_index(drop=True)
    name = f"submission_med_lgbm_w{int(round(w*1000)):03d}" if suffix is None else suffix
    path = f"{DATA_DIR}/{name}.csv"
    out.to_csv(path, index=False)
    print(f"Wrote: {path} | rows: {len(out)} | min/max: {float(out.meter_reading.min()):.6f}/{float(out.meter_reading.max()):.6f}")
    return path

# grid around your best 0.235
weights = [0.228, 0.230, 0.232, 0.233, 0.235, 0.236, 0.237, 0.239]
for w in weights:
    write_blend(w)

Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w228.csv | rows: 84600 | min/max: 0.000000/8.221481
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w230.csv | rows: 84600 | min/max: 0.000000/8.213037
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w232.csv | rows: 84600 | min/max: 0.000000/8.204594
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w233.csv | rows: 84600 | min/max: 0.000000/8.200372
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w235.csv | rows: 84600 | min/max: 0.000000/8.191927
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w236.csv | rows: 84600 | min/max: 0.000000/8.187705
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w237.csv | rows: 84600 | min/max: 0.000000/8.183484
Wrote: /content/drive/My Drive/IISC_data/submission_med_lgbm_w239.csv | rows: 84600 | min/max: 0.000000/8.175039

In [ ]:
import numpy as np, pandas as pd
from numpy.linalg import lstsq

DATA_DIR = "/content/drive/My Drive/IISC_data"  # adjust

# --- Load base submissions (unchanged) ---
med = pd.read_csv(f"{DATA_DIR}/submission_ens_median_top.csv").sort_values("row_id").rename(columns={"meter_reading":"m_med"})
lgb = pd.read_csv(f"{DATA_DIR}/submission_lgbm.csv").sort_values("row_id")
lgb = lgb.rename(columns={"meter_reading_lgbm":"m_lgbm"}) if "meter_reading_lgbm" in lgb.columns else lgb.rename(columns={"meter_reading":"m_lgbm"})

df_base = med.merge(lgb[["row_id","m_lgbm"]], on="row_id", how="left")
df_base["m_med"]  = pd.to_numeric(df_base["m_med"],  errors="coerce").astype(np.float32)
df_base["m_lgbm"] = pd.to_numeric(df_base["m_lgbm"], errors="coerce").fillna(df_base["m_med"]).astype(np.float32)

# Exact best baseline (your winner): w=0.235
W = 0.235
df_base["y_base"] = np.clip((1.0 - W)*df_base["m_med"].to_numpy() + W*df_base["m_lgbm"].to_numpy(), 0, None).astype(np.float32)

# --- Load test for grouping and last-168 inputs ---
test = pd.read_csv(f"{DATA_DIR}/test.csv", parse_dates=["timestamp"])
inp_te = test.query("role=='input'").copy()
tgt_te = test.query("role=='target'").copy()

# cache last-168 per (building, window)
x168_map = {}
for (b,w), gi in inp_te.sort_values(["building_id","window_id","timestamp"]).groupby(["building_id","window_id"], sort=False):
    v = gi["meter_reading"].tail(168).to_numpy(np.float32)
    if len(v)==168:
        x168_map[(str(b), int(w))] = v

# --- Fourier+trend extrapolation from last-168 to next-24 ---
def fourier_forecast_24(y168, daily_K=3, weekly_K=1):
    """
    Fit LS on last 168 samples with:
    intercept + linear trend + daily harmonics (K) + weekly harmonics (K2),
    then forecast the next 24 steps.
    """
    n = 168
    t = np.arange(n, dtype=np.float32)

    # design on history
    cols = [np.ones(n, np.float32), t]  # intercept + trend

    # daily (period=24)
    for k in range(1, daily_K+1):
        ang = 2*np.pi*k*t/24.0
        cols.append(np.sin(ang)); cols.append(np.cos(ang))

    # weekly (period=168)
    for k in range(1, weekly_K+1):
        ang = 2*np.pi*k*t/168.0
        cols.append(np.sin(ang)); cols.append(np.cos(ang))

    X = np.vstack(cols).T  # [168, p]
    beta, *_ = lstsq(X, y168, rcond=None)

    # design for forecast horizon
    t_f = np.arange(n, n+24, dtype=np.float32)
    cols_f = [np.ones_like(t_f), t_f]
    for k in range(1, daily_K+1):
        ang = 2*np.pi*k*t_f/24.0
        cols_f.append(np.sin(ang)); cols_f.append(np.cos(ang))
    for k in range(1, weekly_K+1):
        ang = 2*np.pi*k*t_f/168.0
        cols_f.append(np.sin(ang)); cols_f.append(np.cos(ang))
    Xf = np.vstack(cols_f).T  # [24, p]

    yhat = Xf @ beta
    return yhat.astype(np.float32)

def cos_sim(a, b):
    a = a.astype(np.float32); b = b.astype(np.float32)
    na = np.linalg.norm(a); nb = np.linalg.norm(b)
    if na < 1e-8 or nb < 1e-8: return 0.0
    return float(a @ b / (na*nb))

# Build per-window base + guarded Fourier
base = (df_base
        .merge(tgt_te[["row_id","building_id","window_id","timestamp"]], on="row_id", how="left")
        .sort_values(["building_id","window_id","timestamp"]))

rows_out, vals_out = [], []

# guard thresholds (very strict)
CS_MIN   = 0.93   # cosine similarity between base and Fourier shape
SUM_LOW  = 0.97   # day-sum ratio guard
SUM_HIGH = 1.03
W_FOUR   = 0.05   # at most +5% Fourier when it agrees

for (b,w), gi in base.groupby(["building_id","window_id"], sort=False):
    key = (str(b), int(w))
    rows = gi["row_id"].to_numpy()
    yb   = gi["y_base"].to_numpy(np.float32)

    y = yb
    if key in x168_map and len(yb)==24:
        y_four = fourier_forecast_24(x168_map[key], daily_K=3, weekly_K=1)
        # soft non-negativity
        y_four = np.clip(y_four, 0, None)

        # agreement checks
        cs = cos_sim(yb, y_four)
        sr = float((y_four.sum()+1e-6)/(yb.sum()+1e-6))

        if (cs >= CS_MIN) and (SUM_LOW <= sr <= SUM_HIGH):
            y = (1.0 - W_FOUR)*yb + W_FOUR*y_four  # tiny convex tap
        # else keep base

    y = np.clip(y, 0, None)
    rows_out.append(rows); vals_out.append(y.astype(np.float32))

sub = pd.DataFrame({
    "row_id": np.concatenate(rows_out),
    "meter_reading": np.concatenate(vals_out)
}).sort_values("row_id").reset_index(drop=True)

path = f"{DATA_DIR}/submission_base_plus_fourier_guarded.csv"
sub.to_csv(path, index=False)
print("Wrote:", path, "| rows:", len(sub), "| min/max:", float(sub.meter_reading.min()), float(sub.meter_reading.max()))

Wrote: /content/drive/My Drive/IISC_data/submission_base_plus_fourier_guarded.csv | rows: 84600 | min/max: 0.0 8.191926956176758